### ISSUE TITLE
error after mobile logout 

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect-server#1]
desconnectedMobile

info:     [test:token] Removind token file...
warn:     [test:token] Not Files: /project/tokens/test.data.json
error:    [test:page] Page Closed
browserClose

(node:656973) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink '/project/tokens/test.data.json'

**Comment by kingaspx** [comment]
Hello how are you? This problem was resolved in the last update of WPPConnect :)
