### ISSUE TITLE
BUG de envios de botões para iPhone

### ISSUE THREAD

**Issue by AlexORocha** [wppconnect-team/wppconnect-server#1021]
Prezados, boa tarde!

Estou utilizando a API do WppConnect para enviar alguns botões, porém, para dispositivos cujo SO é IOS (iPhone), o botão não é recebido, apenas em dispositivos Android.

Há alguma forma de corrigir isso?

Obrigado!

**Comment by renat473** [comment]
Olá,

Essa limitação e própria do whatsapp onde não podemos intervir nessa correção.
