### ISSUE TITLE
Falso erro ao criar grupo

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wppconnect-server#1033]
## Description

Ao criar grupo pelo /create-group, o grupo é criado mas retorna erro.
{
  "status": "error",
  "message": "Error creating group(s)",
  "session": "a8e4494773a5ae1c539b"
}

o body pode ter ou não participantes que o erro acontece.

{
  "name": "Teste do OZAP #002",
  "participants": "5516999887777"
}
{
  "name": "Teste do OZAP #002",
  "participants": ""
}

## Environment

- wppconnect-server: 1.8.0
- os: Ubuntu 20.04 (64 bits)
- node: 16.19.0

## Steps to Reproduce

Criar grupo pelo Swagger ou Postman

**Comment by icleitoncosta** [comment]
Olá, poderia testar na última versão? Já foi lançado uma correção para esse erro.

**Comment by icleitoncosta** [comment]
Esse é o mesmo erro que ajustei no commit https://github.com/wppconnect-team/wppconnect-server/commit/e60c9344bc7c77bb380fd01b42cbd9f22a0259c4

Abre o package.json e verifica se o SERVER está na versão 1.8.1, pois não foi no WppConnect (lib) que foi feito a correção, foi direto no server.

**Comment by GMUNDI** [comment]
Sim, é o server 1.8.1

Fiz a atualização ontem:

no diretório wpconnect-server
git pull https://github.com/wppconnect-team/wppconnect-server

npm update @wppconnect-team/wppconnect

Na inicialização do server informa que é o 1.8.1 e diz que está tudo atualizado.

**Comment by GMUNDI** [comment]
Ótimo, se tiver mais alguma coisa que eu possa fazer aqui ou testar para ajudar a identificar o erro me fala.

**Comment by icleitoncosta** [comment]
Opa @GMUNDI, fiz alguns testes, clonei o repósitório de novo, e fiz os testes com a criação de grupo, e tudo permaneceu correto, criando e retornando sem erros.

Assim que puder, me chama la no whats, que testamos juntos, para poder finalizar a issue.

**Comment by GMUNDI** [comment]
Testes realizados com uma nova instalação foram bem sucedidos. Pode finalizar a isuue.
