### ISSUE TITLE
Envio de mensagens para grupos

### ISSUE THREAD

**Issue by udsonassis** [wppconnect-team/wppconnect-server#1046]
Olá, gostaria de saber com enviar mensgens para grupos pela wppconenct-server. Estou consumindo a API pelo postman, listei os grupos, peguei alguns ids que imaginei que seria do grupo, tentei enviar pelo metodo e envio de mensagens substituindo o número do telefone pelo código do grupo, mas retorna que o numero nao existe.

**Comment by renat473** [comment]
tente passar o o parâmetro isGroup como true

**Comment by udsonassis** [comment]
@renat473 show de bola! Era o que faltava. Grato pela sua contribuição.
