### ISSUE TITLE
Novas opões para o /all-groups um ou novo endpoint

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wppconnect-server#1048]
Ao usar o /all-groups em alguns clientes, dá erro de timeout, pois alguns tem mais de 1000 grupos.

Como sugestão, a possibilidade de incluir algumas opções para reduzir a quantidade de dados e tempo de execução:

- isAdmin: só retorna os grupos nos quais a session é admin
- isSuperAdmin: só retorna os grupos nos quais a session é superadmin
- filterByName: filtra os grupos pelo nome
- completeData: (true/false) se traz todos os dados como acontece atualmente

**Comment by icleitoncosta** [comment]
Olá @GMUNDI, estou trabalhando em uma alternativa.

Assim que corrigir o código, irei pedir para você testar em um desses contatos com 1000 grupos, retornando sem travar, aí providenciamos uma alternativa para os filtros.

Ainda iremos lançar a correção na LIB, para posteriormente funcionar aqui, assim que o fizer, te aviso para testar.

**Comment by Saifallak** [comment]
@icleitoncosta would be awesome if done the same to get all chats too.
like the get messages endpoint,
getting data paginated

**Comment by icleitoncosta** [comment]
> @icleitoncosta would be awesome if done the same to get all chats too. like the get messages endpoint, getting data paginated

In all-chats it's a little more complicated, but this weekend, I'm going to try a solution that's on my mind.

**Comment by icleitoncosta** [comment]
> Ao usar o /all-groups em alguns clientes, dá erro de timeout, pois alguns tem mais de 1000 grupos.
> 
> Como sugestão, a possibilidade de incluir algumas opções para reduzir a quantidade de dados e tempo de execução:
> 
> * isAdmin: só retorna os grupos nos quais a session é admin
> * isSuperAdmin: só retorna os grupos nos quais a session é superadmin
> * filterByName: filtra os grupos pelo nome
> * completeData: (true/false) se traz todos os dados como acontece atualmente

Olá, agora você pode usar o list-chats recentemente adicionado, consulte mais informações no Swagger.
