### ISSUE TITLE
Always "initializing browser"

### ISSUE THREAD

**Issue by IgorDePaula** [wppconnect-team/wppconnect-server#1055]
## Description

always show message "initializing browser". the token is generated, but any action after this, is always "status: initializing"

## Environment

- **Environment:** docker (specifically docker-server-front)
- **config.json:** {
    "useChrome":true,
  "secretKey": "My53cr3tKY",
  "host": "http://localhost",
  "port": "21465",
  "startAllSession": true,
  "tokenStoreType": "file",
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "debug",
    "logger": [
      "console",
      "file"
    ]
  },
  "createOptions": {
      "headless":true,
      "useChrome":true,
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": true,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}

## Steps to Reproduce

1- git clone wppconnect-server
2- docker-compose up -d

## Log Output

```
docker logs -f wppconnect-server
yarn run v1.22.5
$ nodemon -w src --exec "babel-node src/server.js"
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node src/server.js`
info: 2023-01-15T10:15:16.949Z Server is running on port: 21465
info: 2023-01-15T10:15:16.956Z  Visit http://localhost:21465/api-docs for Swagger docs
info: 2023-01-15T10:15:16.956Z WPPConnect-Server version: 1.8.2
info: 2023-01-15T10:15:19.380Z ID: y4w0jpmLEcDCq8YqAAAB entrou
info: 2023-01-15T10:15:31.548Z ID: y4w0jpmLEcDCq8YqAAAB saiu
info: 2023-01-15T10:16:06.888Z ID: 3EjrPhAGIfbKHR9IAAAD entrou
info: 2023-01-15T10:16:31.626Z ID: 3EjrPhAGIfbKHR9IAAAD saiu
info: 2023-01-15T10:17:09.957Z ID: qOTMu7yS9l66TaH_AAAF entrou
info:     
  _       ______  ____  ______                            __ 
  | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
  | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
  | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_  
  |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
info:     Checking for updates
info:     You're up to date
info:     [5522997797041:browser] Using browser folder '/home/node/app/tokens/9999999941'
info:     [5522997797041:browser] Initializing browser...
```

**Comment by icleitoncosta** [comment]
Try `sudo apt install -y chromium-browser`

**Comment by IgorDePaula** [comment]
Inside container?

**Comment by icleitoncosta** [comment]
Sorry, I don't read. You have install with DockerFile of WppConnect or manually?

If was with DockerFile of WPPConnect, the error is other, maybe memory.

**Comment by IgorDePaula** [comment]
I cloned repo with docker and executed It. Can be memory. I Will investigate better.

**Comment by IgorDePaula** [comment]
I wrote this in docker-compose file:

```
 wppconnect-server:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 3050M
        reservations:
          cpus: '0.2'
          memory: 3020M
    build: (...)
```

But appear be more time for setup and boot the server. I'm using macos Monterey, intel i7 cpu, and 8gb ram. Have this any influency?

**Comment by IgorDePaula** [comment]
I tryied with a vps with 1gb ram 1vcpu, and works fine, but with docker, not

**Comment by renat473** [comment]
Igor, 

e pouca memória e cpu para você utilizar o wppconnect junto do docker, aconselho que aumente o recursos do servidor.

**Comment by IgorDePaula** [comment]
@renat473 voce acha 3g de memoria pouco? Quanto vc recomenda? Porque no macbook air, ele com 8gb livre (e depois reservado 3gb so pra ele) nao rodou, mas no servidor com 1gb rodou liso.
