### ISSUE TITLE
Novo recurso - Deletar pasta de sessão da instancia.

### ISSUE THREAD

**Issue by WesleyMarinho** [wppconnect-team/wppconnect-server#1060]
Seria legal se puderem adicionar a função que delete totalmente todos os arquivos relacionados a uma sessão ao a desconexão, ou criar uma nova rota, já que muitos podem querer manter isso por algum motivo.

Rota: /api/{session}/close-session

Aqui no meu caso como estavam ocorrendo travamentos ao usar o mesmo nome de sessão, sempre gero um  novo para reconectar ai vai enchendo o servidor de arquivos desnecessários :)

isso seria muito legal e ajudaria muito com certeza!

**Comment by renat473** [comment]
funcionalidade criada no commit 
https://github.com/wppconnect-team/wppconnect-server/commit/1c517c6b3ac40fa5f1c695f0eff211ab16f2b2ab
