### ISSUE TITLE
ChatWoot error

### ISSUE THREAD

**Issue by pedroherpeto** [wppconnect-team/wppconnect-server#1061]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Wppconnect-server version(s):** v1.8.2
- **Browser:** Chrome last version
- **OS:** Ubuntu 20.04
- **Node version:** node 16
- **WhatsApp version:** 2.2234.13
- **MultiDevice (BETA):** yes
- **config.json:** mesmo do original

## Steps to Reproduce

1. Realizei a integração com ChatWoot, todos rodando na mesma VPS

## Log Output

```
0|wppconne |
0|wppconne | info: 2023-01-18T23:32:28.925Z Started Session: sessao1
0|wppconne | TypeError: Cannot read properties of undefined (reading 'meta')
0|wppconne |     at chatWoot (/home/deployzdg/wppconnect-server/dist/controller/deviceController.js:767:39)
0|wppconne |     at runMicrotasks (<anonymous>)
0|wppconne |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|wppconne | TypeError: Cannot read properties of undefined (reading 'meta')
0|wppconne |     at chatWoot (/home/deployzdg/wppconnect-server/dist/controller/deviceController.js:767:39)
0|wppconne |     at runMicrotasks (<anonymous>)
0|wppconne |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|wppconne | TypeError: Cannot read properties of undefined (reading 'baseURL')
0|wppconne |     at chatWoot (/home/deployzdg/wppconnect-server/dist/controller/deviceController.js:775:54)
0|wppconne |     at runMicrotasks (<anonymous>)
0|wppconne |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

-----------------------------------------------------------------------------------------------------------------------

error:    Unhandled Rejection: TypeError: Cannot read properties of null (reading 'id')
8|wpp  |     at chatWootClient.createConversation (/www/wwwroot/wpp/src/util/chatWootClient.js:192:27)
8|wpp  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
8|wpp  |     at chatWootClient.sendMessage (/www/wwwroot/wpp/src/util/chatWootClient.js:71:24)
8|wpp  | TypeError: Cannot read properties of null (reading 'id')
8|wpp  |     at chatWootClient.createConversation (/www/wwwroot/wpp/src/util/chatWootClient.js:192:27)
8|wpp  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
8|wpp  |     at chatWootClient.sendMessage (/www/wwwroot/wpp/src/util/chatWootClient.js:71:24)

```

## Additional context / Screenshot

De dentro do chatwoot é possível enviar mensagens, mas as mensagens de fora não são escutadas pela API. Esse erro começou a acontecer com a nova versão do chatwoot.

**Comment by icleitoncosta** [comment]
Obrigado pelo feeeback, irei verificar. Por gentileza mantenha a versão anterior do ChatWoot até poder fazer o ajuste

**Comment by marcosgunha** [comment]
Testei com versões anteriores e o erro também ocorre, chatwoot 2.12.1 e wppserver 1.8.2, wppserver1.8.1 esta ok

**Comment by marcosgunha** [comment]
Olá, testei em outras versões do chatwoot a versao 1.8.2, mas também esta com mesmo erro relatado acima.

**Comment by pedroherpeto** [comment]
@icleitoncosta tudo bem? com a versao 18.1 está dando erro de meta

4|wppconne | info: 2023-01-24T21:48:12.895Z Started Session: sessao1
4|wppconne | TypeError: Cannot read property 'meta' of undefined
4|wppconne |     at chatWoot (/home/deployzdg/wppconnect-server/dist/controller/deviceController.js:767:39)

**Comment by luanscar** [comment]
estou com problema para integrar também!

![image](https://user-images.githubusercontent.com/19667323/216391911-0c5a5c39-900a-4800-bd7d-1f6c941283c9.png)

**Comment by pedroherpeto** [comment]
@icleitoncosta voces conseguiram validar os erros?

**Comment by renat473** [comment]
olá @pedroherpeto , poderia me informar o momento que este erro ocorre e qual a versão que esta utilizando do chatwoot ?

**Comment by egorky** [comment]
Posso confirmar que na versão do Chatwoot v2.15.0 a mensagem de erro TypeError: Cannot read properties of null (reading 'id') continua chegando
<img width="713" alt="image" src="https://user-images.githubusercontent.com/54412925/227729339-287a2e2b-dea3-4f5e-939a-f477192ba5fd.png">
as mensagens também são duplicadas, mas não sei se isso tem a ver com esse erro. 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/54412925/227729421-c5d63fd2-dd45-4f4a-a9d8-3773e79d33b0.png">
Wppconnect-server version(s): v1.8.5

**Comment by VILANI** [comment]
> Posso confirmar que na versão do Chatwoot v2.15.0 a mensagem de erro TypeError: Cannot read properties of null (reading 'id') continua chegando <img alt="image" width="713" src="https://user-images.githubusercontent.com/54412925/227729339-287a2e2b-dea3-4f5e-939a-f477192ba5fd.png"> as mensagens também são duplicadas, mas não sei se isso tem a ver com esse erro. <img alt="image" width="511" src="https://user-images.githubusercontent.com/54412925/227729421-c5d63fd2-dd45-4f4a-a9d8-3773e79d33b0.png"> Wppconnect-server version(s): v1.8.5

Estou investigando aqui o motivo das mensagens duplicadas, mas náo tive sucesso ainda, descobriu algo?

**Comment by marceloheck** [comment]
ola sabe que a mensagem chega no chatwoot mas não vai pro whatsapp ta instalado selfhosted
