### ISSUE TITLE
I have 16 GB ram with 8core server ...still when more than 30 User conenct server is stuck 

### ISSUE THREAD

**Issue by lalitthinker** [wppconnect-team/wppconnect-server#1064]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by renat473** [comment]
hello, could you tell me what activities you have been running?

In addition to the settings you passed, what operating system are you using?

wppconnect-server is up to date?

**Comment by lalitthinker** [comment]
Yes, after connection of multiple tokens ram will reduce to some mb data.
