### ISSUE TITLE
Getting blank response in all-chats API

### ISSUE THREAD

**Issue by nilede-bharat** [wppconnect-team/wppconnect-server#1065]
After scanning QR code & calling "all-chats" API for first time the response is blank, but after restarting server it works.

**Comment by icleitoncosta** [comment]
Hello, did you test it as soon as you connected it or did you wait a while? this can occur when you have just connected to the device, as Whatsapp is still synchronizing.

**Comment by nilede-bharat** [comment]
Actually, Once the QR code is scanned, we received an "all chats" API response with a "response" parameter which has all the chats but if we hit the same API, then we received a response without the "response" parameter.

**Comment by Saifallak** [comment]
Having same issue, randomly..
I have session giving me empty chats and others giving normal chats, on same machine

**Comment by Saifallak** [comment]
After sometime it works as normal again

**Comment by icleitoncosta** [comment]
> After scanning QR code & calling "all-chats" API for first time the response is blank, but after restarting server it works.

Call the all-chats after the event "inChat" occurs.
