### ISSUE TITLE
Não está enviando botão com link no envio uma mensagem mencionada para grupos

### ISSUE THREAD

**Issue by murilomontalvao** [wppconnect-team/wppconnect-server#1073]
## Environment

- **Wppconnect-server version(s):** [v1.8.2]
- **Browser:** [Google Chrome 109.0.5414.119]
- **OS:** [Ubuntu 16.04 LTS]
- **Node version:** [v16.19.0]
- **WhatsApp version:** [2.2234.13]
- **MultiDevice (BETA):** yes
- **config.json:** 
{
  "secretKey": "XXXXXXXXXXXX",
  "host": "http://localhost",
  "port": "21465",
  "deviceName": "WppConnect Server",
  "poweredBy": "WPPConnect-Server",
  "startAllSession": true,
  "tokenStoreType": "file",
  "maxListeners": 0,
  "customUserDataDir": "./tokens/server-",
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true,
    "onReactionMessage": true,
    "onPollResponse": true,
    "onRevokedMessage": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}

## Steps to Reproduce

1. Tentei fazer o envio através do endpoint "send-mentioned" usando os parametros (apenas retirei os números dos whatsapp mencionados) abaixo:
{
    "phone": "120363027980047881",
    "message":"Boa noite para todos",
    "mentioned":["5599999999@c.us", "5599999999@c.us"],
    "isGroup":true,
    "options": {
        "linkPreview": false,
        "useTemplateButtons": true,
        "buttons": [
            {
                "id": "1",
                "url": "https://www.r7.com/",
                "text": "Link"
            } 
        ]
    }
}
2. Retorna sucesso, porém não envia o botão com link

## Log Output
{
    "status": "success",
    "response": {
        "id": "true_12036302798099999@g.us_3EB0FE4469588D8F869D_559999999999@c.us",
        "ack": 1,
        "sendMsgResult": {
            "_flags": 269,
            "_value": "OK",
            "_onFulfilled": {},
            "_resolveLevel": 2,
            "_thenableParent": null,
            "_parent": {
                "_flags": 269,
                "_value": "OK",
                "_onFulfilled": {},
                "_resolveLevel": 1,
                "_thenableParent": null
            }
        }
    },
    "session": "session1"
}

```
If relevant, paste all of your Log Output
```
![image](https://user-images.githubusercontent.com/3306327/215269823-f5d6806f-05eb-4403-8ee6-4617bd372f24.png)

**Comment by edgardmessias** [comment]
Em vez de `mentioned`, tente usar `mentionedList`

**Comment by murilomontalvao** [comment]
Bom dia Edgard!
Testei e não deu certo! Pelos meus testes ou envia menção ou envia botão. Os dois juntos não funcionaram em situação alguma. 

Tentei pelos endpoints "send-mentioned" e "send-message", inserindo o parametro "mentionedList" fora e dentro do parametro "options". 

Se der certo para você enviar botão com menção, poderia passar um exemplo?

**Comment by renat473** [comment]
deprecated
