### ISSUE TITLE
Caixa de entrada duplicada no Chatwoot Utilizando Wppconnect-server 1.8.3

### ISSUE THREAD

**Issue by udsonassis** [wppconnect-team/wppconnect-server#1091]
## Description
Está duplicando mensagem na caixa de entrada do Chatwoot. Não acontece com todas as mensagens, mas não consegui achar um padrão

![image](https://user-images.githubusercontent.com/4209678/217102760-d6f882bd-bcab-4305-9e84-0c004fcc57b4.png)

## Environment
- **Wppconnect-server version(s): 1.8.3
- **OS: Ubuntu 20.04
- **Node version: v18.12.1

**Comment by ASchneiderBR** [comment]
Olá @udsonassis, tudo bem? Estou com o mesmo problema. Conseguiu descobrir o que pode ser? Obrigado!

**Comment by miguelurtado** [comment]
Em testes aqui esse esse merge deve resolver - https://github.com/wppconnect-team/wppconnect-server/pull/1330

**Comment by udsonassis** [comment]
@ASchneiderBR parei de usar wppconnect, fiz uma integração para codechat e desde então não teve mais problema.

**Comment by ASchneiderBR** [comment]
> Em testes aqui esse esse merge deve resolver - #1330

Boa tarde, será que isso também vai resolver os problemas de criar um novo ticket devido ao digito 9 extra fazer/não fazer parte da mensagem inicial? Quando a pessoa responde e o número não bate, ele cria um novo ticket.

Outro problema que também estava tendo era o CSAT que não era enviado para caixas de WPP utilizando este server.

Obrigado!

**Comment by udsonassis** [comment]
@ASchneiderBR isto não acontece porque trato isso na integração. Quando chega a requisição eu checo se ja tem conversa criada pra aquele numero com nono ou sem nono digito.

**Comment by renat473** [comment]
pr #1330
