### ISSUE TITLE
Atribuir etiquetas a um chat

### ISSUE THREAD

**Issue by lelliss** [wppconnect-team/wppconnect-server#1106]
Seria ótimo poder alterar as etiquetas de um contato, adicionando, removendo ou editando.

![image](https://user-images.githubusercontent.com/77357727/220237538-ce3328c4-5e54-4dba-b451-a926dfdd44c4.png)

![image](https://user-images.githubusercontent.com/77357727/220237859-0ad38a2f-000c-4be9-b6db-b52165fb4bb1.png)

**Comment by icleitoncosta** [comment]
> Seria ótimo poder alterar as etiquetas de um contato, adicionando, removendo ou editando.
> 
> ![image](https://user-images.githubusercontent.com/77357727/220237538-ce3328c4-5e54-4dba-b451-a926dfdd44c4.png)
> 
> ![image](https://user-images.githubusercontent.com/77357727/220237859-0ad38a2f-000c-4be9-b6db-b52165fb4bb1.png)

Olá, você pode usar a rota (POST: add-or-remove-label)
