### ISSUE TITLE
Apos iniciar a sessão não consigo capturar o QRcode

### ISSUE THREAD

**Issue by higormachado3** [wppconnect-team/wppconnect-server#1109]
{
    "status": "INITIALIZING",
    "message": "QRCode is not available..."
}

**Comment by edgardmessias** [comment]
Please, fill any information to help us

**Comment by higormachado3** [comment]
@edgardmessias, faço a requisição para gerar o token de sessão normalmente e ela retorna sucesso. Porém, quando tento iniciar a sessão, recebo a mensagem "QRcode: null" ou, se eu tentar chamar o QRcode diretamente, recebo o erro mostrado acima. Em geral, a API não está retornando o QRcode.

Não sei se é algum bug ou se fiz algo errado no processo.

**Comment by bru95** [comment]
Oi, alguma solução?

Tenho muito esse problema aqui ...

**Comment by icleitoncosta** [comment]
> Oi, alguma solução?
> 
> Tenho muito esse problema aqui ...

Olá, tente chamar a função apenas após a inicialização completa, que registre todos os eventos, ai sim, voce conseguirá retornar o qr-code
