### ISSUE TITLE
Swagger Documentation - Catalog Routes

### ISSUE THREAD

**Issue by lucazin** [wppconnect-team/wppconnect-server#1115]
**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
Add Swagger Documentation - RequestBody Schema to identity what parameters send and them format.

**Describe alternatives you've considered**
I did not find any schemas or doc about paylaod.

**Additional context**

routes.get('/api/:session/get-products', verifyToken, statusConnection, CatalogController.getProducts);
routes.get('/api/:session/get-product-by-id', verifyToken, statusConnection, CatalogController.getProductById);
routes.post('/api/:session/add-product', verifyToken, statusConnection, CatalogController.addProduct);
routes.post('/api/:session/edit-product', verifyToken, statusConnection, CatalogController.editProduct);
routes.post('/api/:session/del-products', verifyToken, statusConnection, CatalogController.delProducts);
routes.post('/api/:session/change-product-image', verifyToken, statusConnection, CatalogController.changeProductImage);
routes.post('/api/:session/add-product-image', verifyToken, statusConnection, CatalogController.addProductImage);
routes.post('/api/:session/remove-product-image', verifyToken, statusConnection, CatalogController.removeProductImage);
routes.get('/api/:session/get-collections', verifyToken, statusConnection, CatalogController.getCollections);
routes.post('/api/:session/create-collection', verifyToken, statusConnection, CatalogController.createCollection);
routes.post('/api/:session/edit-collection', verifyToken, statusConnection, CatalogController.editCollection);
routes.post('/api/:session/del-collection', verifyToken, statusConnection, CatalogController.deleteCollection);
routes.post('/api/:session/send-link-catalog', verifyToken, statusConnection, CatalogController.sendLinkCatalog);

**Comment by icleitoncosta** [comment]
Olá @lucazin, estou trabalhando em uma alternativa viável para o swagger ficar com uma atualização mais simples e colocar todas essas rotas, em preve faço um PR

**Comment by alexandreluchini** [comment]
Falta incluir a rota do logout-session
