### ISSUE TITLE
Escolher o token para a sessão?

### ISSUE THREAD

**Issue by higormachado3** [wppconnect-team/wppconnect-server#1123]
Existe alguma forma deu escolher um token para criar uma  sessão?

Exemplo

{
	"status": "success",
	"session": "nova",
	"token": "Meu_token_escolhido",
	"full": "nova:Meu_token_escolhido"
}

**Comment by renat473** [comment]
Na rota /generate-token você pode gerar novos tokens para cada session que vai ser utilizado no endpoint /start-session onde não a necessidade de enviar estes dados na payload do json, pois ele já e enviado no header do endpoint.

**Comment by icleitoncosta** [comment]
> Existe alguma forma deu escolher um token para criar uma  sessão?
> 
> 
> 
> Exemplo
> 
> 
> 
> {
> 
> 	"status": "success",
> 
> 	"session": "nova",
> 
> 	"token": "Meu_token_escolhido",
> 
> 	"full": "nova:Meu_token_escolhido"
> 
> }

Opa Higor, da forma como o server é feito não é possível, geramos ele através do jwt e validamos na requisição de forma rápida. 

Para colocar uma opção onde pode ser dito o token, iria acabar causando lentidão nas requisições, fora aumentar a complexidade do código
