### ISSUE TITLE
Etiquetas chegando pelo Webhook

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1127]
Alguma possibilidade das etiquetagem de algum chat no app do smartphone chegar no Webhook da sessão?

**Comment by Saifallak** [comment]
@pedromagnox can you explain this feature more?

**Comment by icleitoncosta** [comment]
> Alguma possibilidade das etiquetagem de algum chat no app do smartphone chegar no Webhook da sessão?

Olá Pedro, sim, é possível, ele retorna o ID do label dentro da array. 
https://wppconnect.io/swagger/wppconnect-server#tag/Chat/operation/ChatById

No caso, para consultar quais são use a rota /get-all-labels

Lembrando que o /chat-by-id, estava com erro e fixei através de um commit agora.

**Comment by icleitoncosta** [comment]
> @pedromagnox can you explain this feature more?

These are the labels that you can put in the chat on WhatsApp Business

**Comment by Saifallak** [comment]
> > @pedromagnoxcan you explain this feature more?
> 
> These are the labels that you can put in the chat on WhatsApp Business

Good translated his request wrong.
thanks for explaining.

**Comment by pedromagnox** [comment]
Acho que eu não expliquei o problema de forma clara o suficiente @icleitoncosta.

Abri outro issue mais elaborado:
https://github.com/wppconnect-team/wppconnect-server/issues/1172
