### ISSUE TITLE
timeouts in `all-chats`

### ISSUE THREAD

**Issue by Saifallak** [wppconnect-team/wppconnect-server#1131]
## Description

Getting a lot of timeouts in `all-chats` this is maybe because the chats list is too large,
and looking for a way to paginate them. (like messages endpoint)
also if possible a way to get the last message with each chat

## Related

- Might Be Related To #1048 
- PRs in WA-JS Fixing This:
- - https://github.com/wppconnect-team/wa-js/pull/1015
- - https://github.com/wppconnect-team/wa-js/pull/1037

## Environment

- **Wppconnect-server version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes/no
- **config.json:** [Your src/config.json file content]

## Steps to Reproduce

1. Call `all-chats`
2. Sometimes it gets timed out.

## Log Output

```
cURL error 28: Operation timed out after 30004 milliseconds with 0 out of -1 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://XXXXX:21465/api/WPP-SESSION/all-chats
```

**Comment by icleitoncosta** [comment]
I have already managed to work on a functional solution that will return chats paginated by pages and allow changing the quantity, etc. Tomorrow, I will try to work on the last message to release it correctly, but the paginated request turned out to be very fast.

**Comment by Saifallak** [comment]
@icleitoncosta wow, you're amazing 🚀🚀

**Comment by Saifallak** [comment]
@edgardmessias still not completely fixed

**Comment by Saifallak** [comment]
@icleitoncosta @icleitoncosta 
Can you re open this?
Also, if i can get any guide on how to do it in @wppconnect-team/wppconnect would be appreciated, because i failed to understand the repo after i (with help of you both ❤️) implemented it on wa-js https://github.com/wppconnect-team/wa-js/pull/1037

**Comment by icleitoncosta** [comment]
Hi, you can use the route list-chats.
Has examples to do this on Swagger.  

This was added by commit 456070242ff78609d1187e80c7b2c6e173faebfe
