### ISSUE TITLE
wppconnect-server  | Error: Cannot find module '../swagger.json'

### ISSUE THREAD

**Issue by 1579091** [wppconnect-team/wppconnect-server#1171]
Após alguns commits que subiram hoje, passei a obter esse erro na hora de buildar e subir o server com o chatwoot:

Obs: Já tinha subido outras vezes, e estava ok, seguindo essas instruções:
https://www.youtube.com/watch?v=00616mTid-M&ab_channel=WPPConnect

Log: 
chatwoot-rails     | => Booting Puma
chatwoot-rails     | => Rails 6.1.7.3 application starting in production
chatwoot-rails     | => Run `bin/rails server --help` for more startup options
wppconnect-server  | node:internal/modules/cjs/loader:1078
wppconnect-server  |   throw err;
wppconnect-server  |   ^
wppconnect-server  |
wppconnect-server  | Error: Cannot find module '../swagger.json'
wppconnect-server  | Require stack:
wppconnect-server  | - /home/node/app/dist/routes/index.js
wppconnect-server  | - /home/node/app/dist/index.js
wppconnect-server  | - /home/node/app/dist/server.js
wppconnect-server  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
wppconnect-server  |     at Module._load (node:internal/modules/cjs/loader:920:27)
wppconnect-server  |     at Module.require (node:internal/modules/cjs/loader:1141:19)
wppconnect-server  |     at require (node:internal/modules/cjs/helpers:110:18)
wppconnect-server  |     at Object.<anonymous> (/home/node/app/dist/routes/index.js:33:39)
wppconnect-server  |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
wppconnect-server  |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
wppconnect-server  |     at Module.load (node:internal/modules/cjs/loader:1117:32)
wppconnect-server  |     at Module._load (node:internal/modules/cjs/loader:958:12)
wppconnect-server  |     at Module.require (node:internal/modules/cjs/loader:1141:19)
wppconnect-server  |     at require (node:internal/modules/cjs/helpers:110:18)
wppconnect-server  |     at Object.<anonymous> (/home/node/app/dist/index.js:27:38)
wppconnect-server  |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
wppconnect-server  |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
wppconnect-server  |     at Module.load (node:internal/modules/cjs/loader:1117:32)
wppconnect-server  |     at Module._load (node:internal/modules/cjs/loader:958:12) {
wppconnect-server  |   code: 'MODULE_NOT_FOUND',
wppconnect-server  |   requireStack: [
wppconnect-server  |     '/home/node/app/dist/routes/index.js',
wppconnect-server  |     '/home/node/app/dist/index.js',
wppconnect-server  |     '/home/node/app/dist/server.js'
wppconnect-server  |   ]
wppconnect-server  | }
wppconnect-server  |
wppconnect-server  | Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by 1579091** [comment]
@icleitoncosta can u check it?

**Comment by icleitoncosta** [comment]
> @icleitoncosta can u check it?

I will check today
