### ISSUE TITLE
Navegadores navegando via VPN

### ISSUE THREAD

**Issue by MeuGestor** [wppconnect-team/wppconnect-server#1176]
No servidor uso VPN para os navegadores, quando a VPN está ativa o WppConnect não abre o navegador, tenho que ficar desativando a VPN sempre que vou adicionar novo telefone.
![WppConnect vs VPN](https://user-images.githubusercontent.com/86304368/229796301-b891a981-5f5f-4a01-8047-515a2694f058.png)

**Comment by renat473** [comment]
Olá @MeuGestor ,

Este problema esta relacionado a rota e não um erro da aplicação server. Caso tenha conhecimento na parte de rotas sugiro que seja verificado.

**Comment by edgardmessias** [comment]
@MeuGestor , parece que a VPN também está capturando as requisições para o localhost (127.0.0.1), pois é usado o localhost para a lib controlar o browser, mas se a VPN estiver interceptando isso também, não há nada que possamos fazer, pois se trata um problema da VPN e não da lib

**Comment by MeuGestor** [comment]
@edgardmessias Então, estou achando estranho, porque Enviar Msg, verificar Status, Fechar Sessão, tudo funciona normal.
@renat473 Entendo um pouco, se puder me dar uma luz em qual(is) arquivos verifcar, agradeço!

**Comment by renat473** [comment]
Olá @MeuGestor ,

Esta parte de rotas e nível de sistema operacional, tente verificar como as rotas se encontra, e sobre o comentário de alguns momento esta funcionando e que alguns momentos as configurações de rede acaba encontrando a rota correta.
