### ISSUE TITLE
Server desconectando sessões

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1180]
O servidor fica desconectando sessões, mas não no WhatsApp do usuário

Quando tento chamar um send-message ele avisa que a sessão está desconectada

Mas quando abro o WhatsApp no celular, ela ainda está conectada

Daí quando reinicio a VPS ela volta como conectada

Alguém tem alguma pista do que pode estar causando isso?

**Comment by icleitoncosta** [comment]
Olá Pedro, a principio pode ser diversos problemas, no geral com a VPS.
Passos: atualize o wppconnect para a última versão.
npm upgrade @wppconnect-team/wppconnect@latest

Mantenha o log do config.ts em silly, 

Quando isso acontecer, traga os logs para avaliarmos melhor se eles mostram algum possível problema que possamos identificar, e sugiro também avaliar, ou de alguma forma colocar um analisador de memória para tentar executar exatamente qual função está causando esse erro. 

No geral, é falta de recursos no VPS, mas possívelmente tem algo que está sendo executado em específico que está causando esse problema.
