### ISSUE TITLE
Websocket nao respondendo

### ISSUE THREAD

**Issue by IgorDePaula** [wppconnect-team/wppconnect-server#1183]
## Description
O websocket nao esta respondendo

## Environment

- **Wppconnect-server version(s):** 2.0.0
- **OS:** ubuntu latest
- **Node version:** 16
- **WhatsApp version:** 2.2307.x 
- **config.json:** export default {
    secretKey: 'My53cr3tKY',
    host: 'http://localhost',
    port: '21465',
    deviceName: 'WppConnect',
    poweredBy: 'WPPConnect-Server',
    startAllSession: true,
    tokenStoreType: 'file',
    maxListeners: 15,
    customUserDataDir: './userDataDir/',
    webhook: {
        url: null,
        autoDownload: true,
        uploadS3: false,
        readMessage: true,
        allUnreadOnStart: false,
        listenAcks: false,
        onPresenceChanged: false,
        onParticipantsChanged: false,
        onReactionMessage: false,
        onPollResponse: false,
        onRevokedMessage: true,
    },
    archive: {
        enable: false,
        waitTime: 10,
        daysToArchive: 45,
    },
    log: {
        level: 'silly', // Before open a issue, change level to silly and retry a action
        logger: ['console', 'file'],
    },
    createOptions: {
        browserArgs: [
            '--disable-web-security',
            '--no-sandbox',
            '--disable-web-security',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0',
            '--disable-background-networking',
            '--disable-default-apps',
            '--disable-extensions',
            '--disable-sync',
            '--disable-translate',
            '--hide-scrollbars',
            '--metrics-recording-only',
            '--mute-audio',
            '--no-first-run',
            '--safebrowsing-disable-auto-update',
            '--ignore-certificate-errors',
            '--ignore-ssl-errors',
            '--ignore-certificate-errors-spki-list',
        ],
    },
    mapper: {
        enable: false,
        prefix: 'tagone-',
    },
    db: {
        mongodbDatabase: 'tokens',
        mongodbCollection: '',
        mongodbUser: '',
        mongodbPassword: '',
        mongodbHost: '',
        mongoIsRemote: true,
        mongoURLRemote: '',
        mongodbPort: 27017,
        redisHost: 'localhost',
        redisPort: 6379,
        redisPassword: '',
        redisDb: 0,
        redisPrefix: 'docker',
    },
};

## Steps to Reproduce

tentar conectar no localhost:21465 com o socket.io-client no frontend

## Log Output

CORS Missing origin allow

## Your Code

```
useEffect(() => {
        const socket = io('http://ws.localhost:21465/')
        socket.on('qrCode', e => {
            setQRCode(e.data)
        })

        useEvent('chate', 'StatusFindEvent', e => {
            setStatus(e.status)
        })
    }, [])
```

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/2833993/230404073-5c430623-356e-47e9-9c38-3e729a72115c.png)

**Comment by IgorDePaula** [comment]
https://user-images.githubusercontent.com/2833993/231901151-26eafcff-6d0f-4bcb-b548-5854e73e179b.mp4

**Comment by icleitoncosta** [comment]
Opa Igor, corrigi no commit https://github.com/wppconnect-team/wppconnect-server/commit/8277c1417079b22cc14538740e0ae2b3402ba7ee
