### ISSUE TITLE
Session showing Status="closed"

### ISSUE THREAD

**Issue by SajjadAhmad-inspire-Tech** [wppconnect-team/wppconnect-server#1198]
I have scanned the device successfully and messaging outgoing and incoming are working perfectly but there is an issue that I'm facing like
If I have not sent the message for few minutes then after coming back then sending/outgoing is not working.

Its says that session is closed.
looks the screenshot
![image](https://user-images.githubusercontent.com/104127188/232395079-858bca9e-6fe3-426a-adcd-f84881edcf7b.png)

Observation:
After happening this issue i have restarted the session and after few seconds its looks like working again without scanning the QR code.

Can anyone suggest me 
may i need to implement a heartbeat for status make to OPEN/Connected?

**Comment by swapneal-dev** [comment]
Same issue we are facing. If you get any workaround please let us know.

**Comment by renat473** [comment]
test performed with the latest version of wppconnect-server where the problem was not found.
