### ISSUE TITLE
24052 ms: Scavenge 488.6 (498.5) -> 488.1 (501.0) MB, 13.6 / 0.0 ms  (average mu = 0.249, current mu = 0.239) allocation failure

### ISSUE THREAD

**Issue by denidarmayana** [wppconnect-team/wppconnect-server#1201]
<--- Last few GCs --->

[79943:0x4fa7c20]    24052 ms: Scavenge 488.6 (498.5) -> 488.1 (501.0) MB, 13.6 / 0.0 ms  (average mu = 0.249, current mu = 0.239) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb090e0 node::Abort() [node]
 2: 0xa1b70e  [node]
 3: 0xce19d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce1d77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe993e5  [node]
 6: 0xe99ec6  [node]
 7: 0xea83ee  [node]
 8: 0xea8e30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeabd25 v8::internal::Heap::HandleGCRequest() [node]
10: 0xe393c7 v8::internal::StackGuard::HandleInterrupts() [node]
11: 0x11e5a64 v8::internal::Runtime_StackGuardWithGap(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15d9e19  [node]
Aborted (core dumped)

**Comment by icleitoncosta** [comment]
This is mistake out memory of VPS, please change de log config to silly and when mistake occurs get the log and put here for us analyzing
