### ISSUE TITLE
Sessões desconectadas

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1207]
Toda vez que a VPS reinicia na versão 1.8.5 todas as sessões aparecem como desconectadas
Não deveria ter uma chamada POST que reabrisse a aba do Chrome ou algo assim?

Isso já foi resolvido nas versões mais recentes?

Como reativar uma sessão que está sendo exibida como inativa, mas que continua ativa no celular?

**Comment by Saifallak** [comment]
just use `/start-session`

or enable it to start all sessions from `config.json/ts`

**Comment by edgardmessias** [comment]
Hello @Saifallak , big thanks to you about helping the comunity.

Could you create some common questions for our faq? The site uses Docusaurus for building

Edit: https://github.com/wppconnect-team/wppconnect-team.github.io/blob/main/docs/projects/wppserver/faq.md
Site: https://wppconnect.io/docs/projects/wppserver/faq

**Comment by Saifallak** [comment]
@edgardmessias thanks to you for the great library,

no promises but will try when I have some spare time, but to be honest I'm a little busy in the upcoming weeks.
