### ISSUE TITLE
Webhook not work

### ISSUE THREAD

**Issue by diogofm7** [wppconnect-team/wppconnect-server#1208]
## Description

webhook not triggered when receiving message

## Environment

- **Wppconnect-server version(s):** WPPConnect-Server version: 2.0.1
- **Browser:** Using docker
- **OS:** docker-ce to debian 11
- **Node version:**  Using docker
- **WhatsApp version:** 2.23.7.80
- **MultiDevice (BETA):** yes
- **config.json:** 

{
  "secretKey": "THISISMYSECURETOKEN",
  "host": "http://localhost",
  "port": "21465",
  "customUserDataDir": "./userDataDir/",
  "startAllSession": true,
  "maxListeners": 15,
  "webhook": {
    "url": "https://mydomain.com/wpp-connect",
    "autoDownload": true,
    "readMessage": true,
    "allUnreadOnStart": true
  },
  "archive": {
    "enable": true,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": [ "console", "file" ]
  },
  "createOptions": {
    "browserArgs": ["--no-sandbox"]
  }
}

## Steps to Reproduce

receive a message on ehatsapp connected to wppconnect

## Additional context / Screenshot

I made a git clone in the repositorion, created the config.json file in the root, and ran a "docker compose up -d".

The project is functional, I can send messages from it, but when I receive a message it doesn't trigger the webhook, and nothing appears in the logs.

**Comment by renat473** [comment]
Olá @diogofm7 ,

O arquivo config.json não é mais utilizado, nesta nova versão é utilizado o config.ts e onde tem a linha de webhook deste arquivo o seu webhook irá receber todas as mensagem de todas as session. O ideal e você inicar um start-session com endereço de seu webhook.

**Comment by diogofm7** [comment]
> Olá @diogofm7 ,
> 
> O arquivo config.json não é mais utilizado, nesta nova versão é utilizado o config.ts e onde tem a linha de webhook deste arquivo o seu webhook irá receber todas as mensagem de todas as session. O ideal e você inicar um start-session com endereço de seu webhook.

Existe alguma doc dessa nova versão?? Como eu faria o start-session com webhook?? Assim eu conseguiria direcionar cada session para um webhook diferente???

**Comment by renat473** [comment]
Você pode ter acesso a documentação atráves deste link, os endpoint do server , https://wppconnect.io/swagger/wppconnect-server e lá você encontra o funcionamento e comportamento do start-session.

Qualquer dúvida que tenha pode entrar em nosso grupos de whatsapp e discord, para melhor orientação.
