### ISSUE TITLE
Erro ao enviar msg para grupos

### ISSUE THREAD

**Issue by ObianSistemas** [wppconnect-team/wppconnect-server#121]
Estou enviando mensagem para grupo usando esse json:
{
    "isGroup" : true,
    "message" : "Mensagem ",
    "phone" : "id do grupo"
}
mas a resposta é sempre essa:
{
    "message" : "O número id do grupo não existe.",
    "response" : null,
    "session" : "Sessao",
    "status" : "Connected"
}
Esse erro apareceu depois de uma atualização.

**Comment by hbdbim** [comment]
resolvido no ultimo commit
77b08ae46d15d71b92a777abeee9932f4c7f0889
