### ISSUE TITLE
Not receiving messages chat-by-id

### ISSUE THREAD

**Issue by flexsoluciones** [wppconnect-team/wppconnect-server#1219]
send :
{{baseUrl}}/:session/chat-by-id/593999800763?isGroup=false

response :
{
    "id": {
        "server": "c.us",
        "user": "593999800763",
        "_serialized": "593999800763@c.us"
    },
    "lastReceivedKey": {
        "fromMe": false,
        "remote": {
            "server": "c.us",
            "user": "593999800763",
            "_serialized": "593999800763@c.us"
        },
        "id": "88CD2DF0BDDAE45B15F62ABE63B97157",
        "_serialized": "false_593999800763@c.us_88CD2DF0BDDAE45B15F62ABE63B97157"
    },
    "t": 1683340882,
    "unreadCount": 0,
    "isReadOnly": false,
    "muteExpiration": 0,
    "isAutoMuted": false,
    "notSpam": true,
    "ephemeralDuration": 0,
    "disappearingModeInitiator": "chat",
    "unreadMentionsOfMe": [],
    "unreadMentionCount": 0,
    "hasUnreadMention": false,
    "archiveAtMentionViewedInDrawer": false,
    "hasChatBeenOpened": false,
    "tcToken": {},
    "tcTokenTimestamp": 1683159915,
    "tcTokenSenderTimestamp": 1683160011,
    "endOfHistoryTransferType": 0,
    "pendingInitialLoading": false,
    "msgs": null,
    "kind": "chat",
    "isBroadcast": false,
    "isGroup": false,
    "isUser": true,
    "contact": {
        "id": {
            "server": "c.us",
            "user": "593999800763",
            "_serialized": "593999800763@c.us"
        },
        "name": "Walter Valdez Whtaspp",
        "shortName": "Walter",
        "pushname": "Walter",
        "type": "in",
        "isBusiness": false,
        "isEnterprise": false,
        "isSmb": false,
        "isContactSyncCompleted": 1,
        "formattedName": "Walter Valdez Whtaspp",
        "isMe": false,
        "isMyContact": true,
        "isPSA": false,
        "isUser": true,
        "isWAContact": true,
        "profilePicThumbObj": {
            "eurl": "https://pps.whatsapp.net/v/t61.24694-24/168605894_5059860450796869_7480944813898133723_n.jpg?ccb=11-4&oh=01_AdSo4e5w1Tm7bPe7-YZ-dnG9qEQem9KRbDQGQqcvBhkONA&oe=64626DEF",
            "id": {
                "server": "c.us",
                "user": "593999800763",
                "_serialized": "593999800763@c.us"
            },
            "img": "https://pps.whatsapp.net/v/t61.24694-24/168605894_5059860450796869_7480944813898133723_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdTHy1kiHY8z-GIzFsdzdG-FG4NtlbidrBRjGcCNT2u8zw&oe=64626DEF",
            "imgFull": "https://pps.whatsapp.net/v/t61.24694-24/168605894_5059860450796869_7480944813898133723_n.jpg?ccb=11-4&oh=01_AdSo4e5w1Tm7bPe7-YZ-dnG9qEQem9KRbDQGQqcvBhkONA&oe=64626DEF",
            "tag": "1652205930"
        },
        "msgs": null
    },
    "groupMetadata": null,
    "presence": {
        "id": {
            "server": "c.us",
            "user": "593999800763",
            "_serialized": "593999800763@c.us"
        },
        "chatstates": []
    },
    "session": "flexdemo"
}

msgs null

**Comment by icleitoncosta** [comment]
This route no longer provides messages. We've made this change to enhance performance. Please use the 'get-messages' route instead.
