### ISSUE TITLE
Route for getPlataformFromMessage

### ISSUE THREAD

**Issue by marcelomedina22** [wppconnect-team/wppconnect-server#1222]
I'd like to have a route request this feature from wppconnect

**Comment by Saifallak** [comment]
What does that mean?
What you expect to get?

**Comment by marcelomedina22** [comment]
I'd like to use a route /api/session/getPlataform or any other route sending the message id on body, and so get the result as described ON wppconnect-server and get the plataform from sender. I appreciate your reply on this.
