### ISSUE TITLE
swagger.json is malformed

### ISSUE THREAD

**Issue by fberasategui** [wppconnect-team/wppconnect-server#1242]
## Description

Trying to generate client code using both NSwag or swaggerhub.io yields invalid code.

The endpoint `GetMediaByMessage` has a wrong return value. An object of type `GetMediaByMessage` which doesn't exist in the schema definition.

NSwag crashes when generating client code due to this.

The client code generated by swaggerhub.io does not compile, because it's missing a type.

## Environment

- **Wppconnect-server version(s):** latest master
- **Browser:** N/A
- **OS:** N/A
- **Node version:** N/A
- **WhatsApp version:** N/A
- **MultiDevice (BETA):** no
- **config.json:** N/A

## Steps to Reproduce

1. Get `swagger.json` from this repository
2. Use NSwagStudio or swaggerhub.io to generate C# client code
3. Observe error

## Log Output

N/A

## Your Code

N/A

## Additional context / Screenshot

N/A

**Comment by icleitoncosta** [comment]
Please, test the latest commit
