### ISSUE TITLE
Endpoints Comunidade

### ISSUE THREAD

**Issue by jonatanfroes** [wppconnect-team/wppconnect-server#1255]
**Is your feature request related to a problem? Please describe.**
Olá, pessoal. Os endpoints para gestão de comunidade ainda não foram implementados. Não consigo criar, ler ou enviar mensagens.

**Describe the solution you'd like**
Implementação dos endpoints de comunidade

**Additional context**
Acredito que seja similar aos grupos, mas nos meus testes não funcionou

**Comment by icleitoncosta** [comment]
Adicionado através do commit https://github.com/wppconnect-team/wppconnect-server/commit/681fb79171710241838467d25df3f4913c1ad4bd
