### ISSUE TITLE
Remover uma sessão

### ISSUE THREAD

**Issue by higormachado3** [wppconnect-team/wppconnect-server#1256]
Precisava de uma rota que removesse por completo uma sessão tanto o ' /close-session '  e o ' /logout-session ' que são as rotas atuais para finalizar a sessão acabam sendo ruim de utilizar na produção por acabar sendo lento ou ate mesmo gerar um bug na execução do código!

A melhor forma que encontrei quando e necessário fazer a troca do QRcode , e iniciar  uma nova sessão e esquece a antiga, ficou muito rápido e pratico, porem a sessão antiga ainda continua no sistema mesmo passando os parâmetros atuais para cancelar ela e pior fica consumindo recurso!

Seria muito bom ter uma rota que removesse uma sessão por completo, cujo assim ela não ficaria consumindo recurso no sistema já que foi deletada e todos seus dados apagados,  fazendo assim que a pratica que eu mencionei acima se torne muito viável !

**Comment by gustavodias24** [comment]
3 anos depois e ainda não existe uma rota para deletar uma session?
estou aqui procurando isso também em 2026... será que um dia vai existir esse rota?
