### ISSUE TITLE
Please migrate your code to use AWS SDK for JavaScript (v3)

### ISSUE THREAD

**Issue by denidarmayana** [wppconnect-team/wppconnect-server#1264]
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by denidarmayana** [comment]
is this problem not resolved yet?

**Comment by icleitoncosta** [comment]
> is this problem not resolved yet?

Hello, it hasn't been resolved yet. It's a simple message from AWS, just a migration to v3 that needs to be done. We will make the adjustment soon, but the functions are still running normally without any errors.

**Comment by renat473** [comment]
fix #45fddbd
