### ISSUE TITLE
Webhook Function

### ISSUE THREAD

**Issue by tradename** [wppconnect-team/wppconnect-server#1265]
Seems the **Webhook Option** has been removed on the start-session function

**Comment by icleitoncosta** [comment]
> Seems the **Webhook Option** has been removed on the start-session function

Hello, I recreate all the swagger docs, maybe I forgot the params webhook, I will fix 

Thx

**Comment by mitnick2012** [comment]
can we add a web hook on send message api to get response if the message is being sent or not ?

**Comment by Saifallak** [comment]
> can we add a web hook on send message api to get response if the message is being sent or not ?

You can do it on your own
Send message, and check response
