### ISSUE TITLE
Endpoints de Logout e Close com problemas

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1274]
Acabei de atualizar para a versão 2.2.0

Quando chamo um logout-session aparece o seguinte erro abaixo

![logout](https://github.com/wppconnect-team/wppconnect-server/assets/127373630/677f9ee8-15d6-463d-83e0-1e3a58d16fb0)
Mesmo aparecendo o erro ele chega a deslogar, porém no show-all-sessions a sessão continua aparecendo

imagino que ela continua consumindo memória ram

Na sequência tento um close-session e ele exibe o erro abaixo

![close](https://github.com/wppconnect-team/wppconnect-server/assets/127373630/80cfd2da-2be1-4c6a-9e49-807534fa1df3)
Por conta do erro a sessão não é deletada

**Comment by pedromagnox** [comment]
Bom dia @icleitoncosta,

A mensagem de erro do logout-session sumiu. Mas o comportamento continua o mesmo. Ele Faz o logout mas não deleta a sessão

Já o close-session não mudou nada. Continua a mesma mensagem de erro e ele não deleta a sessão

**Comment by icleitoncosta** [comment]
> Bom dia @icleitoncosta,
> 
> 
> 
> A mensagem de erro do logout-session sumiu. Mas o comportamento continua o mesmo. Ele Faz o logout mas não deleta a sessão
> 
> 
> 
> Já o close-session não mudou nada. Continua a mesma mensagem de erro e ele não deleta a sessão
> 
> 
> 
> Resumindo: Nenhum deles está deletando a sessão.
> 
> Pelo menos é o que eu vejo quando chamo um show-all-sessions

Hmm... 
você está executando ele dentro de um docker, localmente, K8S? Como seria? Tenho que tentar reproduzir o mesmo cenário.

**Comment by pedromagnox** [comment]
Localmente em uma VPS da Contabo. Só estou usando o NPM ao invés do Yarn. Quer o acesso da minha? Só estou usando para testes

**Comment by pedromagnox** [comment]
Me manda o link do grupo de WhatsApp

**Comment by icleitoncosta** [comment]
https://chat.whatsapp.com/LJaQu6ZyNvnBPNAVRbX00K

**Comment by renat473** [comment]
Olá,

realizado o teste com a útlima versão do server onde o problema se encontra resolvido.

O print abaixo demostra o resultado obtido com sucesso.

![image](https://github.com/wppconnect-team/wppconnect-server/assets/1757167/410aa9ce-672a-48ee-92ed-fbb07220067d)
