### ISSUE TITLE
Websocket for incoming messages

### ISSUE THREAD

**Issue by peteh** [wppconnect-team/wppconnect-server#1276]
**Is your feature request related to a problem? Please describe.**
Rather than using a webhook, I'd like to just use a websocket, that continuously can streams incoming messages. 

Currently it's only possible to regularly call get on /api/{session}/get-messages

**Describe the solution you'd like**
The solution would be to receive all messages on a websocket that streams all incoming messages. 

**Describe alternatives you've considered**
Constantly calling get is not very reasonable for fast reaction times. 

The webhook is a nice solution but it adds a dependency to the server component to know where to send it to. Thus providing the messages via a websocket would make the components more independent.

**Comment by icleitoncosta** [comment]
Hello, we already have the WebSocket set up. We are using the socket.io library. You can check our frontend, which already has it configured, to see how you can do it. But in general, you just need to point it to the server's IP.

**Comment by peteh** [comment]
Mhm I'm still struggling with this. 

```python
api_url = "ws://localhost:21465/"
web_sock = wsclient.connect(api_url, max_size=self.WEBSOCKET_MAXSIZE)
```

Will fail to connect

**Comment by icleitoncosta** [comment]
> Mhm I'm still struggling with this.
> 
> ```python
> api_url = "ws://localhost:21465/"
> web_sock = wsclient.connect(api_url, max_size=self.WEBSOCKET_MAXSIZE)
> ```
> 
> Will fail to connect

Try this:

```
import { io } from "socket.io-client";

export const socket = io("http://localhost:21465/");

  socket.on("received-message", (message) => {
      console.log(message);
  });
```

**Comment by peteh** [comment]
Maybe I should have mentioned that I'm using python to talk to wppconnect-server. 

So this won't work for me.

**Comment by icleitoncosta** [comment]
Yes, exactly, SocketIO has libraries for various programming languages.

You can use it confidently as it will work, you just need to figure out the code for it since I know very little about Python and won't be able to assist you with that. However, the idea of SocketIO is to be straightforward, so I assume it's also simple in Python.
