### ISSUE TITLE
onReactionMessage do config.ts disparando rajadas em loop

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1278]
Quando o onReactionMessage fica setado como true no src/config.ts a api fica disparando rajadas com todas as reactions da sessão para o Webhook a cada 40 segundos aproximadamente.

Coloquei 1 sessão no webhook.site e ele estourou a cota em 2 minutos

![limite](https://github.com/wppconnect-team/wppconnect-server/assets/127373630/7a28f460-e3ae-4d80-89da-b8d3c600cf1e)

![rajadas_Prancheta 1](https://github.com/wppconnect-team/wppconnect-server/assets/127373630/a09847e7-045d-4c94-8ad0-3049be231123)

![Captura de tela 2023-06-04 034130](https://github.com/wppconnect-team/wppconnect-server/assets/127373630/d9d99380-af1f-4166-841f-5c4a13c6010d)

**Comment by icleitoncosta** [comment]
Bom dia @pedromagnox, no caso não entendi tão bem... 
Essas mensagens são repetitivas?
Isso acontece na inicialização, que ele repete todos as reactions?
São realmente reações que você esta recebendo nesse momento ou algum bug que fica em loop com as mesmas reações?

**Comment by pedromagnox** [comment]
Exatamente @icleitoncosta
Na inicialização ele manda todos os reactions (o que já nem era pra acontecer)
Daí a cada 40 segundos ele mandar todos os reactions novamente
E fica fazendo isso a cada 40 segundos mais ou menos...

bug que fica em loop com as mesmas reações

**Comment by icleitoncosta** [comment]
Perfeito, irei fazer um teste no reaction, então, se for um bug, corrigindo na lib, ja corrige aqui.

**Comment by pedromagnox** [comment]
onPresenceChanged tb @icleitoncosta
Quando está setado como true no config.ts ele está disparando vários para o Webhook
