### ISSUE TITLE
Sessões se desconectando na 2.2.1

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1283]
Estou usando a versão 2.2.1 e ontem às 18h e pouco todas sessões ficaram como Disconnected na API, embora continuassem conectadas nos app dos celulares

Esse é o resultado quando chamo um send-message
![Captura de tela 2023-06-04 150543](https://github.com/wppconnect-team/wppconnect-server/assets/127373630/c66e61df-df42-4334-b380-7983735bbc1a)

Esse problema ocorria na versão 2.0.0

Estou deixando minha API na 2.0.1 que foi a mais estável até agora em relação a isso

**Comment by icleitoncosta** [comment]
> Estou usando a versão 2.2.1 e ontem às 18h e pouco todas sessões ficaram como Disconnected na API, embora continuassem conectadas nos app dos celulares
> 
> Esse é o resultado quando chamo um send-message ![Captura de tela 2023-06-04 150543](https://user-images.githubusercontent.com/127373630/243199365-c66e61df-df42-4334-b380-7983735bbc1a.png)
> 
> Esse problema ocorria na versão 2.0.0
> 
> Estou deixando minha API na 2.0.1 que foi a mais estável até agora em relação a isso

Por favor, envia o log apresentado no momento de fechamento das sessões pra tentar ver o que esta acontecendo.

**Comment by fabioselau077** [comment]
> > Estou usando a versão 2.2.1 e ontem às 18h e pouco todas sessões ficaram como Disconnected na API, embora continuassem conectadas nos app dos celulares
> > Esse é o resultado quando chamo um send-message ![Captura de tela 2023-06-04 150543](https://user-images.githubusercontent.com/127373630/243199365-c66e61df-df42-4334-b380-7983735bbc1a.png)
> > Esse problema ocorria na versão 2.0.0
> > Estou deixando minha API na 2.0.1 que foi a mais estável até agora em relação a isso
> 
> Por favor, envia o log apresentado no momento de fechamento das sessões pra tentar ver o que esta acontecendo.

aqui tá acontecendo isso também... O erro que peguei foi esse do print 
![image](https://github.com/wppconnect-team/wppconnect-server/assets/57275833/75224a02-1bed-4be1-b937-ed11ba26a81a)
