### ISSUE TITLE
O que é o maxListeners?

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1284]
Em relação ao maxListeners dentro do src/config.ts que vem com um default de 15

1 - Esse é o número máximo de que? sessões ativas?
2 - Colocar 0 representa ilimitado? Se sim, quais problemas isso pode gerar?
3 - Qual a relação desse número com processamento, memória ram, ssd?

Mais uma dúvida

3 - O que acontece quando a memória ram da VPS enche devido ao número de sessões ativas?
Algumas sessões são desativadas? A API consegue usar o SSD de alguma forma para alocar as menos ativas?

**Comment by Saifallak** [comment]
For last point, OS automatically sends alert to all apps that memory is full, then chrome closes some sessions.

**Comment by icleitoncosta** [comment]
1. O maxListeners é referente ao EventEmitter do Node, simplesmente é para setar o maximo de ouvintes. Especificamente no server ele fica escutando os eventos da LIB, e envia para o chatwoot, o max ali é caso você queira mudar e anexar mais ouvintes, mas dificilmente será necessário alterar isso.

2. Não é recomendado usar zero, mas simplesmente você pode registrar mais ouvintes nos eventos.

3. Para o que usamos não irá impactar praticamente nada em memória ram. 
O que impacta o uso de RAM é o browser que fica executando em segundo plano. 

3(2). Acontece exatamente o que o @Saifallak informou, porém, o ideal é você aumentar os recursos do VPS.

**Comment by pedromagnox** [comment]
Entendi. É que eu contratei um VPS de 60gb de ram e pretendo colocar dezenas de sessões nela até usar uns 50gb dessa memória. E imagino que o número de eventos simultâneos vai ser bem grande tb.

Mas pelo que eu entendi o maxListeners é mais um alerta do que um limitador de fato

Também acreditava que o sistema não encerraria sessões quando a memória ram enchesse. Pensava que ele usaria o SSD NVMe para ir guardando, ainda mais porque é uma memória bem rápida de ser acessada também. Então vou monitorar o uso de memória ram, para aumentar os recursos do VPS

**Comment by icleitoncosta** [comment]
Entendi, talvez seja interessante o uso de conteiners (docker ou K8S) pra você conseguir gerenciar melhor os recursos

**Comment by fabioselau077** [comment]
> VPS de 60gb

60gb de ram ou de ssd?

**Comment by pedromagnox** [comment]
ram @fabioselau077
