### ISSUE TITLE
Need to include Number when check status session

### ISSUE THREAD

**Issue by orianablock** [wppconnect-team/wppconnect-server#1286]
its will be good if we can track or know what number of the running session

**Comment by Saifallak** [comment]
https://github.com/wppconnect-team/wppconnect-server/blob/main/src/controller/sessionController.ts#L145 ?

**Comment by orianablock** [comment]
yes, its only show the session not the number need to add response parameter to show the phone number

**Comment by orianablock** [comment]
>

**Comment by Saifallak** [comment]
For loop on them and get profile

**Comment by icleitoncosta** [comment]
> its will be good if we can track or know what number of the running session

You can use the route get-phone-number.
See the example:

https://wppconnect.io/pt-BR/swagger/wppconnect-server#tag/Misc/paths/~1api~1{session}~1get-phone-number/get
