### ISSUE TITLE
SOCKS5

### ISSUE THREAD

**Issue by Padandish** [wppconnect-team/wppconnect-server#1296]
I need wppconnect-server connect to Internet OVER Proxy.
Can it support?

Thanks

**Comment by edgardmessias** [comment]
You can do it using the [proxy-chain](https://www.npmjs.com/package/proxy-chain) package

**Comment by Padandish** [comment]
> You can do it using the [proxy-chain](https://www.npmjs.com/package/proxy-chain) package

I need only chrome use proxy to connect to internet. puppeteer can support launch browser with proxy:
puppeteer.launch({
 
     args: [ '--proxy-server=http://10.10.10.10:8000' ]
  
  });
  
It would be great if this feature was added to the wppconnect-server.
