### ISSUE TITLE
set-limit error

### ISSUE THREAD

**Issue by malik-telegram** [wppconnect-team/wppconnect-server#1298]
```
/api/{session}/set-limit
```

**input** 
`{
  "type": "maxFileSize",
  "value": 104857600
}
`

**response**
`{
  "status": false,
  "message": "Error on set limit",
  "error": {}
}`

**Comment by malik-telegram** [comment]
???@edgardmessias

**Comment by renat473** [comment]
Is there any log error?

which limit do you want to change? @malik-telegram

**Comment by malik-telegram** [comment]
maxFileSize

**Comment by renat473** [comment]
do you have terminal log?

**Comment by renat473** [comment]
depracted

**Comment by malik-telegram** [comment]
> do you have terminal log?

There is no change
