### ISSUE TITLE
Endpoint group-pic não funciona

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1300]
Endpoint group-pic até mostra a mensagem de sucesso, mas a foto do grupo não é trocada

Mais um detalhe: Na documentação do Swagger ele está com um caractere "$" estranho

**Comment by moskoweb** [comment]
Igualmente aqui, fazendo novos testes hoje

**Comment by moskoweb** [comment]
Pelo que vi no código, é solicitado enviar groupId, porém a função tenta utilizar phone, fiz um pull de correção.

https://github.com/wppconnect-team/wppconnect-server/pull/1309
