### ISSUE TITLE
BUG: SEND FILE

### ISSUE THREAD

**Issue by Padandish** [wppconnect-team/wppconnect-server#1303]
## Description

Hi dear, when i send api:
{{baseUrl}}/:session/send-file

when change your base file in postman, receive this error:
{
    "status": "Error",
    "message": "Erro ao enviar a mensagem.",
    "error": {
        "level": "error"
    }
}

but your sample is ok!

**Comment by renat473** [comment]
hello @Padandish what type of file are you trying to send?

**Comment by renat473** [comment]
use route , /send-file-base64
