### ISSUE TITLE
Server does not work with pm2 in cluster mode over nginx

### ISSUE THREAD

**Issue by aureodiasneto** [wppconnect-team/wppconnect-server#1304]
For example, if I start the app with 8 cores, when trying to connect a session, it connects normally but I need to check 8 times (or the number of cores I started) for it to return active, in the others it stays as if it was disconnected

**Comment by renat473** [comment]
is the problem still occurring?
if it still occurs please send more details.

**Comment by aureodiasneto** [comment]
hey, it still happens.

It turns out that, for example, if I upload PM2 in cluster mode (to take advantage of CPU cores), it seems that each worker has an instance of wppconnect, so if I connect the qrcode, only 1 worker can read its status and everything more.

but the ideal is that all workers work the same sessions, for scale

**Comment by renat473** [comment]
The session can use any vcpu core where it does not work with parallelism or allocation of a single vcpu unit.
