### ISSUE TITLE
Run the Api 

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1323]
Hello Developers, 
I m new to this wppconnect and I didn't know how to run it , I get the source code of the repo and run node dev but I get this issue : 
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'D:\Projects\WhatsApp_wssConnect\WhatsAppApi\dev'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

please anyone can help me here?

**Comment by mitnick2012** [comment]
I got this error and managed to fix it by commenting the privacy group function on group controller, and now the app is runing .
src/controller/groupController.ts:976:48 - error TS2345: Argument of type '"restrict"' is not assignable to parameter of type 'GroupProperty'.

976       await req.client.setGroupProperty(group, 'restrict', status === 'true');
                                                   ~~~~~~~~~~


Found 1 error in src/controller/groupController.ts:976

**Comment by renat473** [comment]
hello @mitnick2012  what version of nodejs are you using and what operating system?

**Comment by mitnick2012** [comment]
node v18.16.0

**Comment by mitnick2012** [comment]
it was an error on groupcontroller and when I comment it , the app starts good.
