### ISSUE TITLE
"Session closed" e status diferente entre o /status-session e /check-connection-session

### ISSUE THREAD

**Issue by fabioselau077** [wppconnect-team/wppconnect-server#1331]
## Description

Após iniciar a sessão e ler o QRCode, tudo ocorre como esperado. Porém depois de alguma tempo (1 hora, por exemplo), no logs da função é mostrado 
```
browserClose
2023-06-24T18:49:54.095Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - TargetCloseError: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.".
```
O problema é que ao fazer get no check-connection-session, me retorna status false e message Disconnected, mas ao fazer a request get no status-session, me retorna status CONNECTED, version 2.2.4, qrcode e o urlCode, tudo correto:
<img width="588" alt="image" src="https://github.com/wppconnect-team/wppconnect-server/assets/57275833/2f518219-d6af-4cef-bf22-8f99f2bb53d6">

Nessa situação, se tento fazer alguma request, me retorna o código 404 abaixo:
<img width="548" alt="image" src="https://github.com/wppconnect-team/wppconnect-server/assets/57275833/2b9596bf-637d-46c6-864d-d05e4a9aabab">

## Environment

- **Wppconnect-server version(s):** Last version
- **Browser:** N/D
- **OS:** MacOS (M1 Pro)
- **Node version:** v18.16.1
- **WhatsApp version:** Last Version
- **MultiDevice (BETA):** no
- **config.json:** 
```
export default {
  secretKey: 'THISISMYSECURETOKEN',
  host: 'http://localhost',
  port: '21465',
  deviceName: 'Google Chrome (Ubuntu)',
  poweredBy: 'Fabio',
  startAllSession: true,
  tokenStoreType: 'mongodb',
  maxListeners: 15,
  autoDownload: true,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: "https://webhook.site/minha_url",
    autoDownload: true,
    uploadS3: true,
    awsBucketName: 'teste-whatsapp',
    readMessage: true,
    allUnreadOnStart: true,
    listenAcks: false,
    onPresenceChanged: false,
    onParticipantsChanged: false,
    onReactionMessage: false,
    onPollResponse: false,
    onRevokedMessage: false,
    onLabelUpdated: false,
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true,
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45,
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action
    logger: ['console', 'file'],
  },
  createOptions: {
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
    ],
  },
  mapper: {
    enable: false,
    prefix: 'tagone-',
  },
  db: {
    mongodbDatabase: 'tokens',
    mongodbCollection: 'tokens',
    mongodbUser: 'meu user',
    mongodbPassword: 'minha senha',
    mongodbHost: '',
    mongoIsRemote: true,
    mongoURLRemote:
      'mongodb+srv://meus_banco_mongodb?retryWrites=true&w=majority',
    mongodbPort: 27017,
    redisHost: 'localhost',
    redisPort: 6379,
    redisPassword: '',
    redisDb: 0,
    redisPrefix: 'docker',
  },
};

```

## Steps to Reproduce

1. Criar Token
2. Iniciar Sessão (Start Session)
3. Read QRCode
4. Depois de algum tempo mostra o exception "Session closed." no console e qualquer request informa que o WhatsApp está inativo
5. Nas configurações do WhatsApp ainda mostra o dispositivo como conectado

## Log Output

```
2023-06-24T18:49:54.095Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - TargetCloseError: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

<img width="1087" alt="image" src="https://github.com/wppconnect-team/wppconnect-server/assets/57275833/6c930208-28bf-4642-a3d2-592be108bfe8">
- O dispositivo ainda fica ativo nas configuraçoes do WhatsApp
- Após dá um ctrl + c pra pausar o servidor e rodar npm run dev novamente, o check-connection-session volta o response com status connected:
<img width="614" alt="image" src="https://github.com/wppconnect-team/wppconnect-server/assets/57275833/de6c74ac-4e9c-4195-857b-c7e4bfe27d3c">

E o status-session:
<img width="591" alt="image" src="https://github.com/wppconnect-team/wppconnect-server/assets/57275833/b06d98a0-0ad3-404a-9c30-2ef58812daa4">
Tudo volta funcionar novamente, só tem esse crash da session closed que faz bugar na consulta dos status (um responde q tá inativo o outro q tá ativo)

**Comment by fabioselau077** [comment]
Estou testando aqui mas parece ser um problema exclusivo do macOS. No Docker usando Linux, tive uma sessão ativa por dias sem nenhum erro.

**Comment by daraujo85** [comment]
Estou com o mesmo problema usando docker na nuvem, na minha maquina funciona de boa com docker windows
