### ISSUE TITLE
Disable AutoClose or change its value 

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1332]
Hello everyone, 
I need  to disable auto close or increase it's value but can't find it's value on config.ts
is there any way to do that ? thanks in advance

**Comment by JoseLourenc0** [comment]
you can increase autoClose time up to 2min (time where qrcode is still valid), on createOptions, just like that:
![image](https://github.com/wppconnect-team/wppconnect-server/assets/66333618/dba3180a-36cc-4815-b4d3-78edad87a98b)
![image](https://github.com/wppconnect-team/wppconnect-server/assets/66333618/7d48f366-6dc7-47af-a6f8-00d78b522555)

**Comment by renat473** [comment]
the automatic closing time and the time generated by the qrcode.

you can change the time in the create-session.
