### ISSUE TITLE
How can I connect via proxy?

### ISSUE THREAD

**Issue by Nurlan137** [wppconnect-team/wppconnect-server#1338]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by renat473** [comment]
You can do it using the [proxy-chain](https://www.npmjs.com/package/proxy-chain) package
