### ISSUE TITLE
Como configurar para usar um s3 que não seja o oficial da amazon aws?

### ISSUE THREAD

**Issue by mzramna** [wppconnect-team/wppconnect-server#1365]
existe uma forma de definir a url de acesso para o bucket que será usado para que seja usado um s3 diferente como o minio?
levando em conta que apenas definindo a variavel "endpoint" da biblioteca oficial da amazon isso é possivel, não sei se seria uma dúvida ou uma feature request

**Comment by icleitoncosta** [comment]
No momento não há como, mas vou colocar para implementarmos
