### ISSUE TITLE
get Number by Session Name 

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1382]
Hello Team, 
Is there any way to get whatsapp number by session name  ? 
thanks

**Comment by icleitoncosta** [comment]
Hi, try the route:
https://wppconnect.io/swagger/wppconnect-server/#tag/Misc/paths/~1api~1%7Bsession%7D~1host-device/get

**Comment by mitnick2012** [comment]
thank you @icleitoncosta  :)
