### ISSUE TITLE
Falha ao gerar thumb ao enviar mensagem tipo texto com link

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wppconnect-server#1384]
Está ocorrendo falhas ao gerar o thumb para mensagens de texto com link.
Por vezes envia, por vezes não. 
Quando envia por vezes é thumb pequeno e outras thumb grande.
Isto usando exatamente a mesma mensagem.
Mesmo alternando chips, usando mais de um chip para a mesma mensagem, não há um padrão, pois aleatoriamente gera ou não a thumb.
Isto sempre ocorreu em pequena escala, mas de domingo (16/07/2023) a incidencia de envios sem thumb aumentou muito, ficando maior a quantidade de envios sem thumb que com thumb.
Mesmo com a reconecxão do chip e até com nova leitura de QRCode com a troca da sessão não resolve mais a questão.

## Environment

- **Wppconnect-server version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes/no
- **config.json:** [Your src/config.json file content]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by GMUNDI** [comment]
Acontece o mesmo com mensagens do tipo link.

**Comment by icleitoncosta** [comment]
Opa @GMUNDI, esse é um problema causado pela nossa API de servidores de link preview, a melhor solução talvez seja hospedar um servidor próprio para que sempre fique ativo apenas para você, para isso, basta clonar o projeto https://github.com/wppconnect-team/wa-js-api-server, hospeda-lo em um servidor com SSL, e no config.ts no atributo linkPreviewApiServers incluir o apontamento para ele.

Att,
