### ISSUE TITLE
Send Message and Typing 

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1392]
Hello Team, 
is there ant documentation how to handle send messages with typing methods to avoid whatsapp block bots .

Best Regards

**Comment by Saifallak** [comment]
I do this
send Typing 5sec
Send message
Send stop typing

**Comment by mitnick2012** [comment]
is it working good, and whatsapp doesn't block your numbers ?

**Comment by mitnick2012** [comment]
@Saifallak  why stop typing after we sent message, can we do : 
send Typing 5sec
Send stop typing
Send message

**Comment by Saifallak** [comment]
@mitnick2012 no reason, just though of how i do it on my phone,
typing, send, stop typing

for blocking part:
meta will not block you if you're not spammer, and if they did, it's easy to unblock by contacting them.

anyway, all of that on your own risk.

**Comment by mitnick2012** [comment]
Thanks for explanation
