### ISSUE TITLE
Get Custom Param on webhook response

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1398]
Hello Team, 
is there any way to send a custom param on send message Api and get this param on webhook response, I tried that but didn't get the new param on webhook response.
thanks

**Comment by mitnick2012** [comment]
any solution to that, geeks ?

**Comment by renat473** [comment]
Hello the webhook and event listener between the connected device that sends or receives messages.

Remembering that the webhook does not perform actions.
