### ISSUE TITLE
Alterar arquivo de configurações para .env

### ISSUE THREAD

**Issue by tadeubarbosa** [wppconnect-team/wppconnect-server#140]
Não seria mais interessante ter a opção de subir um arquivo .env para complementar o `src/config.json`?
Estou iniciando a utilização do wppconnect agora, dai me surgiu uma questão: Se quero compartilhar os arquivos entre desenvolvedores, ou até mesmo postar no github como código aberto ou ainda alternar entre o meu computador e o ambiente de produção, vou ficar amarrado ao arquivo config.json. Porém se eu pudesse utilizar um arquivo `.env`, e a função `initServer` ficasse responsável por fazer as substituições ficaria mais fácil.

**Comment by hbdbim** [comment]
Ola Tadeu, a sugestão é otima... estamos reestruturando o server e teremos um .env mas para configuracoes do servidos, configurações da sessões serão passadas no endpoint ao criar as sessões.
