### ISSUE TITLE
Webhook sem Mensagens Enviadas

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wppconnect-server#1407]
Mensagens enviadas não estão sendo mais disparadas no Webhook. Apenas as recebidas.

Já tem meses isso @icleitoncosta. Será que é algo complexo?

**Comment by renat473** [comment]
olá @pedromagnox sua versão esta atualizada ? entra em nosso discord que podemos verificar este problema.

**Comment by pedromagnox** [comment]
Entrei lá @renat473 
Postei a issue no #server

**Comment by pedromagnox** [comment]
Resolvido! É só colocar um true no onSelfMessage lá no config.ts
