### ISSUE TITLE
Erro ao realizar nova Conexão

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#142]
Quando vou fazer uma nova conexão, depois da atualização começou a aparecer o seguinte erro.

```{"name":"ServerStatusCodeError","stack":"ServerStatusCodeError\n    at new i (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:382908)\n    at new i (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:7:67033)\n    at https://web.whatsapp.com/bootstrap_main.0f4eab45314264df4066.js:8:37922\n    at q (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:353990)\n    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.f61502d6311fd24214d7.js:2:353571)","status":401,"statusCode":401} - ServerStatusCodeError```

E ai ele reinicia todas as sessões, o que é um incomodo quando tem mais de 30.

**Comment by hbdbim** [comment]
não foi possivel reproduzir o erro.

**Comment by ghsgabriel** [comment]
Isso ainda acontece @moskoweb ?
