### ISSUE TITLE
can't retrieve qrCode

### ISSUE THREAD

**Issue by carlosdarwed** [wppconnect-team/wppconnect-server#1420]
## Description 

Just happened today, in the past days things were normal as usual, but now when I try to generate the qrCode it simply doesn't show up no matter what I do, I've tried discarding some changes I've made, close/opening vscode, restarting the service multiple times and changing the config.ts file, but I really don't understand what is happening and I need a fix asap.

It looks like it only happens in my machine, and still I don't have clue of what's happening.

thx for your attention

## Environment

- **Wppconnect-server version(s):** [2.2.4]
- **Browser:** [lastest]
- **OS:** [Windows 10]
- **Node version:** [Node 18]
- **WhatsApp version:** [lastest] (i guess)
- **MultiDevice (BETA):** yes
- **config.json:** export default {
  secretKey: 'my-secret-key',
  host: 'http://localhost',
  port: '21465',
  deviceName: 'Wppconnect',
  poweredBy: 'wppconnect',
  startAllSession: true,
  tokenStoreType: 'mongodb',
  privateDb: true,
  maxListeners: 15,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: null,
    autoDownload: true,
    uploadS3: false,
    readMessage: true,
    allUnreadOnStart: false,
    listenAcks: true,
    onPresenceChanged: true,
    onParticipantsChanged: true,
    onReactionMessage: true,
    onPollResponse: true,
    onRevokedMessage: true,
    onLabelUpdated: true,
    onSelfMessage: false,
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true,
  },
  archive: {
    enable: true,
    waitTime: 10,
    daysToArchive: 45,
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action...
    logger: ['console', 'file'],
  },
  createOptions: {
    whatsappVersion: null,
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
    ],
  },
  mapper: {
    enable: false,
    prefix: 'tagone-',
  },
  db: {
    mongodbDatabase: 'tokens',
    mongodbCollection: '',
    mongodbUser: 'my-mongodb-user',
    mongodbPassword: 'my-mongodb-password',
    mongodbHost: 'my-mongodb-host',
    mongoIsRemote: true,
    mongoURLRemote:
      'mongodb+srv:/my-mongo-database@my-host/?retryWrites=true&w=majority',
    mongodbPort: 27017,
    redisHost: 'localhost',
    redisPort: 6379,
    redisPassword: '',
    redisDb: 0,
    redisPrefix: 'docker',
  },
  aws_s3: {
    region: 'sa-east-1',
    access_key_id: null,
    secret_key: null,
    defaultBucketName: null,
  },
};

## Steps to Reproduce

1. call the generate-token endpoint
2. call the start-session endpoint
3. wait and see if the qr coode shows up or not.

## Log Output

no logs, only a hole between the qrCode autoclose messages
```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by carlosdarwed** [comment]
Solved

**Comment by fabioselau077** [comment]
> Solved

Seria bom editar o post com a solução, assim quem tiver o problema já sabe como resolver

**Comment by carlosdarwed** [comment]
Boa tarde @fabioselau077 

Depende muito do caso, ainda acontece às vezes de parar de mandar o qrCode, mas depois volta normalmente

No meu caso é por que eu tinha alterado lá no meu `config.ts` o parâmetro de `secretKey` que não podia ser alterado

Para contexto, o seu deve ficar assim se eu não me engano

`secretKey: THISISMYSECURETOKEN`

**Comment by tbuzatto** [comment]
Olá @carlosdarwed , alterei o secretKey em /src/config.ts, fiz rebuild e reiniciei o servidor. Gerou o QRCode normalmente e estabeleceu conexão.

**Comment by Pankaj-111** [comment]
1. This is expected behavior from the server—it can stop generating QR codes at any time.  
2. After a few days, it tends to freeze, ceasing to send messages while still showing the session as connected.  
3. Running it in a cluster can be extremely challenging; I was unable to get it working in a cluster.  
It is not dependable for production use, so be cautious if you plan to implement it in a production environment. It could turn into a nightmare.
