### ISSUE TITLE
6 Chrome Browser Opened for each Session 

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1445]
Hello Team, 
I'm running the api on a server and I noticed for each session the api opens 6 chrome browsers which is huge when we have multiple sessions opened and consume a lot of ressource on server , is there any way to reduce number of chrome browsers opened ?
thanks

**Comment by renat473** [comment]
And open one browser per session.

What may be happening in your environment and old session that is without devices connected wanting to start the browser.

I recommend deleting old connections.

**Comment by mitnick2012** [comment]
thanks for clarification, can you explain please how to get session without devices using wppconnect api.
