### ISSUE TITLE
config.ts is not loaded in docker container

### ISSUE THREAD

**Issue by peteh** [wppconnect-team/wppconnect-server#1453]
## Description
When building the container with docker compose via 
```docker compose build```

and then starting the container with 
```docker compose up```

It will not load the config.ts file in the main directory

## Environment

- **Wppconnect-server version(s): 2.2.4
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes/no
- **config.json:** [Your src/config.json file content]

## Steps to Reproduce

1. Pull the repo
2. build the container with docker compose build
3. Create a config.ts file in the root of the repo and modify some config
4. Start the server with docker compose up
5. Entries from the config are not taken into account

## Log Output

```
If relevant, paste all of your Log Output
```
I changed the port in the config.ts to
  port: '21461',

However the port is not used as the config.ts file seems not to be read
```
 ✔ Container wppconnect-server-wppconnect-1  Created                                                                                                                                                                                   0.0s 
Attaching to wppconnect-server-wppconnect-1
wppconnect-server-wppconnect-1  | info: 2023-08-23T19:31:59.240Z Server is running on port: 21465
wppconnect-server-wppconnect-1  | info: 2023-08-23T19:31:59.244Z  Visit http://localhost:21465/api-docs for Swagger docs
wppconnect-server-wppconnect-1  | info: 2023-08-23T19:31:59.244Z WPPConnect-Server version: 2.2.4
wppconnect-server-wppconnect-1  | info:     
wppconnect-server-wppconnect-1  |   _       ______  ____  ______                            __ 
wppconnect-server-wppconnect-1  |   | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_

```

# Reason
I found the reason. During the build the ts files are compiled into .js files. 
Thus, the config.ts is only taken into account during the build process. However docker compose does not map it but uses the config.ts file in /src/config.ts which contains default parameters. 

Mapping the config.ts file during the run phase does nothing as the compiled config.js is already there. 

So currently it seems like after compilation it's not possible to change the configuration of the server using a config file.

**Comment by renat473** [comment]
as the dockerfile builds the project, this is why the config.ts file mapping is not loaded at startup.

if you want to change the facade before the build is done or map the build's config.js file.

**Comment by peteh** [comment]
That I understood as well from the code in the end. 

But then the docker-compose file is broken as the mapping of the config.ts is completely pointless if I understand correctly. At the time the config.ts is mapped into the container the binaries are already built. 

Therefore I do not agree with closing this issue as it's not resolved. 

I think it's a leftover from when the config was still a json file that was read at runtime instead of compile time. I think it should be mentioned in the readme that the config is only used at compile time, not at runtime.
