### ISSUE TITLE
/logout-session nao exclui a session

### ISSUE THREAD

**Issue by thiagotoneli** [wppconnect-team/wppconnect-server#1461]
Quando efetuado a chamada acima não está sendo excluido a session, assim que reinciamos a api a mesma gera novamente a qrcode para reconexão
Environment

Wppconnect-server version(s): 2.24
Browser: Chrome 116.0.5845.96-1
OS: Ubuntu server 20.04
MultiDevice (BETA): no

1. Enviei a chamada POST /api/{{session}}/logout-session

2. Sessão retornou "TargetCloseError: Protocol error (Runtime.evoluate): Session closed. Most likely the page has closed."
![errolog-out](https://github.com/wppconnect-team/wppconnect-server/assets/80266445/386357e5-f903-4150-bce7-bd7e38b4f087)

3. Reiniciei a api e ela gerou o qrcode automaticamente na subida.
![apos reiniciar servidor](https://github.com/wppconnect-team/wppconnect-server/assets/80266445/b7d9d620-f97c-4432-874d-fde227a78b43)

**Comment by renat473** [comment]
Olá,

realizado o teste com a útlima versão do server onde o problema se encontra resolvido.

O print abaixo demostra o resultado obtido com sucesso.

![image](https://github.com/wppconnect-team/wppconnect-server/assets/1757167/1876cc49-1329-4796-a0d7-ed64b4fa431f)
