### ISSUE TITLE
Wrong version number in SSL starting the server

### ISSUE THREAD

**Issue by RicardoRamirezR** [wppconnect-team/wppconnect-server#1469]
## Description

wrong version number in SSL staring the server

## Environment

- **Wppconnect-server version(s):** 2.2.5
- **Browser:** Google Chrome 116.0.5845.110 
- **OS:** Ubuntu 22.04.3 LTS
- **Node version:** v16.20.2
- **WhatsApp version:** 2.2331.9
- **MultiDevice (BETA):** n/a
- **config.ts:** only change is the host

## Steps to Reproduce

1. PM2 start wppconnect

## Log Output

0|wppconnect  | info: 2023-08-31T20:40:45.496Z WPPConnect-Server version: 2.2.5
0|wppconnect  | error: 2023-08-31T20:40:45.545Z write EPROTO 140361309059008:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
0|wppconnect  |  - Error: write EPROTO 140361309059008:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
0|wppconnect  |     at Function.AxiosError.from (/opt/wppconnect-server/node_modules/axios/dist/node/axios.cjs:837:14)
0|wppconnect  |     at RedirectableRequest.handleRequestError (/opt/wppconnect-server/node_modules/axios/dist/node/axios.cjs:3016:25)
0|wppconnect  |     at RedirectableRequest.emit (node:events:513:28)
0|wppconnect  |     at ClientRequest.eventHandlers.<computed> (/opt/wppconnect-server/node_modules/follow-redirects/index.js:14:24)
0|wppconnect  |     at ClientRequest.emit (node:events:513:28)
0|wppconnect  |     at TLSSocket.socketErrorListener (node:_http_client:494:9)
0|wppconnect  |     at TLSSocket.emit (node:events:513:28)
0|wppconnect  |     at emitErrorNT (node:internal/streams/destroy:157:8)
0|wppconnect  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
0|wppconnect  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)

## Additional context / Screenshot
<img width="1499" alt="Screenshot 2023-08-31 at 6 48 03 PM" src="https://github.com/wppconnect-team/wppconnect-server/assets/6526545/d041a9b9-cf72-41c1-af49-7fae90e6e945">

**Comment by renat473** [comment]
hello,

update your openssl version or try to use proxy pass with nginx.
