### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:80 - Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by muneebanwar33** [wppconnect-team/wppconnect-server#1471]
I am using docker compose and whenever i start session i get error webhook called i tried to change the machines updating the 

![image](https://github.com/wppconnect-team/wppconnect-server/assets/59768049/f976ea5d-cf63-4e0e-bc6c-79dd895cf5ce)

**Comment by renat473** [comment]
if your webhook is directly to your host.

use the external IP address instead of the localhost address and check your firewall rules.
