### ISSUE TITLE
Gettings make sure you have internet connection on some sessions but not others

### ISSUE THREAD

**Issue by Saifallak** [wppconnect-team/wppconnect-server#1486]
![image](https://github.com/wppconnect-team/wppconnect-server/assets/6053156/506b8bad-e36e-4f0c-83c3-f1592e151f6e)

**Comment by mitnick2012** [comment]
I think you can check session status if it's connected :
https://documenter.getpostman.com/view/9139457/TzshF4jQ#dc592626-d6b3-4655-acc0-c3c45697a7f4
https://wppconnect.io/swagger/wppconnect-server/#tag/Auth/operation/CheckConnectionState

**Comment by Saifallak** [comment]
@mitnick2012 @renat473 Maybe endpoint to force it to load? it was standing like that for hours even restarting it didn't work

**Comment by Saifallak** [comment]
sorry for ping, but any updates to this?

**Comment by Saifallak** [comment]
still having the same issue again 

![image](https://github.com/wppconnect-team/wppconnect-server/assets/6053156/1b273f01-69e9-47ea-95ca-29c96588efca)

on some session but not others, any idea why this is happening ?

**Comment by Saifallak** [comment]
> I think you can check session status if it's connected : https://documenter.getpostman.com/view/9139457/TzshF4jQ#dc592626-d6b3-4655-acc0-c3c45697a7f4 https://wppconnect.io/swagger/wppconnect-server/#tag/Auth/operation/CheckConnectionState

it says connected, but doesn't send any messages..etc , and when I try to take screenshot, I get prev. image.
