### ISSUE TITLE
Dúvida sobre Secret keys

### ISSUE THREAD

**Issue by matheusvalexd** [wppconnect-team/wppconnect-server#1491]
Olá, estou usando o wppconnect e até agora não tive problemas, mas me surgiu uma necessidade que gostaria de saber se é possível! 
É possível configurar/criar mais de uma "Secret Key" ou "SecureToken"? 

Obs: não consegui acesso ao link do discord pois diz que o convite não existe.

**Comment by renat473** [comment]
Olá,

O server atualmente somente permite ter uma única secretkey, já o token você pode gerar tokens individual para cada session.
Caso tenha necessidade de ter uma secretKey para cada session pode utilizar o projeto server-cli que lhe permite esta personalização por session.
