### ISSUE TITLE
bug no v1/{session}/get-media-by-message/{message-id}

### ISSUE THREAD

**Issue by AlexORocha** [wppconnect-team/wppconnect-server#1494]
# Descrição

Em alguns casos, o _endpoint_ **get-media-by-message** retorna o seguinte erro ao solicitar as informações de midia de uma mensagem:

```shell
error: 2023-09-22T21:00:54.740Z Error trying to download the file.
warn: 2023-09-22T21:00:54.744Z Erro ao descriptografar a midia, tentando fazer o download direto...
```

IDs das mensagens de teste:
true_5511945587708@c.us_3EB0C6D410EA2E9B65BBDB
true_5511945587708@c.us_3EB095EEF9DF32B89C9E8A

Podem me ajudar?

**Comment by renat473** [comment]
Realizado testes na última versão e não foi encontrado o problema relatado.


![image](https://github.com/wppconnect-team/wppconnect-server/assets/1757167/a135e774-5583-4cbe-8cf5-79c9f82923fc)

**Comment by Saifallak** [comment]
I can confirm that this problem happens when media is some old or not exist on mobile
