### ISSUE TITLE
urgent : Big issue on Send Message Scalability 

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1504]
## Description
 when I sent thousand of messages to the api it stop responding and return axior error 500 or 400 .
please it's an urgent issue and need support if any one can check with me and fix this issue and I'm ready to pay for that thanks
## Environment

- **Wppconnect-server version(s):** , 2.2.5
- **Browser: Chrome Version 117.0.5938.132
- **OS:**Windows server 2016 Datacenter
- **Node version:** v 18.17.0

- **config.json:** 
"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.default = void 0;
var _default = {
  host: 'http://localhost',
  port: '21465',
  deviceName: 'test',
  poweredBy: 't-Server',
  startAllSession: false,
  tokenStoreType: 'mongodb',
  maxListeners: 250,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: null,
    autoDownload: false,
    uploadS3: false,
    awsBucketName: null,
    readMessage: false,
    allUnreadOnStart: false,
    listenAcks: false,
    onPresenceChanged: false,
    onParticipantsChanged: false,
    onReactionMessage: false,
    onPollResponse: false,
    onRevokedMessage: false,
    onLabelUpdated: false,
	listenMessages: false
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action
    logger: ['console', 'file']
  },
  createOptions: {
	  headless: true,
	autoClose : 120000,
    browserArgs: [
    '--disable-web-security',
    '--no-sandbox',
    '--disable-web-security',
    '--aggressive-cache-discard',
    '--disable-cache',
    '--disable-application-cache',
    '--disable-offline-load-stale-cache',
    '--disk-cache-size=0',
    '--disable-background-networking',
    '--disable-default-apps',
    '--disable-extensions',
    '--disable-sync',
    '--disable-translate',
    '--hide-scrollbars',
    '--metrics-recording-only',
    '--mute-audio',
    '--no-first-run',
    '--safebrowsing-disable-auto-update',
    '--ignore-certificate-errors',
    '--ignore-ssl-errors',
    '--ignore-certificate-errors-spki-list',
	'--disable-features=LeakyPeeker',

            '--unlimited-storage',
			'--full-memory-crash-report',
			'--force-gpu-mem-available-mb',
			'--js-flags=--expose-gc',
			'--no-default-browser-check',
			'--disable-site-isolation-trials',
			'--no-experiments',
	        '--disable-webgl',
            '--disable-infobars',
            '--window-position=0,0',
            '--ignore-certifcate-errors',
            '--ignore-certifcate-espki-list',
            '--disable-threaded-animation',
            '--disable-threaded-scrolling',
            '--disable-in-process-stack-traces',
            '--disable-histogram-customizer',
            '--disable-gl-extensions',
            '--disable-composited-antialiasing',
            '--disable-canvas-aa',
            '--disable-3d-apis',
            '--disable-accelerated-2d-canvas',
            '--disable-accelerated-jpeg-decoding',
            '--disable-accelerated-mjpeg-decode',
            '--disable-app-list-dismiss-on-blur',
            '--disable-accelerated-video-decode',
            '--disable-dev-shm-usage',
		    '--ignore-gpu-blacklist',           
            '--disable-gpu',
			'--disable-setuid-sandbox',
			'--log-level=3',
            '--no-treekill',
            '--enable-features=NetworkService'
			

	]
 
## Steps to Reproduce

1. send thousand of messages on the same time to the api 
2. the api crach and stop responding 

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by renat473** [comment]
to send an automatic volume of messages to suggestions and use intervals between messages and create a queuing system for consuming the messages to be sent.

**Comment by mitnick2012** [comment]
yes, this is what I did, I was working on windows server and moved to Linux ubuntu, and all issues are gone now.
