### ISSUE TITLE
How do I change the default Chrome browser to Mozila?

### ISSUE THREAD

**Issue by leonardovilela100** [wppconnect-team/wppconnect-server#1510]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by Saifallak** [comment]
There is plans to  Migrate to Playwright here https://github.com/wppconnect-team/wppconnect/issues/808

**Comment by renat473** [comment]
Hello, at this time no documentation has been implemented or created to change the browser type.

One of these reasons is browser compatibility.

Suggestion and review the settings of your vps or server instance.
