### ISSUE TITLE
Não respeita a configuração de linkPreviewApiServers no config.ts

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wppconnect-server#1523]
Configurei conforme orientado no config.ts para usar o linkPreviewApiServers: ['https://meuserver.com.br'], porém o envio não respeita a definição e hora usa o meu servidor para gerar a thumb, hora não. Quando não usa o meu server (monitoro pelo log do pm2) por vezes envia com thumb outras não.
Seria possível forçar a utilização da geração de thumbs exclusivamente do meu server?

## Environment

wppconnect-server: 2.2.5
wppconnect: ^1.28.0
nodejs: v16.20.2
Ubuntu 20.04.6 LTS

**Comment by gitdedc** [comment]
Essa correção já foi liberada e o recurso está funcionando corretamente, conforme orientações abaixo:

/**
     * Example of configuring the linkPreview generator
     * If you set this to 'null', it will use global servers; however, you have the option to define your own server
     * Clone the repository https://github.com/wppconnect-team/wa-js-api-server and host it on your server with ssl
     *
     * Configure the attribute as follows:
     * linkPreviewApiServers: [ 'https://www.yourserver.com/wa-js-api-server' ]
     */
    linkPreviewApiServers: null,

Caso ainda esteja com o problema, após atualizar toda a biblioteca, abra uma nova issue com o log detalhando o erro no carregamento do preview.
