### ISSUE TITLE
startTyping, stopTyping Crash and restart server

### ISSUE THREAD

**Issue by wenioferraz** [wppconnect-team/wppconnect-server#154]
Função startTyping, stopTyping, crashando o server e reiniciando.

Ao usar a função retornar o erro no console
Error: CHAT_JID: invalid jid type: Not an instance of WID

**Comment by bgastaldi** [comment]
Bom dia @wenioferraz atualiza a lib para ultima versão. 
https://github.com/wppconnect-team/wppconnect/commit/a122b15deecfcb6f64c9be57b5d03e9fdfaab119.

Se funcionar, me avise por aqui para fechar a issue.

**Comment by bgastaldi** [comment]
Fixed https://github.com/wppconnect-team/wppconnect/commit/a122b15deecfcb6f64c9be57b5d03e9fdfaab119
