### ISSUE TITLE
Sending Group Message Returns Success But Not Sending

### ISSUE THREAD

**Issue by atiqullah-ahmadzai** [wppconnect-team/wppconnect-server#1558]
## Description

When sending message in the group, it returns success but message are not coming in the group actually.
I am using latest everything, I just setup it yesterday.

Request:
curl --location 'http://localhost:21465/api/DEFAULT/send-message' \
--header 'accept: */*' \
--header 'Authorization: Bearer $2b$10$avehVUaCcJVFcZCmhtP3XezPSOmzqTd18sw78O7wM84W0ii3OA_vq' \
--header 'Content-Type: application/json' \
--data '{
    "phone":"120363175540797171",
    "isGroup":true,
    "message": "Hello, testing"
}'

Response:
{
    "status": "success",
    "response": [
        {
            "id": "true_120363175540797171@g.us_3EB06F54CEB45003ECF86A_*****@c.us",
            "body": "Hello, testing",
            "type": "chat",
            "subtype": null,
            "t": 1698853173,
            "from": "******@c.us",
            "to": "120363175540797171@g.us",
            "self": "out",
            "ack": 0,
            "isNewMsg": true,
            "star": false,
            "kicNotified": false,
            "isFromTemplate": false,
            "pollInvalidated": false,
            "isSentCagPollCreation": false,
            "latestEditMsgKey": null,
            "latestEditSenderTimestampMs": null,
            "mentionedJidList": [],
            "groupMentions": [],
            "urlText": null,
            "urlNumber": null,
            "isVcardOverMmsDocument": false,
            "isForwarded": false,
            "labels": [],
            "hasReaction": false,
            "isSendFailure": true,
            "productHeaderImageRejected": false,
            "lastPlaybackProgress": 0,
            "isDynamicReplyButtonsMsg": false,
            "isMdHistoryMsg": false,
            "stickerSentTs": 0,
            "isAvatar": false,
            "lastUpdateFromServerTs": 0,
            "requiresDirectConnection": false,
            "invokedBotWid": null,
            "chatId": "120363175540797171@g.us",
            "fromMe": true,
            "sender": {
                "id": "*****@c.us",
                "name": "*****",
                "shortName": "*****",
                "pushname": "**********",
                "type": "in",
                "verifiedName": "**********",
                "isBusiness": true,
                "isEnterprise": false,
                "isSmb": true,
                "verifiedLevel": 0,
                "privacyMode": null,
                "labels": [],
                "isContactSyncCompleted": 1,
                "formattedName": "You",
                "isMe": true,
                "isMyContact": true,
                "isPSA": false,
                "isUser": true,
                "isWAContact": true,
                "profilePicThumbObj": null,
                "msgs": null
            },
            "timestamp": 1698853173,
            "content": "Hello, testing",
            "isGroupMsg": true,
            "mediaData": {}
        }
    ],
    "mapper": "return",
    "session": "DEFAULT"
}

**Comment by mahmoudgoogle** [comment]
I have this same problem in the latest version 2.2.5
But everything works fine with version 2.2.4

**Comment by danielsantb** [comment]
Same here!

Server 2.2.5
Node: 18.16

**Comment by renat473** [comment]
update version
problem fixed in the latest versions.
