### ISSUE TITLE
É possivel salvar uma sessão para não precisar ficar lendo o QR Code toda vez que subir o container docker?

### ISSUE THREAD

**Issue by kennedtecnico** [wppconnect-team/wppconnect-server#1576]
Estou rodando a API no meu container docker na nuvem normalmente, depois de um certo tempo, a API é escalonada para 0 e o meu container é derrubado e perde as sessões que estavam conectadas, ao subi-lo novamente esta precisando ler o QR Code.
Tem alguma forma para eu estar salvando a sessão? Para não precisar ficar lendo o QR Code toda vez que acontecer isto.

**Comment by icleitoncosta** [comment]
Olá @kennedtecnico você precisa adicionar a pasta userDataDir como um volume com persistent data, que os dados irão se manter.

Segue um tutorial que pode seguir:
https://towardsai.net/p/l/a-guide-to-persistent-storage-in-docker
