### ISSUE TITLE
Send group message failed return 400

### ISSUE THREAD

**Issue by rizzatto** [wppconnect-team/wppconnect-server#1583]
Endpoint: /api/5001/send-message

body
{
	"phone": "120363179345385836",
	"message": "oi",
	"isGroup": true
}

Response: 400 Bad Request
{
	"response": null,
	"status": "Connected",
	"message": "O número 120363179345385836 não existe.",
	"session": "5001"
}

Thanks a lot

**Comment by icleitoncosta** [comment]
Hi, please try with the last version of wppconnect.

This issue was solved!

**Comment by rizzatto** [comment]
Hi, I'am using the last version, but the problem persists.

**Comment by icleitoncosta** [comment]
Please, paste your payload here.

**Comment by mdestafadilah** [comment]
new group or old group? sometimes, id of group is different.

**Comment by rizzatto** [comment]
The group is new! Created for test only!

**Comment by renat473** [comment]
Fixed in the latest version.
