### ISSUE TITLE
erro na rota /take-screenshot

### ISSUE THREAD

**Issue by brunopiaca2** [wppconnect-team/wppconnect-server#1635]
usando o server via a rota /take-screenshot a imagem está voltando dessa forma:
![image](https://github.com/wppconnect-team/wppconnect-server/assets/74620945/34306ca9-9d63-4440-9999-caff767bd8df)

**Comment by Saifallak** [comment]
+1

**Comment by cgslivre** [comment]
+1

**Comment by gitdedc** [comment]
Bom dia Bruno

Acabo de fazer um teste a o print retornado no base64 foi perfeito.

Versão Whatsapp utilizada:
2.2411.x

Por favor, faça atualização completa do pacote, com base no git e teste com essa versão.

**Comment by gitdedc** [comment]
Encerrando a issue por falta de interações.  Testado e tudo funcionando. 

Versão Whatsapp utilizada:
2.2411.x

Por favor, faça atualização completa do pacote, com base no git e teste com essa versão.
