### ISSUE TITLE
Erro (no sharp) ao executar o projeto através da imagem Docker disponibilizada.

### ISSUE THREAD

**Issue by thiagocc** [wppconnect-team/wppconnect-server#1672]
## Description

Erro (no sharp) ao executar o projeto através da imagem Docker disponibilizada.

## Environment

- **Docker version** [23, 24]
- **Node version:** [lts]

## Steps to Reproduce

1. docker compose up

## Log Output

```
wppconnect-1  | /usr/src/wpp-server/node_modules/sharp/lib/sharp.js:107
wppconnect-1  |   throw new Error(help.join('\n'));
wppconnect-1  |   ^
wppconnect-1  |
wppconnect-1  | Error: Could not load the "sharp" module using the linuxmusl-x64 runtime
wppconnect-1  | Possible solutions:
wppconnect-1  | - Ensure optional dependencies can be installed:
wppconnect-1  |     npm install --include=optional sharp
wppconnect-1  |     yarn add sharp --ignore-engines
wppconnect-1  | - Ensure your package manager supports multi-platform installation:
wppconnect-1  |     See https://sharp.pixelplumbing.com/install#cross-platform
wppconnect-1  | - Add platform-specific dependencies:
wppconnect-1  |     npm install --os=linuxmusl --cpu=x64 sharp
wppconnect-1  |     npm install --force @img/sharp-linuxmusl-x64
wppconnect-1  | - Consult the installation documentation:
wppconnect-1  |     See https://sharp.pixelplumbing.com/install
wppconnect-1  |     at Object.<anonymous> (/usr/src/wpp-server/node_modules/sharp/lib/sharp.js:107:9)
wppconnect-1  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
wppconnect-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
wppconnect-1  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
wppconnect-1  |     at Module._load (node:internal/modules/cjs/loader:1023:12)
wppconnect-1  |     at Module.require (node:internal/modules/cjs/loader:1235:19)
wppconnect-1  |     at require (node:internal/modules/helpers:176:18)
wppconnect-1  |     at Object.<anonymous> (/usr/src/wpp-server/node_modules/sharp/lib/constructor.js:10:1)
wppconnect-1  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
wppconnect-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
wppconnect-1  |
wppconnect-1  | Node.js v20.10.0
```

**Comment by unilogica** [comment]
A PR #1676 corrige isso.

https://github.com/wppconnect-team/wppconnect-server/pull/1676

**Comment by lemosluan** [comment]
> A PR #1676 corrige isso.
> 
> <img alt="Captura de Tela 2024-01-13 às 05 57 36" width="614" src="https://private-user-images.githubusercontent.com/7243084/296440744-fa297f38-1597-43a5-9b1d-4f32bbde9e92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTA2MDYsIm5iZiI6MTcxMTIxMDMwNiwicGF0aCI6Ii83MjQzMDg0LzI5NjQ0MDc0NC1mYTI5N2YzOC0xNTk3LTQzYTUtOWIxZC00ZjMyYmJkZTllOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMTYxMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzFhM2RkZWMwOTkxMDcyMzhhNzNhYzk2MTlhMTgwYzQ5YzI3NzExZTM0MmExNTNmYmYxNzI1ZDU3ZWQ4YjYxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lpqH_9UBbBIpZegUA9Vked-6Htnq__fzNPg7DysMW8A"> <img alt="Captura de Tela 2024-01-13 às 05 57 25" width="517" src="https://private-user-images.githubusercontent.com/7243084/296440752-7243f8a9-93c1-4459-8ffc-511ff16cef57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTA2MDYsIm5iZiI6MTcxMTIxMDMwNiwicGF0aCI6Ii83MjQzMDg0LzI5NjQ0MDc1Mi03MjQzZjhhOS05M2MxLTQ0NTktOGZmYy01MTFmZjE2Y2VmNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMTYxMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUzYmQ1Nzk5ZTJiODVhNTk3MWJiNmRhYjllMTNiZmJmNGI3YzgzNjJjYWIxYzVkOGVhNTQzMzI5MmUwOTZjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z4e5oIRaqrBYyj1-pOx__Id5TgYvRKifNSwvt5X2SvE">

If it didnt works, try add this line on the final stage:

```
RUN apk update && \
    apk add --no-cache \
    vips-dev \
    fftw-dev \
    gcc \
    g++ \
    make \
    libc6-compat \
    && rm -rf /var/cache/apk/*
```
