### ISSUE TITLE
ERR_UNKNOWN_FILE_EXTENSION

### ISSUE THREAD

**Issue by gildonei** [wppconnect-team/wppconnect-server#1674]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Wppconnect-server version(s):** 2.3.0
- **Browser:** -
- **OS:** Debian 12
- **Node version:** v18.19.0
- **WhatsApp version:** 
- **MultiDevice (BETA):** no
- **config.json:*
[package.json](https://github.com/wppconnect-team/wppconnect-server/files/13873259/package.json)

## Steps to Reproduce

Error occurred on a fresh install in a WSL Debian

1. git clone https://github.com/wppconnect-team/wppconnect-server.git && cd wppconnect-server
2. yarn install
3. yarn dev

## Log Output

```
junior@DESKTOP-GILDONEI:~/wppconnect-server$ yarn dev
yarn run v1.22.20
$ cross-env TS_NODE_FILES=true TS_NODE_TRANSPILE_ONLY=true NODE_PATH=src nodemon --watch src --exec ts-node --esm src/server.ts -e ts
[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node --esm src/server.ts`
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/junior/wppconnect-server/src/server.ts
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
    at defaultLoad (node:internal/modules/esm/load:101:20)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at load (/home/junior/wppconnect-server/node_modules/ts-node/dist/child/child-loader.js:19:122)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at Hooks.load (node:internal/modules/esm/hooks:447:26)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:196:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
[nodemon] app crashed - waiting for file changes before starting...
```

## Additional context / Screenshot

O erro aconteceu ao tentar realizar uma nova instalação seguindo as orientações dos tutoriais e uma instalação limpa em um WSL Debian 12

**Comment by Ippephyx** [comment]
I have the very same problem with Ubuntu (20 and 22)
![image](https://github.com/wppconnect-team/wppconnect-server/assets/59560947/2b6311ba-6b48-4ab0-a670-398a788df187)

**Comment by renat473** [comment]
fix version

node 18.17.0

**Comment by Ippephyx** [comment]
I just tried with Fedora... same results. 
And I've tried your suggestion with node 18 (18.19 to be exact), but same results : 
![image](https://github.com/wppconnect-team/wppconnect-server/assets/59560947/dc34ccdc-9ad5-4c83-bef9-6d1e1f74fa5c)

**Comment by Ippephyx** [comment]
Yes, node 18.17.0 solves it.
Thank you so much and sorry for not getting it the first time.
