### ISSUE TITLE
 I don't receive the messages in chatwoot

### ISSUE THREAD

**Issue by KatiaSishost** [wppconnect-team/wppconnect-server#1681]
I can send messages from chatwoot without problem, but I don't receive the messages... should I configure a webhook or something on the wppconnect-server?

other, if i create new accout (admin) and create new token, create session scan qrcode from docker console... the 2nd account cant send message!

**Comment by renat473** [comment]
Update version and reconfigure inbox chatwoot with address IP or DNS
