### ISSUE TITLE
Link via phone number instead of QR

### ISSUE THREAD

**Issue by YosefAdPro** [wppconnect-team/wppconnect-server#1687]
https://github.com/wppconnect-team/wppconnect/issues/2031

**Comment by Saifallak** [comment]
> > awesome, waiting for this in @wppconnect-server
> 
> Next release of @wppconnect-server



ref: https://github.com/wppconnect-team/wppconnect/issues/1921#issuecomment-1986845431

**Comment by aymansyam** [comment]
is this as simple as adding this in createSessionUtil()?

```javascript
phoneNumber: client.config?.phoneNumber,
```

I've tried it locally but it doesn't return the link code for some reason :(

Also, a new route similar to POST /qrcode-session which gets you the link code would be nice.

**Comment by icleitoncosta** [comment]
> is this as simple as adding this in createSessionUtil()?
> 
> ```js
> phoneNumber: client.config?.phoneNumber,
> ```
> 
> I've tried it locally but it doesn't return the link code for some reason :(
> 
> Also, a new route similar to POST /qrcode-session which gets you the link code would be nice.

So that's one way. At the moment we have not yet implemented it in a standard way on the server, it will soon be implemented in the next release.
```

      const wppClient = await create(
        Object.assign(
          {},
          { tokenStore: myTokenStore },
          req.serverOptions.createOptions,
          {
            session: session,
            phoneNumber: '5521999999999',
            deviceName:
              client.config?.deviceName || req.serverOptions.deviceName,
            poweredBy:
              client.config?.poweredBy ||
              req.serverOptions.poweredBy ||
              'WPPConnect-Server',
[...code....]
```

**Comment by aymansyam** [comment]
With the newest release, I tried the above but still it doesn't output the code in the terminal.

After some debugging I found that it gets stuck in evaluateAndReturn:

```javascript

  protected async loginByCode(phone: string) {
    const code = await evaluateAndReturn(
      this.page,
      async ({ phone }) => {
        return JSON.parse(
          JSON.stringify(await WPP.conn.genLinkDeviceCodeForPhoneNumber(phone))
        );
      },
      { phone }
    );

```

For some reason, when the wppconnect is ran through wppconnect-server, WPP.conn.genLinkDeviceCodeForPhoneNumber does not return at all. It's weird because wppconnect by itself does return the code, so this may be a configuration issue on wppconnect-server.

**Comment by aymansyam** [comment]
Hi, is this feature still gonna get added?

**Comment by jaygent** [comment]
> With the newest release, I tried the above but still it doesn't output the code in the terminal.
> 
> After some debugging I found that it gets stuck in evaluateAndReturn:
> 
> ```js
>   protected async loginByCode(phone: string) {
>     const code = await evaluateAndReturn(
>       this.page,
>       async ({ phone }) => {
>         return JSON.parse(
>           JSON.stringify(await WPP.conn.genLinkDeviceCodeForPhoneNumber(phone))
>         );
>       },
>       { phone }
>     );
> ```
> 
> For some reason, when the wppconnect is ran through wppconnect-server, WPP.conn.genLinkDeviceCodeForPhoneNumber does not return at all. It's weird because wppconnect by itself does return the code, so this may be a configuration issue on wppconnect-server.

did you manage to find a solution to the problem?

**Comment by jaygent** [comment]
if you delete this
```
deviceName:
              client.config?.deviceName || req.serverOptions.deviceName,
            poweredBy:
              client.config?.poweredBy ||
              req.serverOptions.poweredBy ||
              'WPPConnect-Server',
```
then everything works

**Comment by Saifallak** [comment]
i made a PR https://github.com/wppconnect-team/wppconnect-server/pull/1959

**Comment by icleitoncosta** [comment]
Implemented by @Saifallak in PR #1959

**Comment by YosefAdPro** [comment]
How do I display the code, in start-session?

**Comment by cr4ck3r-byte** [comment]
No work

**Comment by ngethe** [comment]
Hi was this solved how can I implement it?
