### ISSUE TITLE
 Could not load the "sharp" module using the win32-x64 runtime

### ISSUE THREAD

**Issue by FahadAltaf** [wppconnect-team/wppconnect-server#1691]
![image](https://github.com/wppconnect-team/wppconnect-server/assets/5881092/16577564-7820-4817-9a2d-99925e462e4e)

**Comment by unilogica** [comment]
Look this workaround PR #1676

**Comment by icleitoncosta** [comment]
If you're using yarn, I highly recommend you upgrade to v3+.

**Comment by FahadAltaf** [comment]
Thanks @unilogica. It fixed the issue
