### ISSUE TITLE
Error creating group

### ISSUE THREAD

**Issue by my3dnn** [wppconnect-team/wppconnect-server#1694]
When I create it on the server via curl this response still appears

{"status":"error","message":"Error creating group(s)","session":"Session"}

However, the group was created with all the correct telephone numbers.

the json that creates the group is this:

{
"name" : "group test",
"participants" : [ "55489842889998" ]
}

**Comment by my3dnn** [comment]
someone with the same problem? I've already updated wppconnect but I still have the same problem and I don't know what to do

**Comment by gitdedc** [comment]
I checked right now with last version and all dependencies updated.
The group creation works fine.
Please update all libraries and repositories.
Closing this issue.
