### ISSUE TITLE
Any one with problem to generate QRCODE ?

### ISSUE THREAD

**Issue by rizzatto** [wppconnect-team/wppconnect-server#1700]
Problem to generate QRCODE.

It was working normally until yesterday.

But today it's not working anymore.

**Comment by rodolfojnn** [comment]
Since yesterday, a strange error also started

![image](https://github.com/wppconnect-team/wppconnect-server/assets/3813415/2ee1da72-0b55-49a5-821a-df3b18b6ec3c)

**Comment by cgslivre** [comment]
+1

**Comment by cgslivre** [comment]
"The whatsapp version is out of date"

When run with headless: false

**Comment by netomarchiori** [comment]
I'm seeing issues as well related to wapi.js failed, it happened yesterday, I've updated wpp-connect server and it worked.

and its now failing again for some reason

**Comment by rodolfojnn** [comment]
We tried a few things that worked and the service started working again, it's probably the NodeJS version:

- upgrade to NodeJS 18.7.0
- yarn add typescript ts-node
- yarn add sharp --ignore-engines

**Comment by netomarchiori** [comment]
I'm already on 18.17.1 and no luck

**Comment by smlsilva** [comment]
I managed to solve it with the following steps

- I CLONED THE NEW VERSION
- EXECUTE ALL THE COMMANDS BELOW BEFORE INSTALLING node_modules:

1- INSIDE THE WPPCONECT FOLDER EXECUTE: yarn add sharp
2- EXECUTE:
npm install --include=optional sharp
or
yarn add sharp --ignore-engines
3- THEN INSTALL node_modules: npm install
4- AFTER INSTALLATION EXECUTE THE APPLICATION COMMAND
