### ISSUE TITLE
Propriedade Session indefinida

### ISSUE THREAD

**Issue by leonardop21** [wppconnect-team/wppconnect-server#172]
Estou utilizando o pacote do Laravel, mas depois que atualizei a versão do wppconnect-server (1.1.1) parou de gerar as sessões

O código utilizado:

` <?php  if(!Session::get('token') and !Session::get('session')):
            Wppconnect::make($this->url);
            $response = Wppconnect::to('/api/'.$this->session.'/'.$this->key.'/generate-token')->asJson()->post();
            $response = json_decode($response->getBody()->getContents(),true);
            if($response['status'] == 'success'):
                Session::put('token', $response['token']);
                Session::put('session', $response['session']);
            endif;
        endif; ?>  `

Retorna as propriedades: **status, token, full** mas não a session confirme print abaixo

![laravel1](https://user-images.githubusercontent.com/17708447/128791718-401ce92d-4db6-441a-a987-07371fff2b1e.png)

**Comment by leonardop21** [comment]
Resolvido

No arquivo encryptController.js comentei todo o retorno e fiz da seguinte maneira

` res.setHeader('Content-Type', 'application/json');

    return res.status(201).end(JSON.stringify({
      status: 'success',
      session: session,
      token: hashFormat,
      full: `${session}:${hashFormat}`,
    }));`

![2](https://user-images.githubusercontent.com/17708447/128798247-6262f2d7-dbd9-492f-ac43-de8170f72a3d.png)

**Comment by bgastaldi** [comment]
re-aberto para correção.

**Comment by bgastaldi** [comment]
Fixed: https://github.com/wppconnect-team/wppconnect-server/commit/38d096357fa0643efbfc9a822e508508f84e90e9
