### ISSUE TITLE
Sockets.io - send message (text, files,mídia) / notificações 

### ISSUE THREAD

**Issue by Jbloss80** [wppconnect-team/wppconnect-server#1729]
Possibilitar o envio de mensagens através do canal do socket.io.

O cliente do soocket envia a mensagem e a mesma é direcionada pelo servidor do soocket.io para a rota de envio de mensagens para o whatsapp.

Seria uma alternativa ao send-message pelo canal do socket.io

Também possibilitar o envio de notificações para 1 ou todos os clientes conectados no servidor do socket.io, facilitando as notificações.

**Comment by renat473** [comment]
Hello, this type of functionality is only available for other projects that are not part of wppconnect.
