### ISSUE TITLE
Not updating on server for old send message to chatwoot. 

### ISSUE THREAD

**Issue by shivamkb17** [wppconnect-team/wppconnect-server#1734]
## Description

I am connecting chatwoot using the webhook url. But I see error like, In webhook I only recieving message. but message in dashboard is not updated when I send some message from my mobile to that person.  
## Environment

- **Wppconnect-server version(s):** latesh
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** Node 20
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes
- **config.json:** 
[config.txt](https://github.com/wppconnect-team/wppconnect-server/files/14373209/config.txt)

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```
No any changes in code. 
## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by renat473** [comment]
Hello, I carried out recent tests and this reported problem was not found.
