### ISSUE TITLE
/check-connection-session does not respond after first attempt and crashes

### ISSUE THREAD

**Issue by marcelomedina22** [wppconnect-team/wppconnect-server#1737]
## Description

I'm having an issue on 2.4.0 in the /check-connection-session, it does not respond and gets timeout.
Estou tendo problemas na versão 2.4.0 em que o /check-connection-session após aperto a sessão não responde e tenho timeout

## Environment

- **Wppconnect-server version(s):**2.4.0
- **Browser:** Chrome
- **OS:** RockyLinux9
- **Node version:** Node 18.19
- **WhatsApp version:** -
- **MultiDevice (BETA):** yes
- **config.json:** 
   autoDownload: false,
    uploadS3: false,
    readMessage: false,
    allUnreadOnStart: false,
    listenAcks: false,
    onPresenceChanged: false,
    onParticipantsChanged: false,
    onReactionMessage: false,
    onPollResponse: true,
    onRevokedMessage: false,
    onLabelUpdated: false,
    onSelfMessage: false,
    ignore: ['status@broadcast'],
  },
  websocket: {
    autoDownload: false,
    uploadS3: false,
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true,
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45,
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action
    logger: ['console', 'file'],
  },
  createOptions: {
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
    ],

## Steps to Reproduce

1. Generate Token
2.Start Session
3. Check Session Status

## Log Output
Timeout

//// Relevant
If the session is auto started the  /check-connection-session returns the status, if is just created that when the problem happens.

//// What I did
I switch back to 2.3.0

**Comment by gitdedc** [comment]
Hi Marcelo.  I'm checking and reproducing your issue using whatsapp version 2.2411.x.
I tried several times "status-session" and I always get connected status (correct).  I didn't get above error.
Can you test with version 2.2411.x?

**Comment by gitdedc** [comment]
I Redo tests and its works fine (with last version and 2.2411.x wa version)

{
    "status": true,
    "message": "Connected"
}

The tests were with auto connection and manual connection.

Check all dependencies and updates.
