### ISSUE TITLE
Webhook com opção para envio do caminho do arquivo ou Base64

### ISSUE THREAD

**Issue by vazjunior** [wppconnect-team/wppconnect-server#1775]
Para quem usa webhook seria interessante se em config.ts tivesse a opção para escolhermos que forma queremos receber os dados como imagem, video e documentos no webhook. Exemplo, se escolho que quero receber link do arquivo o servidor do salvaria as imagens, videos ou documentos em uma pasta no servidor e enviaria para o webhook apenas o caminho da pasta, isso ficaria como opção no arquivo config.ts se quero receber base64 ou caminho do arquivo.

**Comment by PedroShimpa** [comment]
preciso do mesmo recurso também
