### ISSUE TITLE
How to Change DeviceName and icon

### ISSUE THREAD

**Issue by mrrizwan91** [wppconnect-team/wppconnect-server#1778]
![wppconnect-icon-issue](https://github.com/wppconnect-team/wppconnect-server/assets/5940293/ae0c5444-05b8-43c3-8828-39a7dd3afe80)
How to Change DeviceName and icon like 
Chrome icon not showing in WhatsApp linked Devices

**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by m3ck0** [comment]
If someone has information about this, the feedback will be much appreciated!

**Comment by derciesto** [comment]
@mrrizwan91 you can change the name in [config.ts](https://github.com/wppconnect-team/wppconnect-server/blob/main/src/config.ts)  using **deviceName** , not sure about icon how we can change

**Comment by gitdedc** [comment]
Device name you change in config.ts (like @mrrizwan91)
The icon is not possible
