### ISSUE TITLE
error with random period after running with pm2

### ISSUE THREAD

**Issue by leonardols10** [wppconnect-team/wppconnect-server#1786]
## Description
Randomly
[Description of the bug, When Issue Happens]

call generate token
get qr code
and logout api

## Environment

- **Wppconnect-server version(s): 2.4.1
- **Browser:** Google Chrome 120.0.6099.62
- **OS:** Linux vps44729 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
- **Node version:** 16.20.2
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** no
- **config.json:```
export default {
  secretKey: 'xxxxxx',
  host: 'http://0.0.0.0',
  port: '21465',
  deviceName: 'Alleshub Whatsapp Connect',
  poweredBy: 'Alleshub',
  startAllSession: true,
  tokenStoreType: 'file',
  maxListeners: 15,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: null,
    autoDownload: true,
    uploadS3: false,
    readMessage: true,
    allUnreadOnStart: false,
    listenAcks: true,
    onPresenceChanged: true,
    onParticipantsChanged: true,
    onReactionMessage: true,
    onPollResponse: true,
    onRevokedMessage: true,
    onLabelUpdated: true,
    onSelfMessage: false,
    ignore: ['status@broadcast'],
  },
  websocket: {
    autoDownload: false,
    uploadS3: false,
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true,
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45,
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action
    logger: ['console', 'file'],
  },
  createOptions: {
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
    ],
    /**
     * Example of configuring the linkPreview generator
     * If you set this to 'null', it will use global servers; however, you have the option to define your own server
     * Clone the repository https://github.com/wppconnect-team/wa-js-api-server and host it on your server with ssl
     *
     * Configure the attribute as follows:
     * linkPreviewApiServers: [ 'https://www.yourserver.com/wa-js-api-server' ]
     */
    linkPreviewApiServers: null,
  },
  mapper: {
    enable: false,
    prefix: 'tagone-',
  },
  db: {
    mongodbDatabase: 'tokens',
    mongodbCollection: '',
    mongodbUser: '',
    mongodbPassword: '',
    mongodbHost: '',
    mongoIsRemote: true,
    mongoURLRemote: '',
    mongodbPort: 27017,
    redisHost: 'localhost',
    redisPort: 6379,
    redisPassword: '',
    redisDb: 0,
    redisPrefix: 'docker',
  },
  aws_s3: {
    region: 'sa-east-1',
    access_key_id: null,
    secret_key: null,
    defaultBucketName: null,
    endpoint: null,
    forcePathStyle: null,
  },
};
```

[
## Steps to Reproduce

1. Clean git pull
2. build with npm run build
3.
Schedule to run with pm2
## Log Output
`1|yarn dev | Error: Requesting main frame too early!
1|yarn dev |     at assert (/var/www/html/wppconnect-server/node_modules/puppeteer-core/src/util/assert.ts:19:11)
1|yarn dev |     at FrameManager.mainFrame (/var/www/html/wppconnect-server/node_modules/puppeteer-core/src/cdp/FrameManager.ts:261:11)
1|yarn dev |     at CdpPage.mainFrame (/var/www/html/wppconnect-server/node_modules/puppeteer-core/src/cdp/Page.ts:498:31)
1|yarn dev |     at CdpPage.evaluate (/var/www/html/wppconnect-server/node_modules/puppeteer-core/src/api/Page.ts:2181:23)
1|yarn dev |     at /var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:99:56
1|yarn dev |     at step (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
1|yarn dev |     at Object.next (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
1|yarn dev |     at /var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:24:71
1|yarn dev |     at new Promise (<anonymous>)
1|yarn dev |     at __awaiter (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:20:12)
1|yarn dev |     at evaluateAndReturn (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:71:12)
1|yarn dev |     at Whatsapp.<anonymous> (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:642:82)
1|yarn dev |     at step (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:60:23)
1|yarn dev |     at Object.next (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:41:53)
1|yarn dev |     at /var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:35:71
1|yarn dev |     at new Promise (<anonymous>)
1|yarn dev |     at __awaiter (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:31:12)
1|yarn dev |     at Whatsapp.HostLayer.isConnected (/var/www/html/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:639:16)
1|yarn dev |     at statusConnection (/var/www/html/wppconnect-server/src/middleware/statusConnection.ts:29:24)
1|yarn dev |     at Layer.handle [as handle_request] (/var/www/html/wppconnect-server/node_modules/express/lib/router/layer.js:95:5)
1|yarn dev |     at next (/var/www/html/wppconnect-server/node_modules/express/lib/router/route.js:149:13)
1|yarn dev |     at <anonymous> (/var/www/html/wppconnect-server/src/middleware/auth.ts:75:11)
`
And `
36mverbose�[39m:  [main:page] Page Closed
�[32minfo�[39m: 2024-01-29T09:00:07.027Z browserClose


`
```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```
![image](https://github.com/wppconnect-team/wppconnect-server/assets/61248545/3a5a6180-193b-401f-963f-6a4f2b55709d)

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by cgslivre** [comment]
Same with docker:

error: 2024-04-04T17:46:43.222Z Requesting main frame too early! - Error: Requesting main frame too early!
    at assert (/usr/src/wpp-server/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
    at FrameManager.mainFrame (/usr/src/wpp-server/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:213:32)
    at CdpPage.mainFrame (/usr/src/wpp-server/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:414:35)
    at CdpPage.evaluate (/usr/src/wpp-server/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:828:31)
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:99:56
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:24:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:20:12)
    at evaluateAndReturn (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:71:12)
    at Whatsapp.<anonymous> (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:642:82)
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:60:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:41:53)
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:35:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:31:12)
    at HostLayer.isConnected (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/host.layer.js:639:16)
    at statusConnection (/usr/src/wpp-server/dist/middleware/statusConnection.js:28:24)
    at Layer.handle [as handle_request] (/usr/src/wpp-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/wpp-server/node_modules/express/lib/router/route.js:149:13)
    at /usr/src/wpp-server/dist/middleware/auth.js:71:9
(node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

**Comment by leonardols10** [comment]
I resolved this error using another process manager, Google's native "screen", I think pm2 had an error when emulating the web.whatsapp screen via Google

**Comment by gitdedc** [comment]
This is a specific problem / configuration of pm2.  Suggest you check all possible parameters or use screen Linux as alternative (leonardols10's suggest)

Screen: https://www.gnu.org/software/screen/
