### ISSUE TITLE
SendMessege não funciona

### ISSUE THREAD

**Issue by elinardo10** [wppconnect-team/wppconnect-server#1798]
## Description

Tudo funciona, inicia sessão, fico com status "inChat" recebo webhook, mas a dias. não consigo disparar mensagens. Testei todas as versões e nada do whastapp

## Environment

- **Wppconnect-server version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [Ubuntu 20]
- **Node version:** [e.g. Node 8, Node 18]
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes/no
- **config.json:** [Your src/config.json file content]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by gitdedc** [comment]
Elinardo, acabo de testar.
Está tudo operacional.

Reinstale e faça nova build.  Use uma versão wa estável.

Se persistir, poste aqui os logs para que possamos entender melhor.

**Comment by gitdedc** [comment]
Fechando por falta de interação e recursos funcionando
