### ISSUE TITLE
Dockerfile com problemas

### ISSUE THREAD

**Issue by galbuqp** [wppconnect-team/wppconnect-server#1814]
## Description
Quando subimos o container, ele não consegue concluir a instalação, dando um erro de "yarn" não encontrado.

## Environment

- **Wppconnect-server version(s):** LTS [e.g. 2.0.27, 2.2.1]
- **Browser:** N/A [e.g. Chrome 87, Chromium 85]
- **OS:** Ubuntu 22.04 [e.g. OSX 10.13.4, Windows 10]
- **Node version:** N/A [e.g. Node 8, Node 14]
- **WhatsApp version:** N/A [e.g. 2.2126.14]
- **MultiDevice (BETA):** N/A  yes/no
- **config.json:** N/A [Your src/config.json file content]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
[2024-Apr-18 18:34:08.013894] #0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 738B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/node:lts-alpine3.18
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 107B done
#3 DONE 0.0s

#4 [base 1/5] FROM docker.io/library/node:lts-alpine3.18
#4 DONE 0.0s

#5 [base 2/5] WORKDIR /usr/src/wpp-server
#5 DONE 0.1s

#6 [internal] load build context
#6 transferring context: 1.54MB 0.1s done
#6 DONE 0.1s

#7 [base 3/5] COPY package.json ./
#7 DONE 0.2s

#8 [base 4/5] RUN yarn set version stable
#8 0.231 /bin/bash: line 1: yarn: command not found
#8 ERROR: process "/bin/bash -ol pipefail -c yarn set version stable" did not complete successfully: exit code: 127
------
> [base 4/5] RUN yarn set version stable:
0.231 /bin/bash: line 1: yarn: command not found
------
Dockerfile:5
--------------------
3 | ENV NODE_ENV=production PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
4 | COPY package.json ./
5 | >>> RUN yarn set version stable
6 | RUN yarn install --production --pure-lockfile && \
7 | yarn cache clean
--------------------
ERROR: failed to solve: process "/bin/bash -ol pipefail -c yarn set version stable" did not complete successfully: exit code: 127
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by gitdedc** [comment]
You need to open this issue there:
https://github.com/wppconnect-team/wpp-docker

**Comment by galbuqp** [comment]
But why I should open a issue in wpp-docker if the issue is in this repository??
