### ISSUE TITLE
Channel feature rest endpoint

### ISSUE THREAD

**Issue by SajjadAhmad904** [wppconnect-team/wppconnect-server#1822]
1. In Swagger UI, there are no channel REST endpoints such as create, update, or delete features for channels.
2. Does anyone know if the channel feature exists in the REST endpoints?

Thanks,
Sajjad

**Comment by icleitoncosta** [comment]
Olá @SajjadAhmad904 , the cannels is newsletters.

Docs:
https://wppconnect.io/swagger/wppconnect-server/#operation/createNewsletter
