### ISSUE TITLE
Erro ao startar sessao

### ISSUE THREAD

**Issue by jrcassa** [wppconnect-team/wppconnect-server#1827]
Apos encerrar a sessão, ainda continua dizendo que esta conectada na rota startSession. 
Fica CLOSE, INICIALIZANDO e apos CONECTADO mas na rota status-session aponta como desconectada

**Comment by jrcassa** [comment]
Apaguei a pasta referente a instancia na userDataDir e voltou a funcionar, mas como posso automatizar esse processo?

**Comment by renat473** [comment]
utilize a rota close-session para encerrar.

**Comment by jrcassa** [comment]
Essa rota apenas reinicia a sessão, mas não desloga
