### ISSUE TITLE
WhatsApp connectivity issue on server deployment.

### ISSUE THREAD

**Issue by akk-akk** [wppconnect-team/wppconnect-server#1862]
Hi, We are experiencing connectivity issues with WhatsApp after server deployment. When connecting to a local host, WhatsApp works perfectly as expected. I am attaching a screenshot of the message received after scanning the WhatsApp QR code.

![WhatsApp Image 2024-05-21 at 4 19 23 AM](https://github.com/wppconnect-team/wppconnect-server/assets/155035263/ae499a1d-4c7f-433b-be50-eb05effb7da4)

**Comment by gitdedc** [comment]
The problem it's with your phone connection

**Comment by akk-akk** [comment]
@gitdedc 
This issue only comes when trying to connect to the server-deployed app and is fully functional on localhost.

**Comment by akk-akk** [comment]
## These are the logs shown in the terminal (on server).


![1](https://github.com/wppconnect-team/wppconnect-server/assets/155035263/f185aa08-f952-4770-b47e-602a18a5b4c6)
![2](https://github.com/wppconnect-team/wppconnect-server/assets/155035263/467dc22a-6ee6-4326-a54c-e62a5b457279)

**Comment by gitdedc** [comment]
I found the problem.. investigating the solution

**Comment by geovanetworks** [comment]
Facing same issue for last 1 week. 

@gitdedc Is it have anything to do with server location ? For me it is working from Mumbai Server but not working for Singapore Server

**Comment by gitdedc** [comment]
No, the location don't affect.  I'm deploying a new server to test the problem.
I need to simulate to investigate and I couldn't get this error.  I'm trying.  It's some specific problem with ambient.. a little detail.

**Comment by gitdedc** [comment]
I created a new server using ARM Processor, Ubuntu 22.04, NPM, NVM and Chromium (Chrome too and no problem found).  Node 18.18.0.
No problem found.  I created token, read qrcode, stop server, start server.. all works perfectly.
I did all possible tests.  Check if your scenario is like me.
If you have some additional information, please post here, because I can't find any error.
