### ISSUE TITLE
Receiving messages via webhook,

### ISSUE THREAD

**Issue by jejidyan** [wppconnect-team/wppconnect-server#1878]
Hello wppconnect,
I was reading and checking this tool and i found out is so good and useful to me,
But the problem is i didn't get how can i receive different events on webhook, i need every session to have it's own webhook, and if it is possible to configure the webhook and it's triggers actions when i create new WhatsApp session, also I'm asking if it is possible to add pairing CODE instead of QR code, thank you

**Comment by gitdedc** [comment]
Did you set webhook in config.ts?
If yes, did you rebuild?
If yes, please sent here all evidences, information, configuration and logs.
