### ISSUE TITLE
Verificação de phone da erro para grupos

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#188]
Para os endpoints de group, se não passar o isGroup junto na requisição, a função ```statusConnection``` retorna como se fosse erro de ```O número ${num} não existe.```, sendo que no caso seria uma rota de grupo.

Considerando que as rotas de grupos sempre são para grupos, poderia ter um ajuste na função para verificar se tem o ```isGroup``` em rotas que precisa ter, e em rotas de grupo desconsiderar tambem, mesmo que não tenha o isGroup.

**Comment by hbdbim** [comment]
Para quem endpoint ?

**Comment by ghsgabriel** [comment]
Isso ainda ocorre @moskoweb ?
