### ISSUE TITLE
Host Device (nao sei fazer pull

### ISSUE THREAD

**Issue by tomsilva** [wppconnect-team/wppconnect-server#19]
eu nao sei criar um pull aqui mais aqui esta funcionando o metodo host device 

export async function getHostDevice(req, res) {
    try {
        const response = await req.client.getHostDevice();
        return res.status(200).json({
            "phone": response.wid.user,
            "connected": response.connected,
            "platform": response.platform,
            "locales": response.locales,
            "plugged": response.plugged,
            "battery": response.battery,
            "pushname": response.pushname
        });
    } catch (e) {
        Logger.error(e);
        return res.status(400).json({status: "Error", message: "Erro ao recuperar dados do telefone"});
    }
}
-----------------------------------------------------------------------
antes estava assim 
export async function getHostDevice(req, res) {
    try {
        const response = await req.client.getHostDevice();
        return res.status(200).json({
            "phone": response.user,
            "connected": response.connected,
            "plataform": response.plataform,
            "locales": response.locales,
            "plugged": response.plugged,
            "batery": response.batery,
            "pushname": response.pushname
        });
    } catch (e) {
        Logger.error(e);
        return res.status(400).json({status: "Error", message: "Erro ao recuperar dados do telefone"});
    }
}

**Comment by hbdbim** [comment]
Implementado o result, obrigado
