### ISSUE TITLE
Chatwoot Mensagem Apagada

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#191]
Quando você tenta apagar uma mensagem enviada pelo chatwoot para um contato, a mensagem original não é apagada e ainda é enviado outra mensagem para o contato escrito "Esta mensagem foi apagada".

**Comment by ghsgabriel** [comment]
Isso ainda acontece? @moskoweb

**Comment by icleitoncosta** [comment]
Closed without reply

**Comment by douglaspootz** [comment]
Ainda continua, e não apaga  msg !
