### ISSUE TITLE
UnhandledRejection: Request is already handled!

### ISSUE THREAD

**Issue by shoerofi** [wppconnect-team/wppconnect-server#192]
<img width="864" alt="Screen Shot 2021-08-20 at 10 31 22 AM" src="https://user-images.githubusercontent.com/5960940/130175107-0c78a5e4-28fd-42f7-8949-b5def25d7077.png">

Can anybody help me?
Got this error when use start-session api

Thanks

note:
- wppconnect-server v1.1.3
- M1 macOS (Apple Silicon)
- i also add puppeter-core and edit chromium path to get puppeter working on my m1 mac.

**Comment by ghsgabriel** [comment]
@shoerofi , Does this error still happen in the latest version of the server? If yes, how can I reproduce the error?

**Comment by ghsgabriel** [comment]
@shoerofi 

I could not reproduce the error. Try the latest version, if the error occurs, please open a new issue with more information.

WPPConnect Server(s): X.Y.Z
WPPConnect version(s): X.Y.Z
WA-JS version(s): X.Y.Z
WhatsApp version: X.YYYY.ZZ
Browser: Chrome XX / Chromium XX
OS: Windows X / OSX X.Y.Z
Node version: Node XY
MultiDevice (BETA): yes/no

Thanks
