### ISSUE TITLE
config.JS não pega os dados do config.TS

### ISSUE THREAD

**Issue by salomaoparkour** [wppconnect-team/wppconnect-server#1920]
## Description

Fiquei horas tentando entender porque minha secretKey não era alterada, mesmo após mexer no /src/config.ts
A documentação (aqui no gitHub e no README.md) diz claramente que esse é o arquivo que precisa ser editado.

Após pedir ajuda na comunidade um membro indicou que o arquivo a ser alterado na verdade era o /dist/config.JS
Outra pasta, outro arquivo.

Não sabemos o motivo do config.JS não pegar a configuração do config.TS
Mas alterando o config.JS manualmente, funcionou.

Ele passou por isso e eu também.

![image](https://github.com/wppconnect-team/wppconnect-server/assets/890826/234235cd-d9de-4896-b298-ce210528e800)

## Environment

- **Wppconnect-server version(s):** 2.5.1
- **OS:** Ubuntu 22.04

**Comment by renat473** [comment]
Olá,
Não é bug o config.ts somente e utilizado para gerar o build da aplicação e por isso se tornar config.js.

OBS : O config.ts somente e prioridade se você não fizer o build da aplicação.
