### ISSUE TITLE
Add function clearChatsAll

### ISSUE THREAD

**Issue by wenioferraz** [wppconnect-team/wppconnect-server#193]
Possível criar uma função de deletar todas as mensagens que esteja no celular, não deletando o bate papo, apenas as mensagens internas que existe dentro dos chats

ex:
clearChatsAll()

e se possível também colocar uma timestamp onde um chat que teve uma mensagem após ts (timestamp passado como parâmetro) não será apagado.

clearChatsAll(ts?)

**Comment by icleitoncosta** [comment]
Olá @wenioferraz implementado através do commit b818baed226c806eef9e27b04b0cdaabfdc82a56
