### ISSUE TITLE
Estou tendo um erro no linux ubutun

### ISSUE THREAD

**Issue by josuebsilva** [wppconnect-team/wppconnect-server#1933]
chrome_main_delegate.cc(592)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.

**Comment by gitdedc** [comment]
Verifique se o Chrome/Chromium está instalado.
Caso positivo, você está com algum processo que está travando seu browser, impedindo o seu uso. Não é da LIB isso, mas sim processos da sua instância.  Veja o que está rodando em back.
