### ISSUE TITLE
Error when inviting user via private link

### ISSUE THREAD

**Issue by ijro** [wppconnect-team/wppconnect-server#1934]
## Description

When adding a restricted user (endpoint api/<WPPConnect_session>/send-message, I receive the message Can't join this group because the number was restricted it.
In return I receive the invite_code.
So when generating the link https://chat.whatsapp.com/<invite_code> and sending it using the send-message method, the recipient informs that the return message is "group does not exist"

The general group link doesn't work for me, because the user was removed by an administrator.

## Environment

- **Wppconnect-server version:** 2.5.2
- **OS:** 22.04.1-Ubuntu aarch64
- **Node version:** 20.15.0

**Comment by ijro** [comment]
I was told that I should actually send the invite using WPP.chat.sendGroupInviteMessage (WPP-Js).
Is there this possibility via wppconnect-server?

**Comment by renat473** [comment]
you have the option to revoke the group link and send to this user or new users.

about the invite code you can capture it in return and then trigger the send-message via your application code.
