### ISSUE TITLE
How to run the server in a cluster?

### ISSUE THREAD

**Issue by Pankaj-111** [wppconnect-team/wppconnect-server#1943]
Hi, 
I am want to run the server in a cluster, but wandering to setup a directory (userDataDir and token) in S3. 

Could someone please assist with this? I'm looking for advice or any solutions that others have used for setting up a directory structure (userDataDir and token) in S3.

**Comment by PedroShimpa** [comment]
i have the same issue, need to use in a cluster to best performance but i don know how to this

**Comment by YosefAdPro** [comment]
[](https://github.com/wppconnect-team/wpp-docker/tree/main/docker-server-load-balancing
)
[](https://github.com/wppconnect-team/wpp-docker/tree/main/docker-server-load-balancing-redis)

**Comment by gitdedc** [comment]
https://github.com/wppconnect-team/wpp-docker
