### ISSUE TITLE
Feature to run server in a multi node cluster 

### ISSUE THREAD

**Issue by Pankaj-111** [wppconnect-team/wppconnect-server#1995]
**I want to run the server in production but in a multi-node cluster**
I have tried the steps given in your youtube video, but not able to run server in cluster where nodes are in different machines. 
**Describe the solution you'd like**
Please provide a solution so that I can run my server in cluster where the nodes are in different machines.

**Comment by renat473** [comment]
Hello, this project does not include operation in H.A.

To implement this functionality, you need to configure settings directly on your server.

**Comment by Pankaj-111** [comment]
Thanks for response.
can you please guide how to configure?
