### ISSUE TITLE
QRCode com timeout

### ISSUE THREAD

**Issue by kleber-nascimento** [wppconnect-team/wppconnect-server#2006]
## QRCode é gerado ao executar a aplicação mas retorna erro!

Olá!
Executei o main desse projeto [zapbot](https://github.com/tonylampada/zapbot) e o wpp gera o qrcode, porém, quando faço a leitura pelo whatsapp, retorna erro "Não foi possível conectar o dispositivo! Tente novamente mais tarde.!

## Environment

- **Wppconnect-server:** ultima versão, acabei de fazer o pull;
- **Browser:** Version 128.0.6613.113 (Official Build) (64-bit);
- **OS:** Ubuntu 24.04.1 LTS: 
- **WhatsApp version:** 2.24.16.76

## Steps to Reproduce

1. roda python app/main.py
2. abre o arquivo qrcode criado (qrcode.png)
3. faz a leitura do qrcode no whatsapp pelo Android.

Alguma sugestão do que pode estar acontecendo?

**Comment by renat473** [comment]
O projeto zapbot não pertencesse ao repositorio do wppconnect, estarei encerrado a issues.
