### ISSUE TITLE
swagger.json typed returns and dto

### ISSUE THREAD

**Issue by TheTrigger** [wppconnect-team/wppconnect-server#2012]
## Description

The `swagger.json` file is missing declarations for _return types_ and comprehensive references for _requestBody_ objects, resulting in incomplete code generation when using tools like NSwag. Without these specifications, generating typed clients (e.g., C#) from the OpenAPI definition leads to a lack of return types and DTOs.

## Environment

- **WPPConnect API Rest**: 2.0.0
- **Tool used for generation**: NSwag/NSwagStudio/Refitter

## Steps to Reproduce

1. Obtain the swagger.json from the WppConnect server
2. Use NSwag/NSwagStudio/Refitter or a similar tool to generate a client from the OpenAPI definition
3. Observe the missing return types and body objects in the generated client code

## Expected vs Actual Behavior

**Expected**: The generated client should include all necessary return types and DTOs
**Actual**: The generated client lacks these return types and DTOs due to missing declarations in the swagger.json file

## Example

```diff
{
  "/api/....": {
    "get": {
      "tags": ["Messages"],
      "description": "",
     "requestBody": {
       "content": {
         "application/json": {
           "schema": {
+             "$ref": "#/components/schemas/ExampleBodyType"
            }
          }
        }
     },
      "parameters": [ "--omitted--" ],
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
+                "$ref": "#/components/schemas/ExampleReturnType"
              }
            }
          }
        },
        "401": {
          "description": "Unauthorized"
        }
      },
    }
  },
}
```

## Generated code

**Example of Missing requestBody Reference**: The default name _Body*_ is generated due to missing references in requestBody, impacting the usability of the API in typed languages like C#.

```csharp
public virtual Task ArchiveChatAsync(string session, Body41 body)
{
    return ArchiveChatAsync(session, body, System.Threading.CancellationToken.None);
}
```

**Example of Missing Return Types**: No return types are explicitly declared, which hinders the data in the generated client

```csharp
/// <returns>OK</returns>
/// <exception cref="ApiException">A server side error occurred.</exception>
public Task GetMessagesAsync( /*omitted*/ )
{
    // omitted
    return;
}
```

should be 

```csharp
public Task<Messages[]> GetMessagesAsync()
```

**Comment by renat473** [comment]
hello this is not considered a bug
because swagger is only used as a form of documentation
We always recommend that the swagger file be imported into postman or any rest api testing tool
