### ISSUE TITLE
How to use send file?

### ISSUE THREAD

**Issue by jaygent** [wppconnect-team/wppconnect-server#2014]
When send file, I have error message error: 2024-09-09T09:26:00.269Z Error trying to download the file.
Postman response 
{
    "status": "success",
    "response": [
        {
            "ack": -1,
            "id": "true_39150@g.us_3EB0B38EEED781E250AD0B_48512@c.us",
            "sendMsgResult": {
                "messageSendResult": "ERROR_UNKNOWN"
            }
        }
    ],
    "mapper": "return"
}

**Comment by jaygent** [comment]
.

**Comment by renat473** [comment]
link document rest api : 

https://wppconnect.io/swagger/wppconnect-server/#tag/Messages/paths/~1api~1%7Bsession%7D~1send-file/post
