### ISSUE TITLE
How to send a message to a broadcast list

### ISSUE THREAD

**Issue by juanma09** [wppconnect-team/wppconnect-server#2020]
I am trying to send a message to a broadcast group using /send-message method, but I am not sure how to do that with a broadcast group. It seems that a broadcast is not considered a group nor a contact. This are the params I am sending to the method:
url: http://localhost:8080/api/testsession/send-message
params:
{
  "phone": "id@broadcast",
  "isGroup": true,
  "isNewsletter": false,
  "message": "Test message"
}

It sends a success message when the api is sent. But it does not send the message.
Does anyone know if there is some kind of "isBroadcast" parameter when sending a message?

**Comment by renat473** [comment]
Hello, we do not support broadcast.

**Comment by Saifallak** [comment]
You can't send to broadcast from whatsapp web, only from mobile, also they must register your number to receive the message
