### ISSUE TITLE
Not able to generate QR code

### ISSUE THREAD

**Issue by SnehaKalsaraBs** [wppconnect-team/wppconnect-server#2022]
I have deployed this repo on our stage server initially it was working but now it is not working. I am not able to generate QR code start-session api is going infinite. in my local i took pull and after npm run dev there was a code to install new dependencies in console. after i done that it started working. so can you please provide that npm code to install new dependencies?

**Comment by renat473** [comment]
Install the operating system dependencies and also the Google Chrome browser.

Note: use node18 or version 18 and remove old sessions and create a new one.
