### ISSUE TITLE
swagger.json return types

### ISSUE THREAD

**Issue by TheTrigger** [wppconnect-team/wppconnect-server#2023]
Hello, I need to generate a rest client for C# (via tools like Nswag) and I could do it starting from `swagger.json`. But there is a problem, in the document there are no **return types**

while I noticed that in an old file <https://raw.githubusercontent.com/wppconnect-team/wppconnect-server/main/src/swagger-backup.json> the types are present..

How can we restore the definition correctly?

**Comment by icleitoncosta** [comment]
Hello, in this case, it is necessary to document all types in the functions. When I created the Swagger, I had to do it quickly, as this backup had many errors in the function calls, and to simplify the documentation, I added it directly above the function using swagger-autogen.

Soon, I will try to add all the necessary types.

**Comment by TheTrigger** [comment]
Could you please provide a guide on how to do it? then i could help
