### ISSUE TITLE
Not able to send  mentioned

### ISSUE THREAD

**Issue by Pankaj-111** [wppconnect-team/wppconnect-server#2060]
## Send Mentioned API not working

I am trying use http://localhost:21465/api/DEV-WPS-919910062638/send-mentioned to send mentioned message in group, it sends normal text message in the group, but not send any mentioned

## Steps to Reproduce

1. http://localhost:21465/api/DEV-WPS-919910062638/send-mentioned
2. Payload :
{
  "phone": "120363319753671798@g.us",
  "isGroup": true,
  "message": "Testing mentioned here",
  "mentioned": [
    "919711059874@c.us"
  ]
}
3. Check the group 

You will see the message "Testing mentioned here" but no mention 

## ![image](https://github.com/user-attachments/assets/e3eb5391-71eb-458b-90b0-d3b1f79abe80)

Add any other context about the problem here. If applicable, add screenshots to help explain.

## Enviroment
1. WPPConnect-Server version: 2.6.0
2. Node Version : v20.17.0

**Comment by icleitoncosta** [comment]
Hi @Pankaj-111, the text not show the @ mentioned, but mention the person. 
For teste correctly, close the chat, and send message, do you can see you are mentioned.

For mention is not necessary see mention in text

**Comment by Pankaj-111** [comment]
Yes agree, but we must see the Message and @Person Name.
That is the bug with API.
