### ISSUE TITLE
Qr code not generating using start session api

### ISSUE THREAD

**Issue by SnehaKalsaraBs** [wppconnect-team/wppconnect-server#2061]
error:    [test2:client] Auto Close Called
error: 2024-10-30T06:12:27.541Z Auto Close Called

getting this error in log while calling api using token.

**Comment by weversong2** [comment]
estou com mesmo problema

**Comment by joaofjunior** [comment]
Estou com o mesmo problema, e ao força a conexão recebo erro "error:    [_votacao01:browser] Failed to launch the browser process! undefined"

**Comment by amir200xven** [comment]
I have the same problem

**Comment by amir200xven** [comment]
The issue is that the process stays in the INITIALIZING phase and never displays the QR code. 
This might be due to an update in WhatsApp Web.

**Comment by DiegoCiara** [comment]
I have the same problem

**Comment by renat473** [comment]
QR Code guys, I needed to go to the node_modules/@wppconnect-team/wppconnect/dist/config/create-config.js file and change the version to 2.3000.10177x for it to work.
