### ISSUE TITLE
[URGENT] QR CODE not generating

### ISSUE THREAD

**Issue by syahir10syahir** [wppconnect-team/wppconnect-server#2066]
Hi,
we are unable to generate the QR code - we have tried with fresh installation also and having the same - it keep saying the status " "status": "INITIALIZING","

here is the response
![image](https://github.com/user-attachments/assets/0da577db-e1f8-4522-92fa-e1a7f728df60)

**Comment by Pankaj-111** [comment]
I have the issue, I have tried to delete all the cache, but no luck.

**Comment by amir200xven** [comment]
Hi,

I had the same issue with generating the QR code and getting the status `"status": "INITIALIZING"`. I resolved it by updating to the latest version (`v2.8.1`). I recommend updating your `wppconnect-server` installation to the latest version, as this fixed the problem for me.

Hope this helps!

Best,
Amir

**Comment by renat473** [comment]
you must update the project and install the Chrome browser.

note: you may need to change your WhatsApp web version to the latest one.

**Comment by syahir10syahir** [comment]
@renat473 @amir200xven  thanks - it fixed it after i upgraded, but we cant create group - are you also having the same issue? 

here is the logs - 
<img width="946" alt="image" src="https://github.com/user-attachments/assets/8faf9c3f-ea5e-4920-923b-59773ba7615b">

**Comment by Nesta-Maulana** [comment]
Hello sir @renat473 @syahir10syahir can you tell me how to update whatsapp web and install the chrome browser? 
im use the docker  like this :
`# FROM node:18-alpine3.19 as base
FROM node:18-alpine as base
WORKDIR /usr/src/wpp-server
ENV NODE_ENV=production PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
COPY package.json ./
RUN apk update && \
    apk add --no-cache \
    vips-dev \
    fftw-dev \
    gcc \
    g++ \
    make \
    libc6-compat \
    && rm -rf /var/cache/apk/*
RUN yarn install --production --pure-lockfile && \
    yarn add sharp --ignore-engines && \
    yarn cache clean

FROM base as build
WORKDIR /usr/src/wpp-server
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
COPY package.json  ./
RUN yarn install --production=false --pure-lockfile
RUN yarn cache clean
COPY . .
RUN yarn build

FROM base
RUN apk update && \
    apk add --no-cache \
    vips-dev \
    fftw-dev \
    gcc \
    g++ \
    make \
    libc6-compat \
    && rm -rf /var/cache/apk/*
WORKDIR /usr/src/wpp-server/
RUN apk add --no-cache chromium
RUN yarn cache clean
COPY . .
COPY --from=build /usr/src/wpp-server/ /usr/src/wpp-server/
EXPOSE 21465
ENTRYPOINT ["node", "dist/server.js"]
`

and docker-compose like this :
version: "3"

services:
  wppconnect:
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - "21465:21465"

volumes:
  wppconnect_tokens: {}      
  
  please help me
