### ISSUE TITLE
Mentioned API not working properly

### ISSUE THREAD

**Issue by Pankaj-111** [wppconnect-team/wppconnect-server#2068]
## API
http://localhost:21465/api/SESSION_NAME/send-mentioned

## Environment
WPPConnect-Server version: 2.6.0
Node Version : v20.17.0

## Steps to Reproduce

http://localhost:21465/api/SESSION_NAME/send-mentioned
Payload :
{
"phone": "[120363319753671798@g.us](mailto:120363319753671798@g.us)",
"isGroup": true,
"message": "Testing mentioned here",
"mentioned": [
"[919711059874@c.us](mailto:919711059874@c.us)"
]
}
Expected Result
 Message : Testing mentioned here @MemberName which belongs to the ID : [919711059874@c.us]
Actual Result : See the screenshot of the whatsapp group
![image](https://github.com/user-attachments/assets/9834ef7b-cc27-4fc4-94be-7752d62247b7)

**Comment by renat473** [comment]
To mention, you only need the telephone number

**Comment by Pankaj-111** [comment]
> To mention, you only need the telephone number

Not working, Please check it before closing the issue.
