### ISSUE TITLE
[Blocker]-After calling start-session-QR Code not Generating 

### ISSUE THREAD

**Issue by Pankaj-111** [wppconnect-team/wppconnect-server#2070]
## Description
After calling /start-session API QR Code not Generating 

## Environment
WPPConnect-Server version: 2.6.0
Node Version : v20.17.0

## Steps to Reproduce

1. Call the API **/start-session**
**Response :** {
    "status": "CLOSED",
    "message": "QRCode is not available...",
    "session": "PROD-WPS-919311148076"
}
2. second Call the API **/start-session**
 {
    "status": "INITIALIZING",
    "qrcode": null,
    "version": "2.5.2",
    "session": "PROD-WPS-919311148076"
}
3. now Call the API **/qrcode-session** 
**Every time the same Response :** {
    "status": "INITIALIZING",
    "message": "QRCode is not available...",
    "session": "PROD-WPS-919311148076"
}
The session is never initialized

**Comment by amir200xven** [comment]
Hi,

I had the same issue with generating the QR code and getting the status `"status": "INITIALIZING"`. I resolved it by updating to the latest version (`v2.8.1`). I recommend updating your `wppconnect-server` installation to the latest version, as this fixed the problem for me.

Hope this helps!

Best,
Amir

**Comment by renat473** [comment]
Update project version and install google chrome

**Comment by Pankaj-111** [comment]
This is not a solution, I have up updated to latest version, it again stops generating the QR code.

**Comment by icleitoncosta** [comment]
> This is not a solution, I have up updated to latest version, it again stops generating the QR code.

I will test and fix it (if necessary)

**Comment by Pankaj-111** [comment]
Thank you for your response. I believe this issue is quite common for many users, so I kindly ask that you take it seriously.
