### ISSUE TITLE
Issue with /api/{session}/group-pic API Endpoint - 502 Bad Gateway Error

### ISSUE THREAD

**Issue by amir200xven** [wppconnect-team/wppconnect-server#2074]
**Title**: Issue with `/api/{session}/group-pic` API Endpoint - 502 Bad Gateway Error

**Description**:  
Hello,

I've been using the `wppconnect-server` library (version `v2.8.1 Latest`) and have encountered an issue with the `/api/{session}/group-pic` endpoint. When calling this API, I receive a `502 Bad Gateway` error with the following response:

```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

**Comment by renat473** [comment]
Problem not found

used body json : 

{
  "groupId": "idgroup",
  "path": "image-url"
}
