### ISSUE TITLE
Rota Close Nao funciona 

### ISSUE THREAD

**Issue by lepokoloko** [wppconnect-team/wppconnect-server#24]
Caso ocorra de nao ler o qrcode e a funcao auto close ser chamada, não é possivel chamar a rota close session, ela fica rodando sem resposta e não fecha o navegador.

**Comment by hbdbim** [comment]
Quando não le o qrCode o server fecha automaticamente o navegador.
testando também chamar a rota close.
Se a rota close é chamado enquanto o servidor esta esperando ler o qrCode o metodo retorna erro pois entende que a session ainda não esta inicidada.
Se a rota close é chamada apos o navegador ja estar fechado é retornado erro pois a session ja esta encerrada.
da5ecec
