### ISSUE TITLE
Cerrar função do obtener QRCode despues de varios intentos fallidos

### ISSUE THREAD

**Issue by kenirios** [wppconnect-team/wppconnect-server#25]
Que desde o config.json se pode configurar os números de intentos falidos antes de cerrar o processo de obtener do qrcode.

**Comment by moskoweb** [comment]
Veja se não esgotou a sua memoria ram do computador ou servidor, se esgota ele não consegue subir a instancia.

**Comment by hbdbim** [comment]
Adicionado opção de configurar o create.
da5ecec
