### ISSUE TITLE
Error: no open browser no linux

### ISSUE THREAD

**Issue by infsolution** [wppconnect-team/wppconnect-server#28]
Estou tentando rodar o session-start mas o server sempre retorna esse erro dizendo que não abriu o browser, testei no Windows tanto com npm run dev quanto com build e funciona tranquilo envia mensagem ok, no ubuntu da esse erro
![issuigit](https://user-images.githubusercontent.com/13574950/120711224-7fe7c900-c495-11eb-8566-39f8392b5f75.png)

**Comment by hbdbim** [comment]
Não foi encontrado o navegador de internet, nesse caso vc precisa instalar o chrome
