### ISSUE TITLE
fechar sessoes do whatsapp

### ISSUE THREAD

**Issue by tomsilva** [wppconnect-team/wppconnect-server#29]
tenho 2 problemas
1 - fechar a sessao pelo metodo close-session
2 - fechar a sessao pelo telefone diretamente.

1 - cuando chamo o metodo para fechar a sessao a mesa fecha  no server mais nao finalzia no telefone, dai cuando dou um start-session automaticamente se reconecta.

2 - se fecho a sessao somente pelo telefone nao fecha a sessao na api, respondendo no check-session sempre true conected.....

**Comment by hbdbim** [comment]
1 -  o metodo close-session só fecha o browser e encerra a session, o metodo para desconectar do whats é o **logout**.
2 - corrigido.  da5ecec06dc13121f450bbc7350495a7aab9f1f8
