### ISSUE TITLE
Erro ao iniciar

### ISSUE THREAD

**Issue by renat473** [wppconnect-team/wppconnect-server#3]
Olá,

Quando fui tentar iniciar a aplicação apresentou o erro abaixo.

![image](https://user-images.githubusercontent.com/1757167/113883213-5875c800-9794-11eb-9322-51fb81d071f6.png)

**Comment by kingaspx** [comment]
Olá, pra rodar o projeto, vc precisa usar o `yarn dev`

**Comment by renat473** [comment]
Consegui iniciar a aplicação e abrir uma nova issue para o problema de autenticar ao server.
