### ISSUE TITLE
na rota send-file-base64 retornar os dados da mensagem enviada

### ISSUE THREAD

**Issue by brunopiaca2** [wppconnect-team/wppconnect-server#34]
Ao enviar uma mensagem de texto usando o /send-message retorna todos os dados da mensagem enviada, quando é um arquivo via base64 somente é retornado como enviado com sucesso.

**Comment by ghsgabriel** [comment]
Oi @brunopiaca2 , isso ainda está da mesma forma?

**Comment by icleitoncosta** [comment]
Atualmente ele retorna o ID da mensagem.
Att,
