### ISSUE TITLE
Problema a Ler o QRcode

### ISSUE THREAD

**Issue by dilsoncosta** [wppconnect-team/wppconnect-server#341]
Boa noite, a ler o qrcode pela primeira vez me retorna esse erro abaixo , quando faço a leitura pela segunda vez a leitura é feita com sucesso

![a](https://user-images.githubusercontent.com/28371004/140237533-ca01bbb1-3028-4748-adae-29b31fb29bb8.png)

**Comment by renat473** [comment]
Olá @dilsoncosta ,

Poderia dizer quais são as configurações do ambiente e em qual momento esta ocorrendo ?

**Comment by ghsgabriel** [comment]
Isso foi corrigido na versão 1.1.18
