### ISSUE TITLE
Tokens não estão sendo salvos no BETA

### ISSUE THREAD

**Issue by RaczoOBY** [wppconnect-team/wppconnect-server#342]
Utilizando a versão BETA  mesmo com as linhas abaixo no config.json nada é salvo na pasta tokens, apenas a pasta "userDataDirminhasession" com alguns arquivos é criada

"startAllSession": true,
"tokenStoreType": "file",
"customUserDataDir":"./userDataDir"

Além disso sempre que o nodemon restarta o servidor a sessão é perdida

**Comment by hbdbim** [comment]
Na versão beta a lib não recupera o token, sendo assim não salva o token. 
A sessão do whats teoricamente é recuperada dessa pasta userDataDir.

**Comment by RaczoOBY** [comment]
Ao inserir o "customUserDataDir" no config.json vi a pasta sendo criada com os arquivos.
Consegui logar e esperei uns 30 min para sincronizar mas sempre que o nodemon reinicia o server, a sessão cai sendo necessário escanear o QR Code novamente

Tem alguma luz de onde posso estar errando?

**Comment by RaczoOBY** [comment]
> Na versão beta a lib não recupera o token, sendo assim não salva o token. A sessão do whats teoricamente é recuperada dessa pasta userDataDir.

Ao inserir o "customUserDataDir" no config.json vi a pasta sendo criada com os arquivos.
Consegui logar e esperei uns 30 min para sincronizar mas sempre que o nodemon reinicia o server, a sessão cai sendo necessário escanear o QR Code novamente

Tem alguma luz de onde posso estar errando?

**Comment by ghsgabriel** [comment]
Eu havia feito um ajuste na lib para funcionar o salvamento de token mesmo quando multi device, para funções do server como startAllSessions, webhook e chatwoot funcionacem normalmente.

Infelizemente parece que parou de funcionar novamente, vou tentar ver o motivo até fds retorno

**Comment by RaczoOBY** [comment]
> Eu havia feito um ajuste na lib para funcionar o salvamento de token mesmo quando multi device, para funções do server como startAllSessions, webhook e chatwoot funcionacem normalmente.
> 
> Infelizemente parece que parou de funcionar novamente, vou tentar ver o motivo até fds retorno


Testando melhor a conexão se mantém e consigo utilizar normalmente abrindo a rota start-session, mas a sessão  não sobe junto com o servidor mesmo com startAllSession: true

**Comment by RaczoOBY** [comment]
@ghsgabriel @hbdbim 
Consegui inserir uma gambiarra para iniciar junto com o startAllSessions (necessário inserir o import path from 'path'; no inicio)

inserindo essa parte abaixo dentro da função, (provavelmente não é a melhor solução mas aparentemente funcionou),
`
if (req.serverOptions.customUserDataDir) {
    const { customUserDataDir } = req.serverOptions;
    const dir = path.resolve(customUserDataDir, '..');
    const files = fs.readdirSync(dir);
    const prefix = customUserDataDir.split('/')[customUserDataDir.split('/').length - 1];
    files.map(async (file) => {
      const session = file.replace(prefix, '');
      const util = new CreateSessionUtil();
      await util.opendata(req, session);
    });
  }
`

**Comment by RaczoOBY** [comment]
@ghsgabriel @hbdbim
Consegui inserir uma gambiarra para iniciar junto com o startAllSessions (necessário inserir o import path from 'path'; no inicio)

inserindo essa parte abaixo dentro da função, (provavelmente não é a melhor solução mas aparentemente funcionou),

if (req.serverOptions.customUserDataDir) {
    const { customUserDataDir } = req.serverOptions;
    const dir = path.resolve(customUserDataDir, '..');
    const files = fs.readdirSync(dir);
    const prefix = customUserDataDir.split('/')[customUserDataDir.split('/').length - 1];
    files.map(async (file) => {
      const session = file.replace(prefix, '');
      const util = new CreateSessionUtil();
      await util.opendata(req, session);
    });
  }

**Comment by RaczoOBY** [comment]
![image](https://user-images.githubusercontent.com/36315319/140377924-e6ce981d-1fd9-467f-a74a-6f8425aaff65.png)

**Comment by ghsgabriel** [comment]
Essa questão do token já foi resolvido na lib, porém está na versão nightly ainda. Perdão, achei q já tinha entrado na 1.9.4.

![image](https://user-images.githubusercontent.com/35141093/140394629-40e7d20f-81ef-45df-b3ee-3f920d63c288.png)

**Comment by edgardmessias** [comment]
Sábado vou dar mais uma mexida na LIB e lançar nova release
