### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by danmarris12** [wppconnect-team/wppconnect-server#345]
import config from './config.json';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)

**Comment by ghsgabriel** [comment]
@danmarris12 , esse erro continua acontecendo na ultima versão do server? Se sim, como eu posso reproduzir o erro?

**Comment by ghsgabriel** [comment]
@danmarris12 

I could not reproduce the error. Try the latest version, if the error occurs, please open a new issue with more information.

WPPConnect Server(s): X.Y.Z
WPPConnect version(s): X.Y.Z
WA-JS version(s): X.Y.Z
WhatsApp version: X.YYYY.ZZ
Browser: Chrome XX / Chromium XX
OS: Windows X / OSX X.Y.Z
Node version: Node XY
MultiDevice (BETA): yes/no

Thanks
