### ISSUE TITLE
API send-link-preview não tem opção para enviar para grupo

### ISSUE THREAD

**Issue by murilomontalvao** [wppconnect-team/wppconnect-server#348]
Boa tarde pessoal!

Em versões anteriores do server existia a variável **isGroup**, ao qual se você passasse **true** no parâmetro, enviava o link preview para um grupo. 
Na ultima versão a variável foi retirada da função.
O teste foi executado utilizando o beta-multidevice.

**Comment by ghsgabriel** [comment]
Oi @murilomontalvao , qual função? Esse erro continua acontecendo na ultima versão do server? Se sim, como eu posso reproduzir o erro?

**Comment by ghsgabriel** [comment]
Oi @murilomontalvao , Fiz um teste e está funcionando o isGroup na rota send-link-preview tanto no leacy quanto no Multi Device
