### ISSUE TITLE
API send-image retorna status 500 mesmo com sucesso no envio

### ISSUE THREAD

**Issue by murilomontalvao** [wppconnect-team/wppconnect-server#349]
Testei o envio para grupos, setando a variável **isGroup = true**
O envio da imagem ocorre com sucesso, entretanto o status retornado = 500.
O teste foi feito utilizando beta-multidevice.

**Comment by ghsgabriel** [comment]
Oi @murilomontalvao , qual função?, esse erro continua acontecendo na ultima versão do server? Se sim, como eu posso reproduzir o erro?

**Comment by ghsgabriel** [comment]
Boa tarde.

Notei que a função teve um bug fiz após essa issue.

Fiz testes e não consegui reproduzir o problema.
