### ISSUE TITLE
API group-info-from-invite-link não está funcionando com beta-multidevice

### ISSUE THREAD

**Issue by murilomontalvao** [wppconnect-team/wppconnect-server#350]
O endpoint do wppconnect-server **group-info-from-invite-link** não está funcionando se estiver utilizando **beta-multidevice**

**Comment by ghsgabriel** [comment]
Oi @murilomontalvao , esse erro continua acontecendo na ultima versão do server? Se sim, como eu posso reproduzir o erro?

**Comment by ghsgabriel** [comment]
Boa tarde.

Testei com o beta-multidevice na ultima versão do server e o endpoint está funcionando.
