### ISSUE TITLE
Whatsapp started blocking the account 

### ISSUE THREAD

**Issue by danmarris12** [wppconnect-team/wppconnect-server#364]
Do not. know how but whatsapp started detecting this script and blocking the account ,plz check and work on the exceptions .

**Comment by edgardmessias** [comment]
@danmarris12 , could you provide more information?

**Comment by danmarris12** [comment]
After a QR code scan from wppconnect, WhatsApp gets blocked suddenly,mainly on iPhone devices.

**Comment by ykose1982** [comment]
clear your data, change your ip. it works fine
