### ISSUE TITLE
Limite de Memoria

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#38]
Desde a última atualização, começou a dar o seguinte erro no painel, mesmo tendo mais que o dobro de memoria ram sobrando ainda:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**Comment by tomsilva** [comment]
up

**Comment by hbdbim** [comment]
Pode descrever melhor o evento?
Isso acontece em alguma situação específica ?

Em ter, 29 de jun de 2021 22:58, Weverton Carlos Solva <
***@***.***> escreveu:

**Comment by bgastaldi** [comment]
@hbdbim parece que começou a ficar recorrente

**Comment by ghsgabriel** [comment]
Isso ainda acontece? @moskoweb @tomsilva ?

**Comment by edgardmessias** [comment]
Isso é um erro recorrente, está difícil descobrir em qual parte do sistema que está registrando mais eventos do que deveria, mas existem N maneiras de incrementar esse valor
