### ISSUE TITLE
ERRO DE TOKEN

### ISSUE THREAD

**Issue by renat473** [wppconnect-team/wppconnect-server#4]
Ao tentar iniciar a sessão do token e informado que é invalido

**Comment by kingaspx** [comment]
Como vc está chamando a rota? E como vc gerou esse token?

**Comment by renat473** [comment]
Percebi que primeiro para realizar o acesso e necessário gerar o session através dos comandos curl da API e após este procedimento consegui realizar o acesso ao portal frontend.
