### ISSUE TITLE
UnhandledRejection: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by denidarmayana** [wppconnect-team/wppconnect-server#424]
UnhandledRejection: Navigation timeout of 30000 ms exceeded

how to solve this error, for digitalocean server

**Comment by ghsgabriel** [comment]
Hi @denidarmayana , Does this error still happen in the latest version of the server? If yes, how can I reproduce the error?

**Comment by ghsgabriel** [comment]
@denidarmayana 

I could not reproduce the error. Try the latest version, if the error occurs, please open a new issue with more information.

WPPConnect Server(s): X.Y.Z
WPPConnect version(s): X.Y.Z
WA-JS version(s): X.Y.Z
WhatsApp version: X.YYYY.ZZ
Browser: Chrome XX / Chromium XX
OS: Windows X / OSX X.Y.Z
Node version: Node XY
MultiDevice (BETA): yes/no


And steps to reproduce the error. 

Thanks
