### ISSUE TITLE
How can we run this on Heroku server?

### ISSUE THREAD

**Issue by dubeychandan996** [wppconnect-team/wppconnect-server#445]
Is there any documentation for this. I am getting errors on Heroku.

**Comment by ghsgabriel** [comment]
@dubeychandan996 , We don't have documentation for running on Heroku. What error has occurred?

**Comment by ghsgabriel** [comment]
@dubeychandan996 

We recommend not using heroku in the free version, as the service will stop when there are no requests for a period of time.

In free mode, if there are no requests, the service stops working and only returns when it returns.

Wppconnect depends on the service being active to fetch new messages.
