### ISSUE TITLE
chat-is-online API is down

### ISSUE THREAD

**Issue by dubeychandan996** [wppconnect-team/wppconnect-server#449]
Can you please check I am getting error only on this endpoint.

**Comment by ghsgabriel** [comment]
What error are you getting and when using which function?

What is your WPPConnect Server version and how can I reproduce the error?

**Comment by ghsgabriel** [comment]
I just tested and the endpoint is working.

If it happens, open another issue detailing the environment, what is the error and as an error for you, the environment, what is the error and as an error for you

:D

**Comment by dubeychandan996** [comment]
![image](https://user-images.githubusercontent.com/6350242/149792726-ea6c3db7-01bb-40b3-b6a0-29b7b1b9dd9e.png)
All the time I am getting response : false even when that user is online.

**Comment by ghsgabriel** [comment]
@dubeychandan996 

I couldn't reproduce the error, here it works normally (returns online true)

As I said above, please open a new issue answering the entire opening questionnaire, to help me debug
