### ISSUE TITLE
profile-pic não atualiza o eurl

### ISSUE THREAD

**Issue by riquedev** [wppconnect-team/wppconnect-server#469]
Após a troca bem sucedida pela rota "profile-pic" a nova imagem não é obtida, recebo apenas o eurl da imagem anterior.
Um adendo é que se eu faço a troca pelo aplicativo o eurl é atualizado normalmente.

**Comment by ghsgabriel** [comment]
Oi @riquedev , não entendi muito bem, pode me ajudar?

O que você espera que ocorra ao usar a rota "profile-pic", qual é o erro em si e como eu posso reproduzi-lo?

Além disso, qual a versão do server que está usando?

**Comment by riquedev** [comment]
> Oi @riquedev , não entendi muito bem, pode me ajudar?
> 
> O que você espera que ocorra ao usar a rota "profile-pic", qual é o erro em si e como eu posso reproduzi-lo?
> 
> Além disso, qual a versão do server que está usando?

Opa @ghsgabriel!
Estou usando a última versão disponibilizada, eu esperava receber a "eurl" atualizada.
Oque ocorre é que após a troca bem sucedida, quando tento receber novamente a imagem utilizada ele me retorna a antiga. Estou usando um número Business e com todas configurações públicas (status, foto, etc...).

**Comment by ghsgabriel** [comment]
@riquedev , como você realiza a troca?

Testei aqui na última versão do server, via dispositivo Normal/Business, no modo MD/Legacy, trocando pelo dispositivo mesmo, e a rota "profile-pic", após a troca me retornou sempre a imagem correta.

**Comment by riquedev** [comment]
> @riquedev , como você realiza a troca?
> 
> Testei aqui na última versão do server, via dispositivo Normal/Business, no modo MD/Legacy, trocando pelo dispositivo mesmo, e a rota "profile-pic", após a troca me retornou sempre a imagem correta.

Eu faço o upload normal pelo server e ele retorna a confirmação de sucesso (e a troca é realizada normalmente inclusive aparece no aplicativo), eu só não recebo a eurl certa.
Logo mais vou testar com outro dispositivo e tentar descobrir oque pode ter causado isso.

**Comment by ghsgabriel** [comment]
@riquedev , você pode tentar fazer testes na ultima versão, e alternando entre MD/Legacy.

**Comment by riquedev** [comment]
Após o último update, não tive mais problemas.
