### ISSUE TITLE
Alguns destinos não chegam mensagem se disparado para vários contatos

### ISSUE THREAD

**Issue by OcidentalInfo** [wppconnect-team/wppconnect-server#473]
Quando tendo enviar mensagens automáticas com "send-message" para uma lista de contatos, onde tenho de disparar um de cada vez pois cada mensagem tem dados adicionais referente ao contato, observei que pelo menos uma mensagem de um contato NÃO chega no seu WhatsApp, porém, o "send-message" retorna o status deste com "success" também, como os outros.

Fiz este teste com uma lista de array com 4 elementos (itens) de contato usando o "for" para iterar e normalmente uma (1) mensagem não chega.

Obs.: Não estou usando "Multi Device", não uso o Front somente o "wppconnect-server" e não uso como Chat mas para disparar mensagens personalizadas para diversos contatos.

**Comment by ghsgabriel** [comment]
@OcidentalInfo , poderia me enviar exemplos de contato que não envia, para fazer uns teste, por favor?

Obrigado.

**Comment by OcidentalInfo** [comment]
const contatos = [
      {
        "phone": "559888186652",
        "message": "Anderson testando mensagem.",
        "isGroup": false
      },
      {
        "phone": "559891304380",
        "message": "*Teste*\nAna.",
        "isGroup": false
      },
      {
        "phone": "559891624380",
        "message": "Teste de *mensagem* para\n_Paulo_.",
        "isGroup": false
      },
      {
        "phone": "559889206536",
        "message": "*Mensagem para*\nAny.",
        "isGroup": false
      }
    ];

*Obs: Estes contatos são reais. Favor usar somente para os testes solicitados. Logo que concluir me avise aqui para eu modificar os números para fictícios. Esta comunidade crescerá muito com ética, compromisso e responsabilidade. Obrigado.

**Comment by ghsgabriel** [comment]
> ```
> const contatos = [
>   {
>     "phone": "<apagado>",
>     "message": "Anderson testando mensagem.",
>     "isGroup": false
>   },
>   {
>     "phone": "<apagado>",
>     "message": "*Teste*\nAna.",
>     "isGroup": false
>   },
>   {
>     "phone": "<apagado>",
>     "message": "Teste de *mensagem* para\n_Paulo_.",
>     "isGroup": false
>   },
>   {
>     "phone": "<apagado>",
>     "message": "*Mensagem para*\nAny.",
>     "isGroup": false
>   }
> ];
> ```
> 
> *Obs: Estes contatos são reais. Favor usar somente para os testes solicitados. Logo que concluir me avise aqui para eu modificar os números para fictícios. Esta comunidade crescerá muito com ética, compromisso e responsabilidade. Obrigado.

Oi @OcidentalInfo , muito obrigado pelas infos, já anotei e editei sua resposta para esconder os contatos.

Antes de eu fazer o teste com eles, poderia me responder mais umas questões, por favor?

1. Quando o envio é efetuado separadamente para cada um deles, os 3 recebem? 
2. Quando o envio é efetuado  para os 3 juntos, qual deles não recebe? Todos?
3. Poderia me enviar um código de exemplo? Apenas a parte que faz o envio de fato.
4. Poderia me enviar mais detalhes do seu ambiente? Coisas como:
4.1 WPPConnect Server(s): X.Y.Z
4.2 WPPConnect version(s): X.Y.Z
4.3 WA-JS version(s): X.Y.Z
4.4 WhatsApp version: X.YYYY.ZZ
4.5 Browser: Chrome XX / Chromium XX
4.6 OS: Windows X / OSX X.Y.Z
4.7 Node version: Node XY
4.8 MultiDevice (BETA): yes/no

**Como são contatos reais, com essas infos posso reproduzir o teste com o ambiente o mais próximo possível do seu, então não precisarei enviar mais que um ou 2 "Bom dia" :)**

**Comment by ghsgabriel** [comment]
@OcidentalInfo acabei de ver que se eu apenas editar, ainda conseguem ver o histórico, então estou deletando sua mensagem.

**Comment by OcidentalInfo** [comment]
Olá ghsgabriel.

Seguem alguma respostas:

1. Sim.
2. Normalmente o 2º item da lista "contatos[1]". Mas, as vezes o 4º item "contatos[3]" não recebe, ocasião onde o 2º recebe.
3. Trecho de código-exemplo de envio que uso:
      for (let i = 0; i < contatos.length; i++) {
        await http
          .post('http://localhost:21465/api/informs/send-message', contatos[i])
          .then((resp) => {
            console.log('RESP.SendMessage:', contatos[i].phone, resp.data.status) // 'success'
            console.log('Resp.Data', resp.data);
          })
          .catch(async (erro) => {
            console.log('ERRO: Send Message.', contatos[i].message, erro);
            console.log('RESP:', erro.response.data);
          });
      }

**Comment by OcidentalInfo** [comment]
Atualizei a última versão "v1.1.23" agora, fiz os teste novamente e está funcionando perfeitamente.
Problema RESOLVIDO!!
Obrigado a todos da equipe responsável por "wppconnect-server".

**Comment by OcidentalInfo** [comment]
Atualizei a última versão "v1.1.23" agora, fiz os testes novamente e está funcionando perfeitamente.
Problema RESOLVIDO!!
Obrigado a todos da equipe responsável por "wppconnect-server".
