### ISSUE TITLE
archiveAllChats and deleteAllChats

### ISSUE THREAD

**Issue by ghsgabriel** [wppconnect-team/wppconnect-server#483]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
create functions archiveAllChats and deleteAllChats

**Comment by icleitoncosta** [comment]
Hello @ghsgabriel, archiveAllChats implemented on https://github.com/wppconnect-team/wppconnect-server/commit/8c7d6faacc1246a3b3bac91e926886004b4e8295
