### ISSUE TITLE
ao enviar mensagem em grupo webhook recebe 2 chamadas

### ISSUE THREAD

**Issue by allisonwilliancandido** [wppconnect-team/wppconnect-server#549]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Wppconnect-server version(s): 1.1.20
- **Browser:** chrome 98
- **OS:** Windows 10
- **Node version:** 16
- **WhatsApp version:** 2.2144.11
- **MultiDevice (BETA):** no
- **config.json:
- `{
  "secretKey": "THISISMYSECURETOKEN",
  "host": "http://localhost",
  "port": "21465",
  "deviceName": "WppConnect",
  "startAllSession": true,
  "tokenStoreType": "file",
  "maxListeners": 15,
  "webhook": {
    "url": "",
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}
`

## Additional context / Screenshot
![Screenshot_82](https://user-images.githubusercontent.com/77209255/153969065-cfd6adc3-5f22-4f00-8e67-9e504c4d5765.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by icleitoncosta** [comment]
Esse erro ainda ocorre nessa ultima versão? Fiz alguns testes, mas não consegui reproduzir

**Comment by allisonwilliancandido** [comment]
Opa cleiton vou analisar hoje e se acontecer eu mando aqui.

**Comment by icleitoncosta** [comment]
@allisonwilliancandido algum retorno?
