### ISSUE TITLE
endpoint: /api/:session/forward-messages

### ISSUE THREAD

**Issue by bgastaldi** [wppconnect-team/wppconnect-server#56]
A mensagem é encaminhada mas o retorno é de erro: 'Error forwarding message'

https://github.com/wppconnect-team/wppconnect-server/blob/8cffb8a1493a41f6daa568ceb4ac98e7e6e863bb/src/routes/index.js#L125

**Comment by hbdbim** [comment]
fixed bug a36703fccf8208c98f3d9373510ea757cbc840e1
