### ISSUE TITLE
Send Storie (send-image-storie, send-video-storie e send-text-storie) não funciona.

### ISSUE THREAD

**Issue by filipesr** [wppconnect-team/wppconnect-server#571]
## Description

Nenhum desses endpoints funcionam corretamente.

## Environment

- **Wppconnect-server version(s): 1.1.20**
- **Browser: não encontrei essa informaçào**
- **OS: macOS Monterey 12.2.1**
- **Node version: Node v16.13.1**
- **WhatsApp version: 2.2204.13**
- **MultiDevice (BETA): yes** 
- **config.json:** 
{
  "secretKey": "IHZ5ZVnu5=fys.ADSgmPZI]:rV1i4{",
  "host": "http://localhost",
  "port": "6060",
  "deviceName": "GoOnMensageria",
  "startAllSession": true,
  "tokenStoreType": "file",
  "customUserDataDir": "./userData",
  "maxListeners": 15,
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "whatsappVersion": null,
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}

## Steps to Reproduce

1. generate-token -> ok
2. start-session -> ok
3. scan qrcode -> ok
4. check-connection-session -> ok
5. send-image-storie -> "status": "success"

## Your Code
JSON enviado:
{
	"path": "/Users/fsrezende/Documents/Goon/Goon/goon.png",
	"text": "Filipe Salavarez Rezende - 2022-02-23T10:58:41.225Z"
}

JSON recebido:
{
	"status": "success",
	"response": [
		{
			"ack": -1,
			"id": "true_status@broadcast_3EB0B7712EB03F589698",
			"sendMsgResult": "ERROR_UNKNOWN"
		}
	],
	"mapper": "return",
	"session": "goonSuporte"
}

**Comment by edgardmessias** [comment]
Até o momento é impossível postar stories usando o WhatsApp Web BETA (MultiDevice), pois não é um recurso implementado ainda
