### ISSUE TITLE
Webhook com maxBodyLength

### ISSUE THREAD

**Issue by ThiagoLimah** [wppconnect-team/wppconnect-server#578]
Olá, estou enfrentando dificuldade no recebimento de arquivos com mais de 6 mega de tamanho, quando o webhook é chamado para envio do base64, o mesmo acaba gerando o erro maxBodyLength.

É possível adicionar o maxBodyLength na request do axios com um valor mais alto, que se equivalha ao limite suportado por arquivos no WhatsApp?

`warn: 2022-02-26T12:11:56.463Z Error calling Webhook. Request body larger than maxBodyLength limit - Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit`

**Comment by hbdbim** [comment]
Se você for capaz pode implementar e mandar um pull request

Em sáb., 26 de fev. de 2022 08:36, Thiago Lima ***@***.***>
escreveu:

**Comment by ThiagoLimah** [comment]
Infelizmente não tenho conhecimento em Javascript para tal adaptação =/

**Comment by ThiagoLimah** [comment]
No arquivo src/util/functions.js

`export async function callWebHook(client, req, event, data) {
  const webhook = client?.config.webhook || req.serverOptions.webhook.url || false;
  if (webhook) {
    if (req.serverOptions.webhook.autoDownload) await autoDownload(client, req, data);
    try {
      const chatId = data.from || data.chatId || (data.chatId ? data.chatId._serialized : null);
      data = Object.assign({ event: event, session: client.session }, data);
      if (req.serverOptions.mapper.enable) data = await convert(req.serverOptions.mapper.prefix, data);

      //Adicionado aqui
      const apiConfig = {
        maxContentLength: Infinity,
        maxBodyLength: Infinity
      };

      var instance = api.create(apiConfig);

      instance
        .post(webhook, data)
        .then(() => {
          try {
            const events = ['unreadmessages', 'onmessage'];
            if (events.includes(event) && req.serverOptions.webhook.readMessage) client.sendSeen(chatId);          } catch (e) {}
        })
        .catch((e) => {
          req.logger.warn('Error calling Webhook.', e);
        });
    } catch (e) {
      req.logger.error(e);
    }
  }
}`

Porém agora ele gera o seguinte erro:

`0|omni-ser | warn: 2022-02-26T15:31:19.793Z Error calling Webhook. Request failed with status code 413 - Error: Request failed with status code 413
0|omni-ser |     at createError (/home/node/app/node_modules/axios/lib/core/createError.js:16:15)
0|omni-ser |     at settle (/home/node/app/node_modules/axios/lib/core/settle.js:17:12)
0|omni-ser |     at IncomingMessage.handleStreamEnd (/home/node/app/node_modules/axios/lib/adapters/http.js:322:11)
0|omni-ser |     at IncomingMessage.emit (node:events:532:35)
0|omni-ser |     at endReadableNT (node:internal/streams/readable:1346:12)
0|omni-ser |     at processTicksAndRejections (node:internal/process/task_queues:83:21)`

E ainda não consegui resolver =/

**Comment by hbdbim** [comment]
Acho que esse erro é do retorno e não dá chamada, problema do server que o wpp está chamando

**Comment by ThiagoLimah** [comment]
Sim, realmente era o servidor!
Com os ajustes que fiz do wppconnect-server funcionou pra mim agora!
Realizei o commit caso queiram avaliar depois.
