### ISSUE TITLE
endpoint: /api/:session/typing

### ISSUE THREAD

**Issue by bgastaldi** [wppconnect-team/wppconnect-server#59]
o endpoint funciona, mais ele não retorna success ou error. Ele fica segundando a "requisição" por um longo tempo até ocorrer timeout.

https://github.com/wppconnect-team/wppconnect-server/blob/8cffb8a1493a41f6daa568ceb4ac98e7e6e863bb/src/routes/index.js#L160

**Comment by dudanogueira** [comment]
confirmo isso daqui :)

**Comment by bgastaldi** [comment]
Fixed https://github.com/wppconnect-team/wppconnect/commit/a122b15deecfcb6f64c9be57b5d03e9fdfaab119
