### ISSUE TITLE
Erro group-info-from-invite-link

### ISSUE THREAD

**Issue by LukasCCB** [wppconnect-team/wppconnect-server#604]
A URL do convite está correta, porém quando peço para consultar, ela retorna erro.
Quando eu faço {{ _.base_url }}{{ _.session }}/group-invite-link/123454566 <- retorna a URL.
usando essa mesma URL para a requisição {{ _.base_url }}{{ _.session }}/group-info-from-invite-link

POST

{
  "invitecode": "https://chat.whatsapp.com/blablabla"
}

me retorna erro
500 Internal Server Error
{
	"status": "error",
	"message": "Error on get group info from invite link",
	"session": "NERDWHATS_AMERICA"
}

![image](https://user-images.githubusercontent.com/6683056/157762504-9583f2ab-fc46-43fe-a991-94990d07ccab.png)

**Comment by icleitoncosta** [comment]
This error is fix, update wppconnect-server to new version.
