### ISSUE TITLE
endpoint: /api/:session/change-privacy-group

### ISSUE THREAD

**Issue by bgastaldi** [wppconnect-team/wppconnect-server#61]
Fiz um teste com esse endpoint e travou meu business por 3 vezes. Acredito que exista algum erro. 

https://github.com/wppconnect-team/wppconnect-server/blob/8cffb8a1493a41f6daa568ceb4ac98e7e6e863bb/src/routes/index.js#L181

**Comment by hbdbim** [comment]
fixed bug b987aacece19682cb1665d84b213ddbecd7fabd2

{
  "groupId": "groupID",
  "status": "true ou false"
}
