### ISSUE TITLE
Como remover uma sessão?

### ISSUE THREAD

**Issue by MeuGestor** [wppconnect-team/wppconnect-server#612]
Tive que trocar meu chip que foi configurado na sessão1, porém, ao tentar iniciar novamente a sessão ele retorna apenas "INITIALIZING", como remover a sessão para recriala?

**Comment by dudanogueira** [comment]
vc pode tentar mudar o nome da sessão, dai ele reinicia. Ou apagar a pasta do perfil do chromium.

Mas isso não é um bug :)

**Comment by icleitoncosta** [comment]
Use a rota '/logout-session'
