### ISSUE TITLE
On multisession sessions messages mixes each other

### ISSUE THREAD

**Issue by sencerturgut** [wppconnect-team/wppconnect-server#625]
Hello,

I have an issue with wppconnect-server using with wppconnect-frontend. While system working with multisession, if tow different session chatting with same contact, one of the our sessions messages showing on other sessions chat sent or recieved from same contact.

## Environment

- **Wppconnect-server version(s):** 1.1.22
- **Browser:** Chrome Version 99.0.4844.82 
- **OS:** Windows 10
- **Node version:** Node 12.22
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes
- **config.json:** [Your src/config.json file content]
{
  "secretKey": "",
  "host": "http://localhost",
  "port": "21465",
  "deviceName" : "test",
  "startAllSession": false,
  "tokenStoreType": "file",
  "maxListeners": 15,
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true
  },
  "archive": {
    "enable": true,
    "waitTime": 10,
    "daysToArchive": 40
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "whatsappVersion": null,
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },

## Steps to Reproduce

1. use wppconnect-server with wppconnect-frontend
2. Open multisession and chat from two different session to same contact
3. One of sessions messages will shown in other chat page

**Comment by icleitoncosta** [comment]
Hello!

Do you try wppconnect-frontend-vue? 
That is updated.
