### ISSUE TITLE
Wpp connect crash

### ISSUE THREAD

**Issue by AlexandreDev06** [wppconnect-team/wppconnect-server#640]
## Descrição
Olá tudo bem? Então estou com um problema que o wpp está crashando, isso ocorre apenas em ambiente de produção no servidor hospedado na AWS, quando executo o mesmo código em ambiente development na minha maquina, ele executa de formal normal e não da esse crash.
Mais especificamente o container do wpp no docker está crashando conforme a print abaixo:

![image (1)](https://user-images.githubusercontent.com/69657496/160922136-5fc8d986-a169-404d-b79b-4d46db14d16a.png)
![image](https://user-images.githubusercontent.com/69657496/160925185-358f95df-4044-4af6-81fe-676fd3fbf45f.png)

O método que faz esse crash acontecer é esse abaixo:

```
 class SessionGetter < BaseService
    def call
      return Response.new(false, response, request.status) if request.status != 200
      Response.new(true, response, request.status)
    rescue StandardError => e
      log "Não foi possível obter o status da sessão #{central.session} do WhatsApp", e.message
    end

    private

    def request
      @request ||= Faraday.new(
        url: "#{api_url(central.session)}/status-session",
        headers: { 'Authorization' => "Bearer #{central.session_token}" }
      ).get
    end

    def response
      @response ||= JSON.parse(request.body)
    end
  end
```

Esse é um método de pegar o status da sessão para verificar se o celular está conectado ou não
## Ambiente
- *Wppconnect-server version(s):* [1.1.20]
- *Browser:* [Chrome 87]
- *MultiDevice (BETA):* não
## Passos para reproduzir
1. Acesso a aplicação pelo servidor em ambiente de produção
2. Conecto o celular usando o QR Code do WPP
3. No inicio o celular fica conectado por um periodo inderteminado, fiz alguns testes e ele ficou conectado durante 10 minutos até mais de 1 dia
4. Logo depois o docker crash retornando o erro no log do servidor

**Comment by icleitoncosta** [comment]
O webhook que você configurou está recebendo as mensagens corretamente?
