### ISSUE TITLE
Cannot read property 'numberExists' of undefined

### ISSUE THREAD

**Issue by bahreynipour** [wppconnect-team/wppconnect-server#643]
## Description

Hello,
When I try to use send-message method, I have got the below error:

0|app      | error: 2022-03-31T20:40:17.738Z Cannot read property 'numberExists' of undefined - TypeError: Cannot read property 'numberExists' of undefined
0|app      |     at statusConnection (/root/app/dist/middleware/statusConnection.js:32:24)
0|app      |     at runMicrotasks (<anonymous>)
0|app      |     at processTicksAndRejections (internal/process/task_queues.js:95:5)

## Environment

- **Wppconnect-server version(s): 1.1.23
- **Node version: v14.18.3
- **MultiDevice (BETA): yes

**Comment by bahreynipour** [comment]
any suggestion?

**Comment by edgardmessias** [comment]
@bahreynipour , update to latest version
