### ISSUE TITLE
{   "status": "error",   "message": "Error retrieving QRCode" }

### ISSUE THREAD

**Issue by bwanakweli4ever** [wppconnect-team/wppconnect-server#667]
error: 2022-04-15T13:24:29.303Z Cannot read property 'replace' of null - TypeError: Cannot read property 'replace' of null
    at getQrCode (/home/alex/wppconnect-server/src/controller/sessionController.js:286:47)
    at Layer.handle [as handle_request] (/home/alex/wppconnect-server/node_modules/express/li

when  i request http://localhost:21465/api/NERDWHATS_AMERICA/qrcode-session the above error persists , would you guide me a bit on how i fix that  please ?

**Comment by prashantnirgun** [comment]
I had the same issue as I found I am getting client undefined detail explanation can be found [here](https://discord.com/channels/844351092758413353/844351724600688657/974014436538990642)

**Comment by icleitoncosta** [comment]
What is the version of WAJS and WppConnect?

**Comment by prashantnirgun** [comment]
this issue is resolved please close this thread.
