### ISSUE TITLE
Metodo para retornar o numero logado

### ISSUE THREAD

**Issue by felipe-Rinaldi** [wppconnect-team/wppconnect-server#737]
Procurei e não achei o método para retornar o numero que está conectado, se for possível adicionar, agradeço

**Comment by icleitoncosta** [comment]
Você pode utilizar o método "IP:PORTA/api/NOME_DA_SESSAO/host-device" que retornará os dados da sessão conectada, telefone, dispositivo, etc.

**Comment by felipe-Rinaldi** [comment]
obrigado, deu certo.
