### ISSUE TITLE
Bug on /close-session

### ISSUE THREAD

**Issue by tessarolli** [wppconnect-team/wppconnect-server#740]
error: 2022-05-24T12:14:24.846Z req.client.close is not a function - TypeError: req.client.close is not a function
    at closeSession (/root/wppconnect-server/src/controller/sessionController.js:157:22)
    at Layer.handle [as handle_request] (/root/wppconnect-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/wppconnect-server/node_modules/express/lib/router/route.js:137:13)
    at /root/wppconnect-server/src/middleware/auth.js:57:9

**Comment by Nevinyrral** [comment]
Having the same issue, I'm using the MongoDB token store

**Comment by Nevinyrral** [comment]
wppconnect-team/wppconnect: "1.14.5"
wppconnect/server: "1.5.0"

**Comment by icleitoncosta** [comment]
I'm try to reproduct this, but without errors. 
Do you explain how to reproduce?

You is try to "/close-session" on session connected?

**Comment by tessarolli** [comment]
> I'm try to reproduct this, but without errors. Do you explain how to reproduce?
> 
> You is try to "/close-session" on session connected?

Hit /close-session multiple times.
After the first time, this error shows up

**Comment by icleitoncosta** [comment]
> > I'm try to reproduct this, but without errors. Do you explain how to reproduce?
> 
> > 
> 
> > You is try to "/close-session" on session connected?
> 
> 
> 
> Hit /close-session multiple times.
> 
> After the first time, this error shows up

Thanks, I will make a correction.

**Comment by dcrec1** [comment]
This is still happening.
