### ISSUE TITLE
Unseen not working.

### ISSUE THREAD

**Issue by leohturbo** [wppconnect-team/wppconnect-server#777]
## Description

When call /mark-unseen api.

## Environment

- **Wppconnect-server version(s):** v1.3.3
- **Browser:** Chromium 99
- **OS:** MAC OS BIG SUR
- **Node version:** Node 14
- **WhatsApp version:** 2.2214.12
- **MultiDevice (BETA):** yes

## Steps to Reproduce

POST - /mark-unseen

Return.
{ status: 'error', message: 'Error on mark unseen' }

Console is empty. Nothing happened.

**Comment by icleitoncosta** [comment]
Closed by  commit c3f6420f8129dd4069d2ba05aa911a352914afb4

**Comment by leohturbo** [comment]
I've tested.

The unseen method now is working but with a error...
It don't mark as unseen (unread), it marks as seen (read).

Even if we try to call the method again it keep marking as seen (read) not as unread (unseen).
