### ISSUE TITLE
chat-is-online

### ISSUE THREAD

**Issue by douglasimmer** [wppconnect-team/wppconnect-server#78]
Quando fiz a consulta com o 9 digito, deu como false, removi o 9 digito, deu true.
Coloquei um console log na função getChatIsOnline, para verificar e o resultado era esse:
55XXXXXXXXXX phone
true response
55XX9XXXXXXXX phone
false response

**Comment by hbdbim** [comment]
resolvido, agora as chamadas são tratado o nono digito antes.
#106
