### ISSUE TITLE
wppserver fails to read config file passed

### ISSUE THREAD

**Issue by andrisi** [wppconnect-team/wppconnect-server#793]
## Description

wppserver (the cli) fails when using the --config option. The parsed options in commandOptions (in the run() function in index.js) just contain a "true" for the config param, not the actual file path I pass to the cli.

## Environment

Node: v16.15.0 (Windows 10)
WhatsApp WEB version: 2.2220.8
WA-JS version: 2.7.3

## Steps to Reproduce

`wppserver --config "./config.json"
`
## Log Output

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type boolean (true)`

{
  webhookListenAcks: true,
  webhookOnPresenceChanged: true,
  webhookOnParticipantsChanged: true,
  config: true
}

**Comment by icleitoncosta** [comment]
Please remove the config option from within config.js
