### ISSUE TITLE
Stuck at initializing

### ISSUE THREAD

**Issue by bahreynipour** [wppconnect-team/wppconnect-server#804]
## Description
I already scan and add a whatsapp account in wpp-connect-server.
But when I tried to scan the second whatsapp account it stucks at INITIALIZING like below:
 Initializing browser...
 Chrome not found, using chromium
Initializing...
WhatsApp WEB version: 2.2222.11
WA-JS version: 2.7.3

.. and nothing more

## Environment

- **Wppconnect-server version(s):** 1.3.4
- **OS:** Ubuntu
- **Node version:** v18.4.0 
- **MultiDevice (BETA):** yes
- **config.json:** 

{
  "secretKey": "",
  "host": "http://localhost",
  "port": "8000",
  "deviceName": "WPPConnect",
  "startAllSession": true,
  "tokenStoreType": "file",
  "maxListeners": 0,
  "webhook": {
    "url": null,
    "autoDownload": false,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": false,
    "onParticipantsChanged": false
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "whatsappVersion": null,
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}

**Comment by meshesha** [comment]
same issue

**Comment by meshesha** [comment]
For me the cause of the problem was that I did not have chrome installed. 
The problem was solved after I installed the Chrome

**Comment by icleitoncosta** [comment]
Please, update for de last version, and return for me

**Comment by DevDefault** [comment]
Same issue
