### ISSUE TITLE
Erro de Requisição com 9º Digito

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#81]
Ao realizar uma solicitação para o endpoint ```archive-chat```, se informar o número com o nono digito ele fica rodando e rodando até dar timeout na requisição.

Porém quando tira o nono digito ele já executa a solicitação.

O ideal seria verificar o número junto ao WhatsApp, e pegar o id real dele no WhatsApp antes de cada requisição, como o ```check-number-status``` faz para não ter erro de solicitação perdida.

**Comment by hbdbim** [comment]
#106
