### ISSUE TITLE
all-messages-in-chat returning a undefined response

### ISSUE THREAD

**Issue by leohturbo** [wppconnect-team/wppconnect-server#813]
In some conversations even if already loaded all the messages on the chat we can't see all the messages on this endpoint.
Sometimes it even return a undefined response.

http://localhost:port/api/session/all-messages-in-chat/55SomeNumber

Sometimes it return correctly, so i don't know what happening. LMAO.

* Using multi devices whatsapp *

**Comment by icleitoncosta** [comment]
This route is deprecated in favor of "/get-messages"
