### ISSUE TITLE
kill-service-workier/restart-service always returning session not active.

### ISSUE THREAD

**Issue by Saifallak** [wppconnect-team/wppconnect-server#817]
## Description

kill-service-workier/restart-service always returning session not active.

## Environment

- **Wppconnect-server version(s):** 1.4.0
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** CentOS 7
- **Node version:** Node 14
- **WhatsApp version:** 2.2220.8
- **MultiDevice (BETA):** yes
- **config.json:** same as orignial one.

## Additional context / Screenshot

```
{
    "status": "error",
    "response": {
        "message": "The session is not active"
    }
}
```

**Comment by icleitoncosta** [comment]
tell me the step by step to replicate the error here?
