### ISSUE TITLE
Screenshot of all conversations on the WhatsApp web page

### ISSUE THREAD

**Issue by faisalbz** [wppconnect-team/wppconnect-server#830]
Thank you for this wonderful work.
We wish to add a screenshot of all conversations on the WhatsApp Web page.

**Comment by icleitoncosta** [comment]
Hello, what's the problem, who needs this screenshot?

**Comment by icleitoncosta** [comment]
You can try using the LIB WppConnect-team/WppConnect and try command page.screenshot 

See https://pptr.dev

But this function not viable for the project idea
