### ISSUE TITLE
Filename do send-file-base64 Removido por erro

### ISSUE THREAD

**Issue by jeffsystem** [wppconnect-team/wppconnect-server#831]
Em alguma atualização acabaram removendo o parâmetro filename do endpoint send-file-base64, acarretando em todos os pdf chegando com nome application.pdf.

Pesquisando achei essa mudança
![image](https://user-images.githubusercontent.com/39931647/178266923-a60b2ccc-bc97-417b-8dbb-0f5bb879e878.png)

Com o filename dá para colocar o nome abaixo do arquivo, agora vem assim:

![image](https://user-images.githubusercontent.com/39931647/178266956-399f7ee8-eef8-4f72-ae74-8f18bced3fc0.png)

**Comment by edgardmessias** [comment]
@icleitoncosta

**Comment by icleitoncosta** [comment]
Fixed on https://github.com/wppconnect-team/wppconnect-server/commit/3016f2f7ad65d18e762f51b98bdcb53bfd5ad8b5
