### ISSUE TITLE
Rota getLabels, addToLabel, removeFromLabel

### ISSUE THREAD

**Issue by leohturbo** [wppconnect-team/wppconnect-server#835]
Vi que está disponivel no wa-js a opção de obter as labels ou adicionar ou remover conversas nas labels (etiquetas), mas não tem essa rota aqui!

**Comment by icleitoncosta** [comment]
Ainda estamos aguardando ela ficar disponível na LIB, e assim que for adicionada, já colocamos aqui.

**Comment by icleitoncosta** [comment]
> Vi que está disponivel no wa-js a opção de obter as labels ou adicionar ou remover conversas nas labels (etiquetas), mas não tem essa rota aqui!

Opa Leo, lancei a atualiação para poder pegar as labels e também adicionar e remover um chat da label, porém ainda não é possível criar label através do WhatsApp Web, assim que for, também iremos adicionar essa no server.

Abraços!

https://github.com/wppconnect-team/wppconnect-server/commit/25f21c0a8eb139914ccccd9a515b6558f4b70485
