### ISSUE TITLE
Slow up and down of messages in chatwoot

### ISSUE THREAD

**Issue by valterandrade** [wppconnect-team/wppconnect-server#842]
After version 2.7 of chatwood, the error of slowness of messages that are dealt between chatwoot and wppconnect was noticed

**Comment by igordisco** [comment]
valter, tu conseguiu ler mensagens anteriores do whatsapp? ou só a partir do ponto que conecta no wppcnnect?

**Comment by renat473** [comment]
possível problema corrigido na última versão.
