### ISSUE TITLE
Sending stickers

### ISSUE THREAD

**Issue by apexcodexd** [wppconnect-team/wppconnect-server#85]
How to send stickers

**Comment by mvfernandes** [comment]
you should implement it in your frontend, if you are using the project [wppconnect-frontend](https://github.com/wppconnect-team/wppconnect-frontend) you will soon get this option

**Comment by tomsilva** [comment]
Please see this in documentation.

Link one https://wppconnect-team.github.io/wppconnect/classes/Whatsapp.html#sendImageAsSticker

link two https://wppconnect-team.github.io/wppconnect/classes/Whatsapp.html#sendImageAsStickerGif
