### ISSUE TITLE
START SERVER IN LINUX

### ISSUE THREAD

**Issue by LuizVeloso10** [wppconnect-team/wppconnect-server#856]
nfo:     [sessionName:browser] Using browser folder '/home/gesfood/public_html/bot-test/tokens/sessionName'
info:     [sessionName:browser] Initializing browser...
error:    [sessionName:browser] Error no open browser
error:    [sessionName:browser] Failed to launch the browser process!

Alguém poderia me ajudar com essa questão, estou tentando subir em um server linux 

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by icleitoncosta** [comment]
Try: 
`sudo apt install chromium-browser`

**Comment by icleitoncosta** [comment]
Olá, conseguiu resolver?
