### ISSUE TITLE
error on routes /get-messages /load-messages-in-chat

### ISSUE THREAD

**Issue by leohturbo** [wppconnect-team/wppconnect-server#862]
ENGLISH:
I know I know... loadMessagesInChat is deprecated... BUUUUT...
It still works if I run the command on chrome inspect: WAPI.loadAllEarlierMessages('NUMBER@c.us')

The bug is as follows.
It's only loading the last message in some cases, usually when the conversation is older, so when running the load-messages-in-chat route it returns an error.

In the "deprecated" notice it says warning to use the getMessages route, but this route does not loadAllEarlierMessages, so even using it, only the last message that was in the conversation will always appear.

To fix it I believe you just add the WAPI.loadAllEarlierMessages('NUMERO@c.us') in the getMessages function or simply correct the loadAndGetAllMessagesInChat function so it doesn't give an error.

Follows the return of the error at the end of text.

PORTUGUESE:
Eu sei eu sei... loadMessagesInChat está deprecated... MAAAAS...
Ainda assim funciona se eu rodar o comando no inspecionar: WAPI.loadAllEarlierMessages('NUMERO@c.us')

O bug é o seguinte.
Só está carregando a ultima mensagem em alguns casos, geralmente quando a conversa é mais antiga, então, ao rodar a rota load-messages-in-chat ela retorna um erro.

No aviso de "deprecated" está escrito avisando para usar a rota getMessages, porém essa rota não faz o loadAllEarlierMessages, então mesmo utilizando ela vai aparecer sempre somente a última mensagem que teve na conversa.

Para corrigir acredito que é só adicionar o WAPI.loadAllEarlierMessages('NUMERO@c.us') na função de getMessages ou então simplesmente corrigir a função loadAndGetAllMessagesInChat para ela não dar erro.

Segue o retorno com o erro abaixo.

error: 2022-08-07T09:58:38.423Z n.loadEarlierMsgs is not a function - Error: n.loadEarlierMsgs is not a function
    at /Users/leoh/Desktop/whatsking/king/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
    at step (/Users/leoh/Desktop/whatsking/king/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/Users/leoh/Desktop/whatsking/king/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/Users/leoh/Desktop/whatsking/king/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by icleitoncosta** [comment]
Olá Leo, tudo bem?

Você pode passar a rota get-messages utilizando get-messages/$phone/?count=20 por exemplo, que você retornará quantas mensagens precisar, ou passar como -1 que você retorna todas as mensagens do chat.

Seria isso que você precisa?

**Comment by leohturbo** [comment]
Realmente, nessa rota funciona tudo normal. Obrigado.

**Comment by m7mdcc** [comment]
Sorry to bump this again , i pass -1 but it's only grab 1 month messages .. on web client there is messages but you need to click on sync message to load more messages
