### ISSUE TITLE
WAPI error

### ISSUE THREAD

**Issue by NoctisBnu** [wppconnect-team/wppconnect-server#864]
Erro quando loga o server, normalmente na segunda vez, depois de ja ter dados de login de usuario
![Sem título](https://user-images.githubusercontent.com/57999263/183419755-cf3f9bd1-1883-4238-9e8a-47fcc183b88e.png)

**Comment by dcrec1** [comment]
Também está acontecendo aqui com a ultima versão.

**Comment by icleitoncosta** [comment]
Olá, boa noite
Já descobrimos o problema, e em breve sai uma correção.

**Comment by prashantnirgun** [comment]
I am facing same issue running following version wppconnect-server version 1.6.2
with following dependancy
"@WPPConnect-team/wppconnect": "^1.16.1",

**Comment by icleitoncosta** [comment]
> I am facing same issue running following version wppconnect-server version 1.6.2
> 
> with following dependancy 
> 
> "@WPPConnect-team/wppconnect": "^1.16.1",
> 
> 
> 
> When I was installing node packages it give following warning is that giving problems
> 
> npm WARN lifecycle @wppconnect/server@1.6.2~prepare: cannot run in wd @wppconnect/server@1.6.2 husky install (wd=/dir)
> 
> npm WARN @wppconnect/server@1.6.2 No repository field.
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
> 
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> 

Qual comando está utilizando pra iniciar?
Já existe alguma sessão conectada?

**Comment by prashantnirgun** [comment]
POST start-session with webhook
