### ISSUE TITLE
Some time qrcode not generate . How to solve ?

### ISSUE THREAD

**Issue by Akash-Rathore** [wppconnect-team/wppconnect-server#875]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Wppconnect-server version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes/no
- **config.json:** [Your src/config.json file content]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by dcrec1** [comment]
When I try to close the session, I get:

```
error: 2022-08-24T23:16:23.661Z req.client.close is not a function - TypeError: req.client.close is not a function
    at closeSession (/var/local/apps/wppconnect-server/src/controller/sessionController.js:161:24)
    at Layer.handle [as handle_request] (/var/local/apps/wppconnect-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/local/apps/wppconnect-server/node_modules/express/lib/router/route.js:144:13)
    at /var/local/apps/wppconnect-server/src/middleware/auth.js:57:9
```

**Comment by RodrigoCesarCoelho** [comment]
I have the same problem. 
Eu estou com o mesmo problema, ao executar o servidor para testes localmente no Windows 10.

**Comment by icleitoncosta** [comment]
Can you post here the step by step you are doing to connect?
