### ISSUE TITLE
restart service function not wokring

### ISSUE THREAD

**Issue by Akash-Rathore** [wppconnect-team/wppconnect-server#876]
error: 2022-08-19T14:29:48.095Z req.client.restartService is not a function - TypeError: req.client.restartService is not a function at restartService (C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\src\controller\sessionController.js:313:75) at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\node_modules\express\lib\router\layer.js:95:5) at next (C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\node_modules\express\lib\router\route.js:144:13) at statusConnection (C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\src\middleware\statusConnection.js:71:7) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by dcrec1** [comment]
Which API call are you using?

**Comment by icleitoncosta** [comment]
This function is currently not implemented.

**Comment by renat473** [comment]
possível problema corrigido na última versão.
