### ISSUE TITLE
Criar rotas para backup e restore das sessions

### ISSUE THREAD

**Issue by bgastaldi** [wppconnect-team/wppconnect-server#88]
Adicionar duas rotas sendo um para backup(download) e outra para restore (upload) dos tokens salvos diretamente no server.

**Comment by moskoweb** [comment]
Já tem uma rota para pegar todas as sessões.

**Comment by bgastaldi** [comment]
Salve! A ideia aqui é outra. Deixei aberto para lembrar de implementar no futuro um restore mais automatico.

**Comment by Saifallak** [comment]
+1, this feature would be awesome.

**Comment by icleitoncosta** [comment]
> Any ideas on what to backup exactly? And restore?
> 
> Going to give it a try.

I already have this code done, but I'm going to release it in the new version, to later leave here, but in summary it's very simple:

you have to put the userDataDir folder and the tokens in a zip and download it to make the backup, and to restore send it through an endpoint and extract it in the respective folders, then start all sessions to be able to start them.

**Comment by icleitoncosta** [comment]
Added by the last commit
