### ISSUE TITLE
How to send file with message?

### ISSUE THREAD

**Issue by shoerofi** [wppconnect-team/wppconnect-server#903]
<img width="1323" alt="Screen Shot 2022-09-18 at 10 23 38 AM" src="https://user-images.githubusercontent.com/5960940/190884301-a78f3d71-3cdc-44ce-9028-0e01fcacfe0e.png">

**Comment by icleitoncosta** [comment]
Whatsapp still does not allow sending files with text, only images.

**Comment by shoerofi** [comment]
> Whatsapp still does not allow sending files with text, only images.

Oke..
So how to send image with text? I did not see it in api docs. 

Thanks

**Comment by shoerofi** [comment]
<img width="665" alt="Screen Shot 2022-10-03 at 12 58 44 PM" src="https://user-images.githubusercontent.com/5960940/193510260-3f0c3957-9c10-4ef7-8d79-a1436dfd1480.png">

this is how to send image with text, 

/send-image

body: {
phone: "phone number",
path: "path for the image",
caption: "text messages"
}
