### ISSUE TITLE
Doc Postman GET Host device - get-battery-level

### ISSUE THREAD

**Issue by gcsfred2** [wppconnect-team/wppconnect-server#941]
## Description

Na documentação do Postman ( https://documenter.getpostman.com/view/9139457/TzshF4jQ#965e57bf-cf5a-4387-a702-f2f39a722645 ), a chamada GET Host device usa a URL de Battery status (get-battery-level).

## Environment

- **Wppconnect-server version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes/no
- **config.json:** [Your src/config.json file content]

## Steps to Reproduce

Not applicable.

## Log Output

```
Not applicable.
```

## Your Code

```
Not applicable.
```

**Comment by icleitoncosta** [comment]
Tenta priorizar o uso da nossa documentação do Swagger, está mais completa:

https://wppconnect.io/swagger/wppconnect-server/
