### ISSUE TITLE
Código QR de /status-session não contém margens

### ISSUE THREAD

**Issue by gcsfred2** [wppconnect-team/wppconnect-server#942]
## Description
O código QR gerado pela chamada /status-session e codificado em base64 quando salvo em .PNG ou mostrado como imagem direto não contém margens brancas, enquanto deveria conter. Sem as margens em branco, um celular ao escanear a imagem não reconhece o QR e não linka uma sessão. A imagem anexada foi salva

## Environment

- **Wppconnect-server version(s):** commit 2bbff1341b6df49eab368a9580bd7f6137077650 
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]
- **WhatsApp version:** [e.g. 2.2126.14]
- **MultiDevice (BETA):** yes/no
- **config.json:** [Your src/config.json file content]

## Steps to Reproduce

1. Chama /status-session
2. Pega string de código QR
3. Descarta os primeiros 22 bytes, salva esse string como arquivo .png
4. Escaneia essa imagem .png com WhatsApp

Esperado: celular linkado
O que acontece: celular não reconhece o código QR. 

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

O código abaixo mostra um workaround para o problema em Python.

```
def mostra_qr(sessao, qr_code):
	arquivo_qr = "qr_" + sessao + ".png"
	qr_code = qr_code[22:]  # removendo o prefixo data:image/png;base64,
	with open(arquivo_qr, "wb") as fh:
		fh.write(base64.decodebytes(str.encode(qr_code)))
		fh.close()
	with Image.open(arquivo_qr) as img:
                # workaround abaixo -- inserindo margens em branco
		background = Image.new(img.mode[:-1], (img.size[0]+30, img.size[1]+30), (255, 255, 255))
		background.paste(img, (15, 15))
		background.show()
	# os.remove(arquivo_qr)

```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

![qr_vfywbnauysetobpangjz](https://user-images.githubusercontent.com/39340197/196305094-55612c66-53d2-4a4b-899e-bc85796f5d61.png)

**Comment by icleitoncosta** [comment]
Olá, qual o celular que foi feito o teste?

**Comment by gcsfred2** [comment]
Android Galaxy S8 modelo SM-G950W.

**Comment by gcsfred2** [comment]
Esse foi o celular de envio, mas o código foi executado num MacBook Pro com
macOS Monterey.

**Comment by icleitoncosta** [comment]
Certo, verifiquei e realmente, em alguns sistemas com Android há uma dificuldade na leitura do QR sem borda branca dentro do WhatsApp. Vou analisar a possibilidade de adicionar essa margem no server.

**Comment by gcsfred2** [comment]
Note que o QR gerado no servidor mostrado nos logs tem uma borda branca,
mas o PNG retornado na API não tem a borda.
