### ISSUE TITLE
Erro ao tentar conectar

### ISSUE THREAD

**Issue by diogofm7** [wppconnect-team/wppconnect-server#944]
Estou tendo esse erro, e não consigo conectar, ele gera o qrcode, eu escaneio, mas da esse erro.

info:     [nova-session:session] Session Unpaired
wppconnect_1  | info: 2022-10-18T12:13:17.142Z [nova-session] 0% - Connecting…
wppconnect_1  | info: 2022-10-18T12:13:21.147Z [nova-session] 100% - Connecting…
wppconnect_1  | info: 2022-10-18T12:13:22.538Z [nova-session] 100% - Organizing messages
wppconnect_1  | info:     [nova-session:client] Closing the page
wppconnect_1  | warn:     [nova-session:client] Failed to authenticate
wppconnect_1  | info: 2022-10-18T12:13:38.241Z qrReadError
wppconnect_1  |
wppconnect_1  |
wppconnect_1  | error:    [nova-session:client] Auto Close Called
wppconnect_1  | error: 2022-10-18T12:13:38.242Z Auto Close Called
wppconnect_1  | info: 2022-10-18T12:13:38.247Z browserClose

**Comment by icleitoncosta** [comment]
Opa @diogofm7, poderia testar na última versão (1.6.4)?

**Comment by renat473** [comment]
situação corrigida na última versão.
