### ISSUE TITLE
`QRCode.toDataURL` requires string on existing session fetch

### ISSUE THREAD

**Issue by Saifallak** [wppconnect-team/wppconnect-server#959]
Hello, this is crashing my server, as when the session is already authenticated, `urlcode` is null, and `QRCode.toDataURL` needs a string not null, so it's crashing.

_Originally posted by @Saifallak in https://github.com/wppconnect-team/wppconnect-server/pull/956#discussion_r1002746871_

**Comment by icleitoncosta** [comment]
Hello, I'm test reproduce this error for fix

**Comment by icleitoncosta** [comment]
Please, test after the last commit https://github.com/wppconnect-team/wppconnect-server/commit/5ed97e4beec570d1573fdb05ebaedd2584876d42

**Comment by Saifallak** [comment]
> Please, test after the last commit [5ed97e4](https://github.com/wppconnect-team/wppconnect-server/commit/5ed97e4beec570d1573fdb05ebaedd2584876d42)

I'll tomrrow thanks
