### ISSUE TITLE
send button

### ISSUE THREAD

**Issue by ti-3w** [wppconnect-team/wppconnect-server#960]
## Description

When I send the button by api it only appears on the web but it is not seen on the mobile

## Environment

- **Wppconnect-server version(s):** 1.6.4
- **Browser:** Chrome  106.0.5249.119
- **OS:** Macos
- **Node version:** Node 16
- **WhatsApp version:** 2.2240.7
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. I send the buttons by api following this structure: https://wppconnect.io/swagger/wppconnect-server/#tag/Send-Message/operation/SendMessageWithButton

2. On whatsapp web if it is displayed but on the phone the message arrives empty

Web
![image](https://user-images.githubusercontent.com/112997831/197828371-d60320db-e6cd-4bc4-be10-0b9c7830559a.png)

Mobile
![image](https://user-images.githubusercontent.com/112997831/197828679-ab56da2a-9399-48d4-a3b7-d9676c9b56f4.png)

**Comment by icleitoncosta** [comment]
This is an error of whatsapp itself that does not appear on certain devices, and at the moment, in

**Comment by vitos88** [comment]
> This is an error of whatsapp itself that does not appear on certain devices, and at the moment, in

Is it the same in the official api? does anyone know when this problem hits iOS

**Comment by icleitoncosta** [comment]
No, the official API is working. We are already working on the fix and I believe that soon we will get an alternative to solve it.

**Comment by icleitoncosta** [comment]
Hello, could you test in the latest version of WhatsApp? On some updated devices, the buttons are already working again.

**Comment by icleitoncosta** [comment]
Please, test with: useTemplateButtons: false

**Comment by Sau64** [comment]
not fully working though. If app is closed or in background, buttons don't render.

**Comment by IgorDePaula** [comment]
I have the same problem. I put logger like debug, and nothing more about the error.

![Captura de Tela 2023-01-16 às 13 55 13](https://user-images.githubusercontent.com/2833993/212730908-0d509c8d-ab38-46ed-a41d-3a83f115eb64.png)

**Comment by icleitoncosta** [comment]
> I have the same problem. I put logger like debug, and nothing more about the error.
> 
> 
> 
> ![Captura de Tela 2023-01-16 às 13 55 13](https://user-images.githubusercontent.com/2833993/212730908-0d509c8d-ab38-46ed-a41d-3a83f115eb64.png)
> 
> 
> 
> the log file have:
> 
> 
> 
> ```
> 
> {
> 
>   message: 'Error sending message with buttons',
> 
>   level: 'error',
> 
>   timestamp: '2023-01-16T16:46:04.484Z'
> 
> }
> 
> {
> 
>   message: 'Error sending message with buttons',
> 
>   level: 'error',
> 
>   timestamp: '2023-01-16T16:47:11.176Z'
> 
> }
> 
> {
> 
>   message: 'Error sending message with buttons',
> 
>   level: 'error',
> 
>   timestamp: '2023-01-16T16:47:27.986Z'
> 
> }
> 
> {
> 
>   message: 'Error sending message with buttons',
> 
>   level: 'error',
> 
>   timestamp: '2023-01-16T16:49:17.252Z'
> 
> }
> 
> {
> 
>   message: 'Error sending message with buttons',
> 
>   level: 'error',
> 
>   timestamp: '2023-01-16T16:51:52.687Z'
> 
> }
> 
> {
> 
>   message: 'Error sending message with buttons',
> 
>   level: 'error',
> 
>   timestamp: '2023-01-16T16:56:39.517Z'
> 
> }
> 
> ```
> 
> 

Nao está funcionando o envio de botões. Erro do próprio WhatsApp, não há solução.

**Comment by IgorDePaula** [comment]
> > I have the same problem. I put logger like debug, and nothing more about the error.
> > ![Captura de Tela 2023-01-16 às 13 55 13](https://user-images.githubusercontent.com/2833993/212730908-0d509c8d-ab38-46ed-a41d-3a83f115eb64.png)
> > the log file have:
> > ```
> > 
> > {
> > 
> >   message: 'Error sending message with buttons',
> > 
> >   level: 'error',
> > 
> >   timestamp: '2023-01-16T16:46:04.484Z'
> > 
> > }
> > 
> > {
> > 
> >   message: 'Error sending message with buttons',
> > 
> >   level: 'error',
> > 
> >   timestamp: '2023-01-16T16:47:11.176Z'
> > 
> > }
> > 
> > {
> > 
> >   message: 'Error sending message with buttons',
> > 
> >   level: 'error',
> > 
> >   timestamp: '2023-01-16T16:47:27.986Z'
> > 
> > }
> > 
> > {
> > 
> >   message: 'Error sending message with buttons',
> > 
> >   level: 'error',
> > 
> >   timestamp: '2023-01-16T16:49:17.252Z'
> > 
> > }
> > 
> > {
> > 
> >   message: 'Error sending message with buttons',
> > 
> >   level: 'error',
> > 
> >   timestamp: '2023-01-16T16:51:52.687Z'
> > 
> > }
> > 
> > {
> > 
> >   message: 'Error sending message with buttons',
> > 
> >   level: 'error',
> > 
> >   timestamp: '2023-01-16T16:56:39.517Z'
> > 
> > }
> > ```
> 
> Nao está funcionando o envio de botões. Erro do próprio WhatsApp, não há solução.

Eu achei que esta escrito na parte de cima que a api oficial esta funcionando, mas tudo bem. Sugestao remover essa parte do core da lib e da docs. Fica confuso para quem esta iniciando.

**Comment by IgorDePaula** [comment]
@icleitoncosta rapaz, eu consegui enviar pelo client do wppconnect, ae resolvi baixar o server, estudar e propor uma solucao, mas na real, ta funcioando sim. Acho que foram as imagens docker que usei...mas baixando ambas e rodando local, ta funcionando perfeitamente...So o server q ta perdendo a sessao ativa com o celular...

**Comment by icleitoncosta** [comment]
> @icleitoncosta rapaz, eu consegui enviar pelo client do wppconnect, ae resolvi baixar o server, estudar e propor uma solucao, mas na real, ta funcioando sim. Acho que foram as imagens docker que usei...mas baixando ambas e rodando local, ta funcionando perfeitamente...So o server q ta perdendo a sessao ativa com o celular...

Opa, show! Irei fazer alguns testes com outros dispositivos, beta, Android, iOS, etc, e fechar essas issues, acho que é a requisição mais pedida do projeto, mas sai do nosso escopo de solução, então a gente fica travado. 
Eu não entendi sobre a parte das DOCs, seria o que?

**Comment by IgorDePaula** [comment]
@icleitoncosta O que seria DOCs? ou seria docker? Inicialmente eu testei o projeto usando as imagens docker que voces disponibilizam, encontrei alguns erros, mas baixando o projeto e rodando direto, sem docker, eles funcionam. Agora algumas dessas funcionalidade stem limitacoes, acredito ser do proprio whatsapp. Exemplo, botoes, no web eu consegui exibir 6 botoes, mas no aparelho android so era exibir 3 botoes.

**Comment by icleitoncosta** [comment]
> @icleitoncosta O que seria DOCs? ou seria docker? Inicialmente eu testei o projeto usando as imagens docker que voces disponibilizam, encontrei alguns erros, mas baixando o projeto e rodando direto, sem docker, eles funcionam. Agora algumas dessas funcionalidade stem limitacoes, acredito ser do proprio whatsapp. Exemplo, botoes, no web eu consegui exibir 6 botoes, mas no aparelho android so era exibir 3 botoes.

DOCs seria a documentação, mas é porque você em uma mensagem anterior digitou assim, então imagino que esteja falando do docker, pela nossa conversa.

O que seria pra retirar do docker?

Exato, são limitações do próprio WhatsApp, que não dá muito o que fazer, aproveitando... você testou os botões em iOS e com o celular com a tela desligada?

Nas nossas conversas acima estávamos enfrentando problemas dessas duas formas, e não tínhamos solução.

Sobre os outros problemas que encontrou, se puder abrir uma issue informando, fico muito grato. Em breve vamos estar analisando e tentando melhorar de alguma forma.

**Comment by IgorDePaula** [comment]
> > @icleitoncosta O que seria DOCs? ou seria docker? Inicialmente eu testei o projeto usando as imagens docker que voces disponibilizam, encontrei alguns erros, mas baixando o projeto e rodando direto, sem docker, eles funcionam. Agora algumas dessas funcionalidade stem limitacoes, acredito ser do proprio whatsapp. Exemplo, botoes, no web eu consegui exibir 6 botoes, mas no aparelho android so era exibir 3 botoes.
> 
> DOCs seria a documentação, mas é porque você em uma mensagem anterior digitou assim, então imagino que esteja falando do docker, pela nossa conversa.
> 
> O que seria pra retirar do docker?
> 
> Exato, são limitações do próprio WhatsApp, que não dá muito o que fazer, aproveitando... você testou os botões em iOS e com o celular com a tela desligada?
> 
> Nas nossas conversas acima estávamos enfrentando problemas dessas duas formas, e não tínhamos solução.
> 
> Sobre os outros problemas que encontrou, se puder abrir uma issue informando, fico muito grato. Em breve vamos estar analisando e tentando melhorar de alguma forma.

Apesar de eu, agora, nesse momento, utilizar macos monterey (no dia a dia uso linux) numa maquina um pouco limitada (8gm ram - meu linux tem mais poder) nao sei o que retirar do docker. Quando voltar pra casa e rodar o docker novamente eu lanco PRs. Sobre IOs, eu so tenho android. 

Sim, sobre documentacao, algumas estao "erradas/defasadas/desatualizadas", uma delas esta com o metodo sendgif duplicado. Eu to querendo sentar no meu linux, testar o que der, e atualizar as documentacoes.

**Comment by icleitoncosta** [comment]
> > > @icleitoncosta O que seria DOCs? ou seria docker? Inicialmente eu testei o projeto usando as imagens docker que voces disponibilizam, encontrei alguns erros, mas baixando o projeto e rodando direto, sem docker, eles funcionam. Agora algumas dessas funcionalidade stem limitacoes, acredito ser do proprio whatsapp. Exemplo, botoes, no web eu consegui exibir 6 botoes, mas no aparelho android so era exibir 3 botoes.
> 
> > 
> 
> > DOCs seria a documentação, mas é porque você em uma mensagem anterior digitou assim, então imagino que esteja falando do docker, pela nossa conversa.
> 
> > 
> 
> > O que seria pra retirar do docker?
> 
> > 
> 
> > Exato, são limitações do próprio WhatsApp, que não dá muito o que fazer, aproveitando... você testou os botões em iOS e com o celular com a tela desligada?
> 
> > 
> 
> > Nas nossas conversas acima estávamos enfrentando problemas dessas duas formas, e não tínhamos solução.
> 
> > 
> 
> > Sobre os outros problemas que encontrou, se puder abrir uma issue informando, fico muito grato. Em breve vamos estar analisando e tentando melhorar de alguma forma.
> 
> 
> 
> Apesar de eu, agora, nesse momento, utilizar macos monterey (no dia a dia uso linux) numa maquina um pouco limitada (8gm ram - meu linux tem mais poder) nao sei o que retirar do docker. Quando voltar pra casa e rodar o docker novamente eu lanco PRs. Sobre IOs, eu so tenho android. 
> 
> 
> 
> Sim, sobre documentacao, algumas estao "erradas/defasadas/desatualizadas", uma delas esta com o metodo sendgif duplicado. Eu to querendo sentar no meu linux, testar o que der, e atualizar as documentacoes.

Se conseguir fazer isso, você não tem noção do quanto irá ajudar! 
Perfeito Igor, irei fazer novos testes nesses outros tipos de dispositivos e retorno nessa issue.

**Comment by Saifallak** [comment]
Sorry for ping.
But any solution or where is the problem exactly?

**Comment by icleitoncosta** [comment]
> Sorry for ping.
> 
> But any solution or where is the problem exactly?

unfortunately there is no solution. besides us, no other project also solved it.

**Comment by Saifallak** [comment]
> > Sorry for ping.
> > But any solution or where is the problem exactly?
> 
> unfortunately there is no solution. besides us, no other project also solved it.

Sad, hope it gets solved soon.
Thanks for your time.

**Comment by afgomezt** [comment]
Alguna solución para este problema? 

Any solution for this problem?

**Comment by renat473** [comment]
deprecated
