### ISSUE TITLE
Timed out after 30000 ms while trying to connect to Chrome!

### ISSUE THREAD

**Issue by rhutikcodes** [wppconnect-team/wppconnect-server#985]
I am trying to deploy this to cloud run, however I am getting "Timed out after 30000 ms while trying to connect to Chrome!" error. How to properly deploy this to cloud run or any serverless platform?

**Comment by icleitoncosta** [comment]
It is necessary to have a server, because it is necessary to have chrome installed to run whatsapp web in backend.
